
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BKitchenGrillSouth_Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6479, 0, 0, 13}, {2547, 1, 0, 13}, {2530, 2, 0, 11}// 1	2	3	
			, {2500, -1, 0, 11}, {7707, 2, 1, 9}, {7711, -1, 1, 9}// 4	5	6	
			, {2450, -1, 1, 8}, {7704, 1, 1, 8}, {7704, 0, 1, 8}// 7	9	11	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BKitchenGrillSouth_AddonDeed();
			}
		}

		[ Constructable ]
		public BKitchenGrillSouth_Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 4846, 1, 1, 6, 0, 1, "hot coals", 1);// 8
			AddComplexComponent( (BaseAddon) this, 3530, 1, 1, 7, 1954, -1, "grate", 1);// 10
			AddComplexComponent( (BaseAddon) this, 3530, 0, 1, 7, 1954, -1, "grate", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1300, 2, 1, 9, 1153, -1, "grill", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1300, 2, 0, 11, 1153, -1, "grill", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1300, 1, 0, 13, 1153, -1, "grill", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1300, 0, 0, 13, 1153, -1, "grill", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1300, -1, 1, 8, 1153, -1, "grill", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1300, -1, 0, 11, 1153, -1, "grill", 1);// 18
			AddComplexComponent( (BaseAddon) this, 4846, 1, 1, 7, 0, 1, "hot coals", 1);// 19
			AddComplexComponent( (BaseAddon) this, 4846, 0, 1, 6, 0, 1, "hot coals", 1);// 20
			AddComplexComponent( (BaseAddon) this, 19207, 2, 1, 3, 1310, -1, "grill", 1);// 21
			AddComplexComponent( (BaseAddon) this, 19207, 2, 0, 5, 1310, -1, "grill", 1);// 22
			AddComplexComponent( (BaseAddon) this, 19207, 1, 0, 7, 1310, -1, "grill", 1);// 23
			AddComplexComponent( (BaseAddon) this, 19207, 0, 0, 7, 1310, -1, "grill", 1);// 24
			AddComplexComponent( (BaseAddon) this, 19207, -1, 1, 2, 1310, -1, "grill", 1);// 25
			AddComplexComponent( (BaseAddon) this, 19207, -1, 0, 5, 1310, -1, "grill", 1);// 26
			AddComplexComponent( (BaseAddon) this, 19207, 2, 1, 0, 1310, -1, "grill", 1);// 27
			AddComplexComponent( (BaseAddon) this, 19207, 2, 0, 0, 1310, -1, "grill", 1);// 28
			AddComplexComponent( (BaseAddon) this, 19207, 1, 1, 0, 1310, -1, "grill", 1);// 29
			AddComplexComponent( (BaseAddon) this, 19207, 1, 0, 0, 1310, -1, "grill", 1);// 30
			AddComplexComponent( (BaseAddon) this, 19207, 0, 1, 0, 1310, -1, "grill", 1);// 31
			AddComplexComponent( (BaseAddon) this, 19207, 0, 0, 0, 1310, -1, "grill", 1);// 32
			AddComplexComponent( (BaseAddon) this, 19207, -1, 0, 0, 1310, -1, "grill", 1);// 33
			AddComplexComponent( (BaseAddon) this, 19207, -1, 1, 0, 1310, -1, "grill", 1);// 34

		}

		public BKitchenGrillSouth_Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BKitchenGrillSouth_AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BKitchenGrillSouth_Addon();
			}
		}

		[Constructable]
		public BKitchenGrillSouth_AddonDeed()
		{
			Name = "BKitchenGrillSouth_";
		}

		public BKitchenGrillSouth_AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}