
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CookieStationEast_Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {11229, -1, 0, 10}, {11232, -1, 0, 12}, {11234, -1, -1, 14}// 2	3	4	
			, {11234, -1, -1, 12}, {11234, -1, -1, 10}, {11233, -1, -1, 10}// 5	6	7	
			, {5643, -1, -2, 13}, {5643, -1, -2, 12}, {5643, -1, -2, 11}// 8	9	10	
			, {5643, -1, -2, 10}, {11230, -1, 1, 14}, {11232, 0, 1, 6}// 11	17	18	
			, {11228, 0, 2, 8}, {2879, -1, -2, 4}, {2877, -1, -1, 4}// 19	25	26	
			, {2877, -1, 0, 4}, {2879, -1, 1, 4}// 27	28	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CookieStationEast_AddonDeed();
			}
		}

		[ Constructable ]
		public CookieStationEast_Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 5162, 0, -1, 4, 0, -1, "pot of icing", 1);// 1
			AddComplexComponent( (BaseAddon) this, 9005, 1, -2, 0, 98, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 3645, 0, -2, 7, 33, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 3645, 0, -2, 4, 73, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 5164, 0, -2, 10, 0, 2, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 5168, 0, -2, 14, 0, 2, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2540, 0, 1, 8, 73, -1, "jar of cookies", 1);// 20
			AddComplexComponent( (BaseAddon) this, 18085, 0, 1, 4, 1194, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 18085, -1, 1, 12, 1195, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 18085, -1, 1, 10, 1172, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2602, 0, 0, 4, 33, -1, "", 1);// 24

		}

		public CookieStationEast_Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CookieStationEast_AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CookieStationEast_Addon();
			}
		}

		[Constructable]
		public CookieStationEast_AddonDeed()
		{
			Name = "CookieStationEast_";
		}

		public CookieStationEast_AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}