
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Halloween_CreepyPlace_SAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4652, 2, 1, 20}, {4655, -1, 1, 2}, {4650, 3, 1, 1}// 1	2	3	
			, {7573, 0, 1, 13}, {4310, -2, 1, 0}, {6661, 3, 0, 0}// 4	7	8	
			, {8783, 1, 1, 34}, {2420, -1, 0, 0}// 9	15	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Halloween_CreepyPlace_SAddonDeed();
			}
		}

		[ Constructable ]
		public Halloween_CreepyPlace_SAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 6914, 2, 1, 40, 1109, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 6920, -1, 0, 40, 1109, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 6232, 2, 1, 20, 0, 0, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 6232, -2, 1, 20, 0, 0, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 14736, 0, 0, 0, 0, 0, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 14736, -1, 0, 0, 0, 0, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 4012, -1, 0, 0, 0, 2, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2416, -1, 0, 8, 0, -1, "Stew", 1);// 16
			AddComplexComponent( (BaseAddon) this, 4012, 1, 0, 1, 0, 0, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 4012, 0, 0, 1, 0, 0, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 4012, -1, 0, 1, 0, 0, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 88, 0, -1, 0, 1109, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 88, -1, -1, 0, 1109, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 379, 2, 0, 20, 1108, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 378, 0, 0, 20, 1108, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 378, 1, 0, 20, 1108, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 378, -1, 0, 20, 1108, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 380, -2, 0, 20, 1108, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 1181, 1, 0, 0, 1108, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1181, 0, 0, 0, 1108, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1181, -1, 0, 0, 1108, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 382, 2, 1, 0, 1108, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 382, -2, 1, 0, 1108, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 375, 2, 0, 0, 1108, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 375, -2, 0, 0, 1108, -1, "", 1);// 33

		}

		public Halloween_CreepyPlace_SAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Halloween_CreepyPlace_SAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Halloween_CreepyPlace_SAddon();
			}
		}

		[Constructable]
		public Halloween_CreepyPlace_SAddonDeed()
		{
			Name = "Halloween_CreepyPlace_S";
		}

		public Halloween_CreepyPlace_SAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}