
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Halloween_PilloryAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4735, 0, 2, 0}, {4734, 1, 2, 0}, {4740, 1, 1, 0}// 1	2	3	
			, {4738, 0, 1, 0}, {4737, -1, 1, 0}, {4736, -1, 2, 0}// 4	5	6	
			, {4745, 1, -1, 0}, {4739, 1, 0, 0}, {4743, -1, -1, 0}// 7	8	9	
			, {4744, 0, -1, 0}, {4738, 0, 0, 0}, {4742, -1, 0, 0}// 10	11	12	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Halloween_PilloryAddonDeed();
			}
		}

		[ Constructable ]
		public Halloween_PilloryAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public Halloween_PilloryAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Halloween_PilloryAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Halloween_PilloryAddon();
			}
		}

		[Constructable]
		public Halloween_PilloryAddonDeed()
		{
			Name = "Halloween_Pillory";
		}

		public Halloween_PilloryAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}