
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Halloween_Pillory_SouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4752, -1, 1, 0}, {4752, 0, 1, 0}, {4751, 1, 1, 0}// 1	2	3	
			, {4753, -1, 0, 0}, {4753, 0, 0, 0}, {4749, -1, -1, 0}// 4	5	6	
			, {4754, 0, -1, 0}, {4754, 1, -1, 0}, {4753, 1, 0, 0}// 7	8	9	
			, {4746, 2, 1, 0}, {4747, 2, 0, 0}, {4748, 2, -1, 0}// 10	11	12	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Halloween_Pillory_SouthAddonDeed();
			}
		}

		[ Constructable ]
		public Halloween_Pillory_SouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public Halloween_Pillory_SouthAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Halloween_Pillory_SouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Halloween_Pillory_SouthAddon();
			}
		}

		[Constructable]
		public Halloween_Pillory_SouthAddonDeed()
		{
			Name = "Halloween_Pillory_South";
		}

		public Halloween_Pillory_SouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}