
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SkullPeachTree_Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3488, 0, 0, 1}, {7572, 0, 0, 0}, {7570, 0, 1, 17}// 1	2	3	
			, {6884, 1, 0, 23}, {6880, 0, 1, 22}, {6883, 0, 1, 25}// 4	5	6	
			, {6881, 0, 0, 17}, {6883, 0, 0, 27}, {6882, 0, 0, 34}// 7	8	9	
			, {6881, 0, 0, 24}, {6880, 0, 1, 32}// 10	11	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SkullPeachTree_AddonDeed();
			}
		}

		[ Constructable ]
		public SkullPeachTree_Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public SkullPeachTree_Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SkullPeachTree_AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SkullPeachTree_Addon();
			}
		}

		[Constructable]
		public SkullPeachTree_AddonDeed()
		{
			Name = "SkullPeachTree_";
		}

		public SkullPeachTree_AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}