
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DdWCampingS6x6Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3303, -2, -1, 0}, {3261, 2, -3, 0}, {7750, 0, 0, 0}// 1	2	3	
			, {754, 3, -1, 0}, {7752, 0, -2, 0}, {7829, 0, 3, 3}// 4	5	6	
			, {500, -1, 1, 0}, {7746, 2, -2, 0}, {3210, 3, 1, 0}// 7	8	9	
			, {3245, 2, 2, 0}, {502, 1, -2, 0}, {3234, 3, 0, 0}// 10	11	12	
			, {2506, 1, 2, 0}, {7749, 1, 0, 0}, {7748, 1, -1, 0}// 13	14	15	
			, {7744, 2, 0, 0}, {3318, -1, 2, 0}, {3261, 1, -3, 0}// 16	17	18	
			, {7747, 1, -2, 0}, {3302, -2, -1, 0}, {888, 1, 2, 0}// 20	21	22	
			, {499, -1, -2, 0}, {3319, 0, 2, 0}, {887, 0, 1, 0}// 24	25	26	
			, {7745, 2, -1, 0}, {888, 0, 2, 0}, {755, 3, 1, 0}// 27	28	29	
			, {752, 2, -1, 0}, {498, 2, -1, 0}, {3701, -2, 3, 0}// 30	31	32	
			, {3236, -2, 1, 0}, {3204, -2, 2, 0}, {496, 2, 1, 0}// 33	35	36	
			, {4155, -1, 3, 0}, {502, 0, -2, 0}, {503, -1, -1, 0}// 37	38	39	
			, {7751, 0, -1, 0}, {3317, -2, 2, 0}, {501, 2, -2, 0}// 40	41	42	
			, {503, -1, 0, 0}, {498, 2, 0, 0}, {3210, 3, -2, 0}// 43	44	45	
			, {3236, -2, 0, 0}, {1540, 2, 1, 25}, {1541, 2, 0, 25}// 46	47	48	
			, {1542, 1, 0, 25}, {1543, 1, 1, 25}, {497, 0, 1, 0}// 49	50	51	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DdWCampingS6x6AddonDeed();
			}
		}

		[ Constructable ]
		public DdWCampingS6x6Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2647, 0, -1, 0, 1437, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 4012, 0, 3, 0, 0, 1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 3555, 0, 3, 2, 0, 1, "", 1);// 34

		}

		public DdWCampingS6x6Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DdWCampingS6x6AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DdWCampingS6x6Addon();
			}
		}

		[Constructable]
		public DdWCampingS6x6AddonDeed()
		{
			Name = "DdWCampingS6x6";
		}

		public DdWCampingS6x6AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}