
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Gold_DiningSet_South_1Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {11758, 2, 2, 1}, {11758, 2, 1, 1}, {11758, 2, 0, 1}// 1	2	3	
			, {11758, 2, -1, 1}, {11758, 2, -2, 1}, {11757, -2, 2, 1}// 4	5	6	
			, {11757, -2, 1, 1}, {11757, -2, 0, 1}, {11757, -2, -1, 1}// 7	8	9	
			, {11757, -2, -2, 1}, {11755, 0, 3, 1}, {11756, 0, -3, 1}// 10	11	12	
			, {9037, 0, 0, 10}, {3210, 0, 0, 9}// 13	14	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Gold_DiningSet_South_1AddonDeed();
			}
		}

		[ Constructable ]
		public Gold_DiningSet_South_1Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2845, 0, 1, 11, 0, 0, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2845, 0, -1, 10, 0, 0, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 9431, 0, 0, 6, 2721, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 2458, 1, 2, 11, 2721, -1, "Golden Goblet", 1);// 18
			AddComplexComponent( (BaseAddon) this, 2458, 1, 1, 11, 2721, -1, "Golden Goblet", 1);// 19
			AddComplexComponent( (BaseAddon) this, 2458, 1, 0, 11, 2721, -1, "Golden Goblet", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2458, 1, -1, 14, 2721, -1, "Golden Goblet", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2458, 1, -2, 11, 2721, -1, "Golden Goblet", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2458, 1, -1, 10, 2721, -1, "Golden Goblet", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2458, 0, 2, 14, 2721, -1, "Golden Goblet", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2458, 0, 3, 15, 2721, -1, "Golden Goblet", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2458, 0, 2, 10, 2721, -1, "Golden Goblet", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2458, 0, 1, 14, 2721, -1, "Golden Goblet", 1);// 27
			AddComplexComponent( (BaseAddon) this, 2458, 0, 0, 14, 2721, -1, "Golden Goblet", 1);// 28
			AddComplexComponent( (BaseAddon) this, 2458, 0, -1, 14, 2721, -1, "Golden Goblet", 1);// 29
			AddComplexComponent( (BaseAddon) this, 2517, 1, -2, 8, 2721, -1, "Golden Silverware", 1);// 30
			AddComplexComponent( (BaseAddon) this, 2517, 1, -1, 8, 2721, -1, "Golden Silverware", 1);// 31
			AddComplexComponent( (BaseAddon) this, 2517, 1, 0, 8, 2721, -1, "Golden Silverware", 1);// 32
			AddComplexComponent( (BaseAddon) this, 2517, 1, 1, 8, 2721, -1, "Golden Silverware", 1);// 33
			AddComplexComponent( (BaseAddon) this, 2517, 1, 2, 8, 2721, -1, "Golden Silverware", 1);// 34
			AddComplexComponent( (BaseAddon) this, 2516, 0, 2, 7, 2721, -1, "Golden Silverware", 1);// 35
			AddComplexComponent( (BaseAddon) this, 2493, -1, -2, 7, 2721, -1, "Golden Silverware", 1);// 36
			AddComplexComponent( (BaseAddon) this, 2493, -1, -1, 7, 2721, -1, "Golden Silverware", 1);// 37
			AddComplexComponent( (BaseAddon) this, 2493, -1, 0, 7, 2721, -1, "Golden Silverware", 1);// 38
			AddComplexComponent( (BaseAddon) this, 2493, -1, 1, 7, 2721, -1, "Golden Silverware", 1);// 39
			AddComplexComponent( (BaseAddon) this, 2493, -1, 2, 7, 2721, -1, "Golden Silverware", 1);// 40
			AddComplexComponent( (BaseAddon) this, 2494, 0, -2, 7, 2721, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 2519, 0, 2, 7, 2037, -1, "Fine China", 1);// 42
			AddComplexComponent( (BaseAddon) this, 2519, 1, 2, 7, 2037, -1, "Fine China", 1);// 43
			AddComplexComponent( (BaseAddon) this, 2519, 1, 1, 7, 2037, -1, "Fine China", 1);// 44
			AddComplexComponent( (BaseAddon) this, 2519, 1, 0, 7, 2037, -1, "Fine China", 1);// 45
			AddComplexComponent( (BaseAddon) this, 2519, 1, -1, 7, 2037, -1, "Fine China", 1);// 46
			AddComplexComponent( (BaseAddon) this, 2519, 1, -2, 7, 2037, -1, "Fine China", 1);// 47
			AddComplexComponent( (BaseAddon) this, 2519, 0, -2, 7, 2037, -1, "Fine China", 1);// 48
			AddComplexComponent( (BaseAddon) this, 2519, -1, 2, 7, 2037, -1, "Fine China", 1);// 49
			AddComplexComponent( (BaseAddon) this, 2519, -1, 1, 7, 2037, -1, "Fine China", 1);// 50
			AddComplexComponent( (BaseAddon) this, 2519, -1, 0, 7, 2037, -1, "Fine China", 1);// 51
			AddComplexComponent( (BaseAddon) this, 2519, -1, -1, 7, 2037, -1, "Fine China", 1);// 52
			AddComplexComponent( (BaseAddon) this, 2519, -1, -2, 7, 2037, -1, "Fine China", 1);// 53
			AddComplexComponent( (BaseAddon) this, 4612, 1, 2, 1, 1022, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 4612, 1, 1, 1, 1022, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 4612, 1, 0, 1, 1022, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 4612, 1, -1, 1, 1022, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 4612, 1, -2, 1, 1022, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 4614, 0, -2, 1, 1022, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 4614, 0, 2, 1, 1022, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 4614, 0, 1, 2, 1022, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 4614, 0, 0, 0, 1022, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 4614, 0, -1, 0, 1022, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 4613, -1, 2, 1, 1022, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 4613, -1, 1, 1, 1022, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 4613, -1, 0, 1, 1022, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 4613, -1, -1, 1, 1022, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 4613, -1, -2, 1, 1022, -1, "", 1);// 68

		}

		public Gold_DiningSet_South_1Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Gold_DiningSet_South_1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Gold_DiningSet_South_1Addon();
			}
		}

		[Constructable]
		public Gold_DiningSet_South_1AddonDeed()
		{
			Name = "Gold_DiningSet_South_1";
		}

		public Gold_DiningSet_South_1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}