
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GypsyWagonRoofSouth_Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1652, 0, 2, 3}, {1652, 0, 1, 3}, {1652, 0, 0, 3}// 1	2	3	
			, {1652, 0, -1, 3}, {1651, 1, -1, 3}, {1651, 1, 0, 3}// 4	5	6	
			, {1651, 1, 1, 3}, {1651, 1, 2, 3}, {1632, 0, 4, 0}// 7	8	9	
			, {1632, 1, 4, 0}, {1631, 1, -3, 0}, {1631, 0, -3, 0}// 10	11	12	
			, {1630, -1, 3, 0}, {1630, -1, 2, 0}, {1630, -1, 1, 0}// 13	14	15	
			, {1630, -1, 0, 0}, {1630, -1, -1, 0}, {1630, -1, -2, 0}// 16	17	18	
			, {1633, 2, -2, 0}, {1633, 2, -1, 0}, {1633, 2, 0, 0}// 19	20	21	
			, {1633, 2, 1, 0}, {1633, 2, 2, 0}, {1633, 2, 3, 0}// 22	23	24	
			, {1637, 0, -2, 3}, {1636, 1, -2, 3}, {1637, -1, -3, 0}// 25	26	27	
			, {1636, 2, -3, 0}, {1638, 0, 3, 3}, {1638, -1, 4, 0}// 28	29	30	
			, {1635, 1, 3, 3}, {1635, 2, 4, 0}// 31	32	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new GypsyWagonRoofSouth_AddonDeed();
			}
		}

		[ Constructable ]
		public GypsyWagonRoofSouth_Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public GypsyWagonRoofSouth_Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GypsyWagonRoofSouth_AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GypsyWagonRoofSouth_Addon();
			}
		}

		[Constructable]
		public GypsyWagonRoofSouth_AddonDeed()
		{
			Name = "GypsyWagonRoofSouth_";
		}

		public GypsyWagonRoofSouth_AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}