
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GypsyWagonTentRoofEast_Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1649, 2, 1, 3}, {1649, 1, 1, 3}, {1649, -1, 1, 3}// 1	2	3	
			, {1649, 0, 1, 3}, {1561, 0, 2, 0}, {1561, 1, 2, 0}// 4	5	6	
			, {1561, 2, 2, 0}, {1561, 3, 2, 0}, {1561, -1, 2, 0}// 7	8	9	
			, {1561, -2, 2, 0}, {1559, -3, 1, 0}, {1559, -3, 0, 0}// 10	11	12	
			, {1650, 2, 0, 3}, {1650, 1, 0, 3}, {1650, 0, 0, 3}// 13	14	15	
			, {1650, -1, 0, 3}, {1560, 3, -1, 0}, {1560, 2, -1, 0}// 16	17	18	
			, {1560, 1, -1, 0}, {1560, 0, -1, 0}, {1560, -1, -1, 0}// 19	20	21	
			, {1560, -2, -1, 0}, {1562, 4, 0, 0}, {1562, 4, 1, 0}// 22	23	24	
			, {1637, -3, -1, 0}, {1637, -2, 0, 3}, {1638, -2, 1, 3}// 25	26	27	
			, {1638, -3, 2, 0}, {1636, 3, 0, 3}, {1636, 4, -1, 0}// 28	29	30	
			, {1635, 3, 1, 3}, {1635, 4, 2, 0}// 31	32	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new GypsyWagonTentRoofEast_AddonDeed();
			}
		}

		[ Constructable ]
		public GypsyWagonTentRoofEast_Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public GypsyWagonTentRoofEast_Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GypsyWagonTentRoofEast_AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GypsyWagonTentRoofEast_Addon();
			}
		}

		[Constructable]
		public GypsyWagonTentRoofEast_AddonDeed()
		{
			Name = "GypsyWagonTentRoofEast_";
		}

		public GypsyWagonTentRoofEast_AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}