
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LunaTrainingCenter7_Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3341, 6, 21, 0}, {3341, 7, 12, 0}, {3141, 3, 22, 0}// 1	2	3	
			, {3128, 1, 22, 0}, {3143, -1, 26, 0}, {3263, 4, 22, 0}// 4	5	6	
			, {3205, 6, 23, 0}, {3207, -4, 22, 0}, {3205, 2, 22, 0}// 7	8	9	
			, {3208, 1, 24, 0}, {3205, -2, 26, 0}, {9157, -3, 20, 23}// 10	11	12	
			, {9157, -3, 19, 23}, {9157, -3, 18, 23}, {9157, -3, 17, 23}// 13	14	15	
			, {9157, -3, 16, 23}, {9160, 3, 14, 20}, {9160, 2, 14, 20}// 16	17	18	
			, {9160, 1, 14, 20}, {9160, 0, 14, 20}, {9160, -1, 14, 20}// 19	20	21	
			, {9160, -2, 14, 20}, {9153, 1, 20, 26}, {9153, 0, 20, 26}// 22	23	24	
			, {9153, -1, 20, 26}, {9154, 0, 22, 20}, {9154, -1, 22, 20}// 25	26	27	
			, {9154, -2, 22, 20}, {9154, 3, 22, 20}, {9154, 2, 22, 20}// 28	29	30	
			, {9154, 1, 22, 20}, {9154, -3, 22, 20}, {10647, 3, 19, 0}// 31	32	33	
			, {10647, 3, 14, 0}, {10575, -3, 13, 0}, {10575, 0, 13, 0}// 34	35	36	
			, {10575, -1, 13, 0}, {10575, 2, 13, 0}, {10575, 1, 13, 0}// 37	38	39	
			, {10575, 3, 13, 0}, {10650, -4, 21, 0}, {10650, -2, 21, 0}// 40	41	42	
			, {10650, -3, 21, 0}, {10650, 2, 21, 0}, {10650, 1, 21, 0}// 43	44	45	
			, {10650, 3, 21, 0}, {10647, 3, 15, 0}, {10647, 3, 21, 0}// 46	47	48	
			, {10647, 3, 16, 0}, {10647, 3, 20, 0}, {9158, -4, 15, 20}// 49	50	51	
			, {9156, 4, 15, 20}, {9156, 4, 16, 20}, {9156, 4, 17, 20}// 52	53	54	
			, {9156, 4, 18, 20}, {9156, 4, 19, 20}, {9156, 4, 20, 20}// 55	56	57	
			, {9156, 4, 21, 20}, {9158, -4, 17, 20}, {9276, 1, 17, 0}// 58	59	60	
			, {9158, -4, 18, 20}, {9158, -4, 19, 20}, {9158, -4, 20, 20}// 61	62	63	
			, {9153, 0, 21, 23}, {9153, 1, 21, 23}, {10644, 7, 16, 0}// 64	65	66	
			, {9158, -4, 21, 20}, {9159, -2, 15, 23}, {9325, 4, 21, 0}// 67	68	69	
			, {9159, 2, 15, 23}, {9159, 0, 15, 23}, {9165, 2, 16, 26}// 70	71	72	
			, {9276, -1, 21, 0}, {9159, 1, 15, 23}, {9153, 0, 19, 29}// 73	74	75	
			, {9325, 4, 14, 0}, {10575, -2, 13, 0}, {9158, -4, 16, 20}// 76	77	78	
			, {9157, -2, 17, 26}, {9161, 2, 20, 26}, {9163, -2, 20, 26}// 79	80	81	
			, {9155, 3, 16, 23}, {9166, 4, 14, 20}, {9276, 1, 15, 0}// 82	83	84	
			, {9276, 1, 14, 0}, {9276, 1, 16, 0}, {9276, -4, 18, 0}// 85	86	87	
			, {9276, -4, 19, 0}, {9276, -4, 20, 0}, {9276, 3, 14, 0}// 88	89	90	
			, {9276, 0, 16, 0}, {9276, -3, 18, 0}, {9276, 1, 20, 0}// 91	92	93	
			, {9276, -2, 21, 0}, {9276, -4, 14, 0}, {9276, -4, 21, 0}// 94	95	96	
			, {9276, 1, 19, 0}, {9276, -3, 16, 0}, {9276, 2, 14, 0}// 97	98	99	
			, {9276, 2, 19, 0}, {9276, 2, 18, 0}, {9276, 2, 20, 0}// 100	101	102	
			, {9276, -2, 14, 0}, {9276, -2, 15, 0}, {9276, -2, 16, 0}// 103	104	105	
			, {9167, -2, 16, 26}, {9167, -1, 17, 29}, {9159, 0, 17, 29}// 106	107	108	
			, {9276, -2, 19, 0}, {9276, -2, 18, 0}, {9276, -3, 17, 0}// 109	110	111	
			, {9157, -2, 18, 26}, {9157, -2, 19, 26}, {9276, -1, 19, 0}// 112	113	114	
			, {9276, -1, 18, 0}, {9276, -1, 20, 0}, {9155, 2, 17, 26}// 115	116	117	
			, {9155, 3, 19, 23}, {9276, 2, 16, 0}, {9155, 3, 20, 23}// 118	119	120	
			, {9155, 3, 17, 23}, {9155, 3, 18, 23}, {9155, 2, 18, 26}// 121	122	123	
			, {9155, 2, 19, 26}, {10575, -4, 13, 0}, {10650, 0, 21, 0}// 124	125	126	
			, {9276, 2, 15, 0}, {9276, -3, 14, 0}, {9276, -3, 15, 0}// 127	128	129	
			, {10650, -1, 21, 0}, {9276, -1, 14, 0}, {9276, 2, 21, 0}// 130	131	132	
			, {9276, 0, 20, 0}, {9276, 0, 19, 0}, {9165, 3, 15, 23}// 133	134	135	
			, {9276, 3, 18, 0}, {9276, 0, 21, 0}, {9276, -4, 15, 0}// 136	137	138	
			, {9276, 2, 17, 0}, {9276, -3, 19, 0}, {9151, 0, 18, 32}// 139	140	141	
			, {9276, -2, 20, 0}, {9276, 1, 21, 0}, {9157, -1, 18, 29}// 142	143	144	
			, {9155, 1, 18, 29}, {9153, 2, 21, 23}, {9276, 0, 17, 0}// 145	146	147	
			, {9276, -4, 16, 0}, {9276, -1, 17, 0}, {9159, -1, 16, 26}// 148	149	150	
			, {9164, -4, 22, 20}, {9276, -4, 17, 0}, {9276, -2, 17, 0}// 151	152	153	
			, {9276, -1, 16, 0}, {9153, -1, 21, 23}, {9276, -3, 20, 0}// 154	155	156	
			, {9276, -3, 21, 0}, {9161, 3, 21, 23}, {9159, 0, 16, 26}// 157	158	159	
			, {9276, 3, 17, 0}, {9162, 4, 22, 20}, {9276, 3, 16, 0}// 160	161	162	
			, {9159, -1, 15, 23}, {9276, -1, 15, 0}, {9159, 1, 16, 26}// 163	164	165	
			, {9276, 3, 19, 0}, {9153, -2, 21, 23}, {10644, 7, 19, 0}// 166	167	168	
			, {9163, -3, 21, 23}, {9167, -3, 15, 23}, {9160, -3, 14, 20}// 169	170	171	
			, {3210, 7, 14, 0}, {9276, 3, 15, 0}, {9276, 3, 20, 0}// 172	173	174	
			, {9163, -1, 19, 29}, {9276, 0, 18, 0}, {9276, 3, 21, 0}// 175	176	177	
			, {9165, 1, 17, 29}, {9161, 1, 19, 29}, {9276, 0, 15, 0}// 178	179	180	
			, {9276, 1, 18, 0}, {9276, 0, 14, 0}, {9168, -4, 14, 20}// 181	182	183	
			, {3353, 5, -2, 0}, {3145, -2, -4, 0}, {3148, 5, -3, 0}// 184	185	186	
			, {3148, 7, 7, 0}, {3145, 6, 8, 0}, {3142, 4, 11, 2}// 187	188	189	
			, {3146, 0, 10, 0}, {3146, -3, 10, 0}, {3142, 7, -2, 0}// 190	191	192	
			, {3212, -4, 9, 0}, {3213, -4, 8, 0}, {3265, -1, 10, 0}// 193	194	195	
			, {3212, 5, 10, 0}, {10644, 7, 4, 0}, {3210, 4, 11, 0}// 196	197	198	
			, {3207, 5, 11, 0}, {10644, 7, 1, 0}, {2750, 3, 1, 0}// 199	200	210	
			, {11677, -2, 3, 6}, {2750, -1, 4, 0}, {2807, 1, 0, 0}// 211	213	214	
			, {2809, 3, 6, 0}, {2750, 0, 3, 0}, {2750, 2, 1, 0}// 216	217	218	
			, {2809, 0, 6, 0}, {2750, 3, 5, 0}, {11680, 2, 0, 6}// 219	223	230	
			, {2756, -2, 6, 0}, {2807, -1, 0, 0}, {2809, -1, 6, 0}// 234	238	240	
			, {2750, 1, 5, 0}, {3342, -3, -4, 0}, {2806, -2, 5, 0}// 241	242	243	
			, {3208, -1, -4, 0}, {7617, -2, 4, 0}, {2750, 1, 4, 0}// 244	245	250	
			, {2750, 0, 1, 0}, {2755, -2, 0, 0}, {2754, 4, 6, 0}// 252	253	254	
			, {2750, 0, 5, 0}, {2807, 2, 0, 0}, {2806, -2, 1, 0}// 256	257	259	
			, {2808, 4, 5, 0}, {7622, 1, 0, 0}, {2750, -1, 5, 0}// 261	263	265	
			, {2807, 0, 0, 0}, {2750, -1, 1, 0}, {3145, -1, -3, 0}// 272	276	279	
			, {2750, 0, 4, 0}, {2750, 2, 5, 0}, {2808, 4, 4, 0}// 280	282	283	
			, {2757, 4, 0, 0}, {3211, 6, 10, 0}, {2809, 2, 6, 0}// 284	285	288	
			, {7621, 0, 0, 0}, {4031, -2, 2, 6}, {2750, -1, 3, 0}// 289	291	294	
			, {2807, 3, 0, 0}, {7620, 2, 0, 0}, {2806, -2, 3, 0}// 296	298	300	
			, {7618, -2, 2, 0}, {2809, 1, 6, 0}, {2750, 3, 2, 0}// 330	331	334	
			, {2750, 0, 2, 0}, {2750, -1, 2, 0}, {2750, 2, 4, 0}// 335	339	341	
			, {2750, 1, 2, 0}, {7619, -2, 3, 0}, {2808, 4, 3, 0}// 342	343	344	
			, {2750, 2, 3, 0}, {2750, 1, 1, 0}, {11684, 0, 0, 6}// 348	349	351	
			, {2750, 3, 4, 0}, {2750, 2, 2, 0}, {2806, -2, 4, 0}// 354	355	356	
			, {2806, -2, 2, 0}, {2750, 1, 3, 0}, {2808, 4, 2, 0}// 357	359	360	
			, {2808, 4, 1, 0}, {2750, 3, 3, 0}, {3141, 0, -4, 0}// 363	364	365	
			, {11685, 1, 0, 6}, {3150, 5, -5, 0}, {10644, 7, -12, 0}// 370	371	372	
			, {3352, -3, -10, 0}, {3342, 6, -18, 0}, {3141, 5, -17, 0}// 373	374	375	
			, {3212, 4, -5, 0}, {3263, 7, -7, 0}, {3203, 2, -9, 0}// 376	377	378	
			, {3206, -3, -7, 0}, {3203, 4, -16, 0}, {3264, -3, -19, 0}// 379	380	381	
			, {3214, -4, -20, 0}, {3146, 3, -10, 0}, {3214, 6, -6, 0}// 382	383	384	
			, {3146, 5, -16, 0}, {19519, 1, -19, 5}, {30729, 3, -18, 0}// 385	386	387	
			, {30729, 2, -18, 0}, {3143, 6, -6, 0}, {30729, 1, -18, 0}// 388	389	390	
			, {30729, 0, -18, 0}, {30729, -1, -18, 0}, {30732, 4, -18, 0}// 391	392	393	
			, {30727, 3, -19, 0}, {30727, 3, -20, 0}, {30727, 2, -19, 0}// 394	395	396	
			, {3144, -3, -8, 0}, {3149, 2, -10, 0}, {3127, 7, -7, 0}// 397	398	400	
			, {3772, 2, -19, 5}, {3003, 4, -15, 14}, {10644, 7, -19, 0}// 402	403	405	
			, {1995, 3, -15, 7}, {10644, 7, -15, 0}, {2102, 3, -16, 8}// 406	407	408	
			, {1993, 0, -15, 7}, {1993, -4, -14, 7}, {3146, 4, -16, 0}// 409	410	411	
			, {2102, 2, -16, 8}, {563, 3, -12, 15}, {1995, 2, -14, 7}// 412	413	414	
			, {569, 3, -12, 0}, {2103, 3, -12, 8}, {1993, 2, -12, 7}// 415	418	424	
			, {3142, -4, -20, 0}, {30728, 4, -20, 0}, {1993, 0, -14, 7}// 425	427	428	
			, {2973, 4, -12, 13}, {3645, -4, -15, 8}, {5758, 2, -12, 0}// 429	431	432	
			, {2102, -4, -16, 8}, {3645, -3, -15, 8}, {2973, 4, -15, 14}// 433	434	435	
			, {1993, -4, -12, 7}, {1996, -1, -14, 7}, {2102, 1, -12, 8}// 439	440	441	
			, {3645, -4, -15, 11}, {1993, -3, -14, 7}, {1996, 2, -13, 7}// 443	445	446	
			, {3645, -3, -15, 11}, {2102, 1, -16, 8}, {2102, 0, -12, 8}// 450	451	452	
			, {30727, -1, -20, 0}, {30727, -1, -19, 0}, {3712, -4, -14, 8}// 453	454	455	
			, {3127, -3, -19, 0}, {3148, -4, -6, 0}, {2102, -1, -16, 8}// 457	458	459	
			, {2102, 0, -16, 8}, {30727, 0, -20, 0}, {1993, -1, -13, 7}// 460	461	462	
			, {2102, -1, -12, 8}, {30727, 0, -19, 0}, {3703, -2, -15, 8}// 463	464	466	
			, {2102, -2, -16, 8}, {1993, 3, -13, 7}, {2103, 3, -15, 8}// 467	468	469	
			, {1993, -1, -15, 7}, {1993, 2, -15, 7}, {1996, 3, -12, 7}// 470	471	472	
			, {563, -4, -15, 24}, {2202, 4, -14, 0}, {1993, -1, -12, 7}// 473	474	475	
			, {2102, 3, -12, 8}, {2102, -3, -16, 8}, {2202, 4, -13, 0}// 476	478	479	
			, {1996, 0, -13, 7}, {3703, -1, -15, 8}, {2102, -4, -12, 8}// 480	483	484	
			, {563, 3, -16, 15}, {1996, 0, -12, 7}, {5454, -1, -20, 5}// 485	487	488	
			, {2102, -3, -12, 8}, {3703, 0, -15, 8}, {1994, 1, -15, 7}// 489	490	491	
			, {5758, -3, -12, 0}, {3127, -3, -20, 0}, {30727, 1, -20, 0}// 492	493	494	
			, {30728, 4, -19, 0}, {3703, 1, -15, 8}, {3703, 2, -15, 8}// 495	496	497	
			, {1993, 3, -14, 7}, {1993, 1, -13, 7}, {30727, 1, -19, 0}// 499	500	505	
			, {1995, -2, -15, 7}, {5758, 1, -12, 0}, {2102, -2, -12, 8}// 507	510	512	
			, {2102, 2, -12, 8}, {1993, 1, -12, 7}, {1993, -2, -14, 7}// 513	517	519	
			, {1993, 1, -14, 7}, {3143, -4, -19, 0}, {5454, -1, -19, 5}// 520	525	526	
			, {1993, -2, -13, 7}, {1993, -3, -12, 7}, {1993, -3, -13, 7}// 530	531	534	
			, {5758, -2, -12, 0}, {1993, -3, -15, 7}, {1996, -2, -12, 7}// 535	536	540	
			, {1995, -4, -15, 7}, {30727, 2, -20, 0}, {1994, -4, -13, 7}// 541	543	544	
			, {3352, 5, -25, 0}, {3210, -1, -25, 0}, {3203, 4, -26, 0}// 545	546	547	
			, {19516, 1, -23, 5}, {30730, 3, -24, 0}, {30730, -1, -24, 0}// 548	549	550	
			, {30730, 0, -24, 0}, {30730, 1, -24, 0}, {30730, 2, -24, 0}// 551	552	553	
			, {30727, 3, -21, 0}, {30727, 3, -22, 0}, {30727, 3, -23, 0}// 554	555	556	
			, {19547, 1, -21, 5}, {3127, 6, -24, 0}, {3772, 2, -23, 5}// 557	558	559	
			, {3772, 2, -21, 5}, {30728, 4, -22, 0}, {30728, 4, -21, 0}// 560	561	562	
			, {30727, -1, -23, 0}, {30727, -1, -22, 0}, {30727, -1, -21, 0}// 563	564	565	
			, {3144, -4, -21, 0}, {30727, 0, -23, 0}, {30727, 0, -22, 0}// 566	567	568	
			, {30727, 0, -21, 0}, {30727, 1, -23, 0}, {30727, 1, -22, 0}// 569	570	571	
			, {30727, 1, -21, 0}, {30728, 4, -23, 0}, {30734, 4, -24, 0}// 572	573	574	
			, {3211, 3, -26, 0}, {5454, -1, -22, 5}, {30727, 2, -23, 0}// 575	576	577	
			, {5455, -1, -23, 5}, {30727, 2, -22, 0}, {3127, 7, -22, 0}// 578	579	580	
			, {30727, 2, -21, 0}, {5454, -1, -21, 5}, {3144, 5, -26, 0}// 581	582	583	
			, {3128, -7, 20, 0}, {3212, -7, 26, 0}, {3213, -7, 19, 0}// 584	585	586	
			, {10569, -5, 16, 0}, {10569, -5, 18, 0}, {10569, -5, 17, 0}// 587	588	589	
			, {10569, -5, 20, 0}, {10569, -5, 19, 0}, {10569, -5, 21, 0}// 590	591	592	
			, {10569, -5, 15, 0}, {10572, -5, 13, 0}, {10569, -5, 14, 0}// 593	594	595	
			, {3148, -5, 11, 0}, {3128, -6, 1, 0}, {3142, -6, 3, 0}// 596	597	598	
			, {3262, -5, -2, 0}, {3206, -6, -3, 0}, {3206, -6, -1, 0}// 599	600	601	
			, {3211, -6, 2, 0}, {3206, -6, -5, 0}, {563, -5, -12, 16}// 602	603	604	
			, {2103, -5, -13, 8}, {3150, -5, -5, 0}, {2103, -5, -14, 8}// 606	607	608	
			, {2103, -5, -15, 8}, {2103, -5, -12, 8}, {3127, -6, -6, 0}// 609	610	614	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LunaTrainingCenter7_AddonDeed();
			}
		}

		[ Constructable ]
		public LunaTrainingCenter7_Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1542, -2, 0, 23, 1195, -1, "", 1);// 201
			AddComplexComponent( (BaseAddon) this, 1536, -1, 0, 23, 1195, -1, "", 1);// 202
			AddComplexComponent( (BaseAddon) this, 1536, 2, 2, 45, 1195, -1, "", 1);// 203
			AddComplexComponent( (BaseAddon) this, 1536, 3, 2, 45, 1195, -1, "", 1);// 204
			AddComplexComponent( (BaseAddon) this, 1536, 4, 2, 45, 1195, -1, "", 1);// 205
			AddComplexComponent( (BaseAddon) this, 1537, 3, 9, 45, 1195, -1, "", 1);// 206
			AddComplexComponent( (BaseAddon) this, 1537, 5, 9, 45, 1195, -1, "", 1);// 207
			AddComplexComponent( (BaseAddon) this, 1537, 4, 9, 45, 1195, -1, "", 1);// 208
			AddComplexComponent( (BaseAddon) this, 1537, 3, 7, 51, 1195, -1, "", 1);// 209
			AddComplexComponent( (BaseAddon) this, 1537, 3, 8, 48, 1195, -1, "", 1);// 212
			AddComplexComponent( (BaseAddon) this, 1536, 4, 4, 51, 1195, -1, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 1535, 2, 5, 51, 1195, -1, "", 1);// 220
			AddComplexComponent( (BaseAddon) this, 888, 6, 10, 20, 53, -1, "", 1);// 221
			AddComplexComponent( (BaseAddon) this, 888, 5, 10, 20, 53, -1, "", 1);// 222
			AddComplexComponent( (BaseAddon) this, 1540, 6, 8, 48, 1195, -1, "", 1);// 224
			AddComplexComponent( (BaseAddon) this, 1535, 1, 7, 48, 1195, -1, "", 1);// 225
			AddComplexComponent( (BaseAddon) this, 1538, 6, 5, 48, 1195, -1, "", 1);// 226
			AddComplexComponent( (BaseAddon) this, 888, 4, 10, 20, 53, -1, "", 1);// 227
			AddComplexComponent( (BaseAddon) this, 888, 1, 10, 20, 53, -1, "", 1);// 228
			AddComplexComponent( (BaseAddon) this, 1540, 7, 9, 45, 1195, -1, "", 1);// 229
			AddComplexComponent( (BaseAddon) this, 6570, 4, 0, 0, 0, 29, "", 1);// 231
			AddComplexComponent( (BaseAddon) this, 1535, 1, 5, 48, 1195, -1, "", 1);// 232
			AddComplexComponent( (BaseAddon) this, 1537, 6, 9, 45, 1195, -1, "", 1);// 233
			AddComplexComponent( (BaseAddon) this, 1542, 3, 5, 54, 1195, -1, "", 1);// 235
			AddComplexComponent( (BaseAddon) this, 1538, 5, 5, 51, 1195, -1, "", 1);// 236
			AddComplexComponent( (BaseAddon) this, 1535, 0, 8, 45, 1195, -1, "", 1);// 237
			AddComplexComponent( (BaseAddon) this, 6571, -2, 0, 18, 0, 1, "", 1);// 239
			AddComplexComponent( (BaseAddon) this, 888, 2, 10, 20, 53, -1, "", 1);// 246
			AddComplexComponent( (BaseAddon) this, 1537, 2, 8, 48, 1195, -1, "", 1);// 247
			AddComplexComponent( (BaseAddon) this, 888, 3, 10, 20, 53, -1, "", 1);// 248
			AddComplexComponent( (BaseAddon) this, 1541, 4, 5, 54, 1195, -1, "", 1);// 249
			AddComplexComponent( (BaseAddon) this, 1537, 5, 8, 48, 1195, -1, "", 1);// 251
			AddComplexComponent( (BaseAddon) this, 1536, 3, 4, 51, 1195, -1, "", 1);// 255
			AddComplexComponent( (BaseAddon) this, 1538, 7, 8, 45, 1195, -1, "", 1);// 258
			AddComplexComponent( (BaseAddon) this, 1536, 6, 2, 45, 1195, -1, "", 1);// 260
			AddComplexComponent( (BaseAddon) this, 1538, 7, 4, 45, 1195, -1, "", 1);// 262
			AddComplexComponent( (BaseAddon) this, 1543, 1, 8, 48, 1195, -1, "", 1);// 264
			AddComplexComponent( (BaseAddon) this, 1537, 4, 7, 51, 1195, -1, "", 1);// 266
			AddComplexComponent( (BaseAddon) this, 1535, 0, 3, 45, 1195, -1, "", 1);// 267
			AddComplexComponent( (BaseAddon) this, 1536, 5, 2, 45, 1195, -1, "", 1);// 268
			AddComplexComponent( (BaseAddon) this, 1535, 0, 5, 45, 1195, -1, "", 1);// 269
			AddComplexComponent( (BaseAddon) this, 1540, 5, 7, 51, 1195, -1, "", 1);// 270
			AddComplexComponent( (BaseAddon) this, 1536, 2, 3, 48, 1195, -1, "", 1);// 271
			AddComplexComponent( (BaseAddon) this, 1536, 5, 3, 48, 1195, -1, "", 1);// 273
			AddComplexComponent( (BaseAddon) this, 888, -1, 10, 20, 53, -1, "", 1);// 274
			AddComplexComponent( (BaseAddon) this, 1536, 4, 3, 48, 1195, -1, "", 1);// 275
			AddComplexComponent( (BaseAddon) this, 1538, 6, 7, 48, 1195, -1, "", 1);// 277
			AddComplexComponent( (BaseAddon) this, 1538, 6, 4, 48, 1195, -1, "", 1);// 278
			AddComplexComponent( (BaseAddon) this, 888, 0, 10, 20, 53, -1, "", 1);// 281
			AddComplexComponent( (BaseAddon) this, 1538, 7, 7, 45, 1195, -1, "", 1);// 286
			AddComplexComponent( (BaseAddon) this, 1536, 3, 3, 48, 1195, -1, "", 1);// 287
			AddComplexComponent( (BaseAddon) this, 3827, -2, 4, 6, 0, -1, "", 2);// 290
			AddComplexComponent( (BaseAddon) this, 1535, -2, 2, 23, 1195, -1, "", 1);// 292
			AddComplexComponent( (BaseAddon) this, 1538, 7, 6, 45, 1195, -1, "", 1);// 293
			AddComplexComponent( (BaseAddon) this, 1542, 2, 4, 51, 1195, -1, "", 1);// 295
			AddComplexComponent( (BaseAddon) this, 1538, 6, 6, 48, 1195, -1, "", 1);// 297
			AddComplexComponent( (BaseAddon) this, 1535, 0, 7, 45, 1195, -1, "", 1);// 299
			AddComplexComponent( (BaseAddon) this, 500, -3, 7, 0, 1195, -1, "", 1);// 301
			AddComplexComponent( (BaseAddon) this, 503, -3, 5, 0, 1195, -1, "", 1);// 302
			AddComplexComponent( (BaseAddon) this, 503, -3, 6, 0, 1195, -1, "", 1);// 303
			AddComplexComponent( (BaseAddon) this, 503, -3, 3, 0, 1195, -1, "", 1);// 304
			AddComplexComponent( (BaseAddon) this, 503, -3, 4, 0, 1195, -1, "", 1);// 305
			AddComplexComponent( (BaseAddon) this, 503, -3, 1, 0, 1195, -1, "", 1);// 306
			AddComplexComponent( (BaseAddon) this, 503, -3, 2, 0, 1195, -1, "", 1);// 307
			AddComplexComponent( (BaseAddon) this, 502, -2, -1, 0, 1195, -1, "", 1);// 308
			AddComplexComponent( (BaseAddon) this, 502, -1, -1, 0, 1195, -1, "", 1);// 309
			AddComplexComponent( (BaseAddon) this, 502, 1, -1, 0, 1195, -1, "", 1);// 310
			AddComplexComponent( (BaseAddon) this, 502, 2, -1, 0, 1195, -1, "", 1);// 311
			AddComplexComponent( (BaseAddon) this, 502, 3, -1, 0, 1195, -1, "", 1);// 312
			AddComplexComponent( (BaseAddon) this, 502, 0, -1, 0, 1195, -1, "", 1);// 313
			AddComplexComponent( (BaseAddon) this, 497, -2, 7, 0, 1195, -1, "", 1);// 314
			AddComplexComponent( (BaseAddon) this, 497, -1, 7, 0, 1195, -1, "", 1);// 315
			AddComplexComponent( (BaseAddon) this, 497, 0, 7, 0, 1195, -1, "", 1);// 316
			AddComplexComponent( (BaseAddon) this, 497, 2, 7, 0, 1195, -1, "", 1);// 317
			AddComplexComponent( (BaseAddon) this, 497, 1, 7, 0, 1195, -1, "", 1);// 318
			AddComplexComponent( (BaseAddon) this, 497, 3, 7, 0, 1195, -1, "", 1);// 319
			AddComplexComponent( (BaseAddon) this, 503, -3, 0, 0, 1195, -1, "", 1);// 320
			AddComplexComponent( (BaseAddon) this, 502, 4, -1, 0, 1195, -1, "", 1);// 321
			AddComplexComponent( (BaseAddon) this, 496, 5, 7, 0, 1195, -1, "", 1);// 322
			AddComplexComponent( (BaseAddon) this, 498, 5, 0, 0, 1195, -1, "", 1);// 323
			AddComplexComponent( (BaseAddon) this, 498, 5, 1, 0, 1195, -1, "", 1);// 324
			AddComplexComponent( (BaseAddon) this, 498, 5, 6, 0, 1195, -1, "", 1);// 325
			AddComplexComponent( (BaseAddon) this, 498, 5, 5, 0, 1195, -1, "", 1);// 326
			AddComplexComponent( (BaseAddon) this, 497, 4, 7, 0, 1195, -1, "", 1);// 327
			AddComplexComponent( (BaseAddon) this, 739, 5, -1, 0, 1195, -1, "", 1);// 328
			AddComplexComponent( (BaseAddon) this, 1538, 5, 6, 51, 1195, -1, "", 1);// 329
			AddComplexComponent( (BaseAddon) this, 1543, 3, 6, 54, 1195, -1, "", 1);// 332
			AddComplexComponent( (BaseAddon) this, 1538, 7, 3, 45, 1195, -1, "", 1);// 333
			AddComplexComponent( (BaseAddon) this, 1541, 6, 3, 48, 1195, -1, "", 1);// 336
			AddComplexComponent( (BaseAddon) this, 1540, 4, 6, 54, 1195, -1, "", 1);// 337
			AddComplexComponent( (BaseAddon) this, 1541, 7, 2, 45, 1195, -1, "", 1);// 338
			AddComplexComponent( (BaseAddon) this, 1535, 2, 6, 51, 1195, -1, "", 1);// 340
			AddComplexComponent( (BaseAddon) this, 1543, 2, 7, 51, 1195, -1, "", 1);// 345
			AddComplexComponent( (BaseAddon) this, 1537, 4, 8, 48, 1195, -1, "", 1);// 346
			AddComplexComponent( (BaseAddon) this, 1535, 1, 6, 48, 1195, -1, "", 1);// 347
			AddComplexComponent( (BaseAddon) this, 1535, 1, 4, 48, 1195, -1, "", 1);// 350
			AddComplexComponent( (BaseAddon) this, 1535, 0, 6, 45, 1195, -1, "", 1);// 352
			AddComplexComponent( (BaseAddon) this, 1538, 7, 5, 45, 1195, -1, "", 1);// 353
			AddComplexComponent( (BaseAddon) this, 6570, -2, 0, 0, 0, 29, "", 1);// 358
			AddComplexComponent( (BaseAddon) this, 6571, 4, 0, 18, 0, 1, "", 1);// 361
			AddComplexComponent( (BaseAddon) this, 1542, 1, 3, 48, 1195, -1, "", 1);// 362
			AddComplexComponent( (BaseAddon) this, 1543, 0, 9, 45, 1195, -1, "", 1);// 366
			AddComplexComponent( (BaseAddon) this, 1537, 2, 9, 45, 1195, -1, "", 1);// 367
			AddComplexComponent( (BaseAddon) this, 1537, 1, 9, 45, 1195, -1, "", 1);// 368
			AddComplexComponent( (BaseAddon) this, 1541, 5, 4, 51, 1195, -1, "", 1);// 369
			AddComplexComponent( (BaseAddon) this, 4830, 4, -13, 14, 1931, -1, "", 1);// 399
			AddComplexComponent( (BaseAddon) this, 1562, 3, -14, 29, 1931, -1, "", 1);// 401
			AddComplexComponent( (BaseAddon) this, 569, 1, -12, 14, 1929, -1, "", 1);// 404
			AddComplexComponent( (BaseAddon) this, 569, 0, -16, 14, 1929, -1, "", 1);// 416
			AddComplexComponent( (BaseAddon) this, 569, -1, -16, 14, 1929, -1, "", 1);// 417
			AddComplexComponent( (BaseAddon) this, 569, -2, -16, 14, 1929, -1, "", 1);// 419
			AddComplexComponent( (BaseAddon) this, 569, -1, -12, 14, 1929, -1, "", 1);// 420
			AddComplexComponent( (BaseAddon) this, 569, 1, -16, 14, 1929, -1, "", 1);// 421
			AddComplexComponent( (BaseAddon) this, 1561, 2, -12, 29, 1931, -1, "", 1);// 422
			AddComplexComponent( (BaseAddon) this, 1561, 1, -12, 29, 1931, -1, "", 1);// 423
			AddComplexComponent( (BaseAddon) this, 1638, -3, -13, 32, 1931, -1, "", 1);// 426
			AddComplexComponent( (BaseAddon) this, 1649, -2, -13, 32, 1931, -1, "", 1);// 430
			AddComplexComponent( (BaseAddon) this, 569, 2, -12, 14, 1929, -1, "", 1);// 436
			AddComplexComponent( (BaseAddon) this, 1562, 3, -13, 29, 1931, -1, "", 1);// 437
			AddComplexComponent( (BaseAddon) this, 569, 3, -12, 14, 1929, -1, "", 1);// 438
			AddComplexComponent( (BaseAddon) this, 568, 3, -15, 14, 1929, -1, "", 1);// 442
			AddComplexComponent( (BaseAddon) this, 1561, -3, -12, 29, 1931, -1, "", 1);// 444
			AddComplexComponent( (BaseAddon) this, 1561, -2, -12, 29, 1931, -1, "", 1);// 447
			AddComplexComponent( (BaseAddon) this, 1560, -1, -15, 29, 1931, -1, "", 1);// 448
			AddComplexComponent( (BaseAddon) this, 569, -4, -16, 14, 1929, -1, "", 1);// 449
			AddComplexComponent( (BaseAddon) this, 1638, -4, -12, 29, 1931, -1, "", 1);// 456
			AddComplexComponent( (BaseAddon) this, 569, 0, -12, 14, 1929, -1, "", 1);// 465
			AddComplexComponent( (BaseAddon) this, 1561, 0, -12, 29, 1931, -1, "", 1);// 477
			AddComplexComponent( (BaseAddon) this, 1649, 1, -13, 32, 1931, -1, "", 1);// 481
			AddComplexComponent( (BaseAddon) this, 1561, -1, -12, 29, 1931, -1, "", 1);// 482
			AddComplexComponent( (BaseAddon) this, 1649, 0, -13, 32, 1931, -1, "", 1);// 486
			AddComplexComponent( (BaseAddon) this, 1560, -2, -15, 29, 1931, -1, "", 1);// 498
			AddComplexComponent( (BaseAddon) this, 1559, -4, -13, 29, 1931, -1, "", 1);// 501
			AddComplexComponent( (BaseAddon) this, 1650, 1, -14, 32, 1931, -1, "", 1);// 502
			AddComplexComponent( (BaseAddon) this, 1559, -4, -14, 29, 1931, -1, "", 1);// 503
			AddComplexComponent( (BaseAddon) this, 1560, 1, -15, 29, 1931, -1, "", 1);// 504
			AddComplexComponent( (BaseAddon) this, 1560, 2, -15, 29, 1931, -1, "", 1);// 506
			AddComplexComponent( (BaseAddon) this, 1560, -3, -15, 29, 1931, -1, "", 1);// 508
			AddComplexComponent( (BaseAddon) this, 1650, -2, -14, 32, 1931, -1, "", 1);// 509
			AddComplexComponent( (BaseAddon) this, 1560, 0, -15, 29, 1931, -1, "", 1);// 511
			AddComplexComponent( (BaseAddon) this, 1635, 3, -12, 29, 1931, -1, "", 1);// 514
			AddComplexComponent( (BaseAddon) this, 1635, 2, -13, 32, 1931, -1, "", 1);// 515
			AddComplexComponent( (BaseAddon) this, 1636, 3, -15, 29, 1931, -1, "", 1);// 516
			AddComplexComponent( (BaseAddon) this, 568, 3, -12, 14, 1929, -1, "", 1);// 518
			AddComplexComponent( (BaseAddon) this, 1636, 2, -14, 32, 1931, -1, "", 1);// 521
			AddComplexComponent( (BaseAddon) this, 569, 2, -16, 14, 1929, -1, "", 1);// 522
			AddComplexComponent( (BaseAddon) this, 569, -3, -16, 14, 1929, -1, "", 1);// 523
			AddComplexComponent( (BaseAddon) this, 1650, 0, -14, 32, 1931, -1, "", 1);// 524
			AddComplexComponent( (BaseAddon) this, 1650, -1, -14, 32, 1931, -1, "", 1);// 527
			AddComplexComponent( (BaseAddon) this, 569, 3, -16, 14, 1929, -1, "", 1);// 528
			AddComplexComponent( (BaseAddon) this, 2594, 4, -12, 26, 0, 2, "", 1);// 529
			AddComplexComponent( (BaseAddon) this, 1637, -4, -15, 29, 1931, -1, "", 1);// 532
			AddComplexComponent( (BaseAddon) this, 1637, -3, -14, 32, 1931, -1, "", 1);// 533
			AddComplexComponent( (BaseAddon) this, 569, -2, -12, 14, 1929, -1, "", 1);// 537
			AddComplexComponent( (BaseAddon) this, 569, -3, -12, 14, 1929, -1, "", 1);// 538
			AddComplexComponent( (BaseAddon) this, 569, -4, -12, 14, 1929, -1, "", 1);// 539
			AddComplexComponent( (BaseAddon) this, 1649, -1, -13, 32, 1931, -1, "", 1);// 542
			AddComplexComponent( (BaseAddon) this, 568, -5, -15, 14, 1929, -1, "", 1);// 605
			AddComplexComponent( (BaseAddon) this, 568, -5, -14, 14, 1929, -1, "", 1);// 611
			AddComplexComponent( (BaseAddon) this, 568, -5, -13, 14, 1929, -1, "", 1);// 612
			AddComplexComponent( (BaseAddon) this, 568, -5, -12, 14, 1929, -1, "", 1);// 613

		}

		public LunaTrainingCenter7_Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LunaTrainingCenter7_AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LunaTrainingCenter7_Addon();
			}
		}

		[Constructable]
		public LunaTrainingCenter7_AddonDeed()
		{
			Name = "LunaTrainingCenter7_";
		}

		public LunaTrainingCenter7_AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}