
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class OldWestCasino1_Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1205, 1, 6, 5}, {1205, 2, 7, 5}, {1205, 4, 6, 5}// 1	2	3	
			, {1206, 5, 7, 5}, {1206, 3, 6, 5}, {1206, 1, 7, 5}// 4	5	6	
			, {1207, 6, 6, 5}, {1207, 4, 7, 5}, {1207, 0, 6, 5}// 7	8	9	
			, {1208, 6, 7, 5}, {1208, 5, 6, 5}, {1208, 3, 7, 5}// 10	11	12	
			, {1208, 2, 6, 5}, {1208, 0, 7, 5}, {7, 3, 5, 45}// 13	14	29	
			, {7, 2, 5, 45}, {7, 1, 5, 45}, {21, 6, 5, 45}// 30	31	32	
			, {21, 6, 4, 45}, {21, 6, 3, 45}, {21, 6, 2, 45}// 33	34	35	
			, {21, 6, 1, 45}, {21, 6, 0, 45}, {21, 6, -1, 45}// 36	37	38	
			, {21, 6, -2, 45}, {21, 6, -3, 45}, {21, 6, -4, 45}// 39	40	41	
			, {21, 6, -5, 45}, {18, 4, 5, 45}, {18, 5, 5, 45}// 42	43	44	
			, {18, 6, 5, 45}, {7, 0, 5, 45}, {10, 2, 5, 25}// 45	46	126	
			, {10, 5, 5, 25}, {1848, 6, -5, 0}, {1848, 6, 0, 0}// 127	130	131	
			, {1208, 6, 5, 25}, {1208, 6, 4, 25}, {1208, 6, 3, 25}// 132	133	134	
			, {1208, 6, 2, 25}, {1208, 6, 1, 25}, {1208, 6, 0, 25}// 135	136	137	
			, {1208, 6, -1, 25}, {1208, 6, -2, 25}, {1208, 6, -3, 25}// 138	139	140	
			, {1208, 6, -4, 25}, {1208, 6, -5, 25}, {1208, 5, 5, 25}// 141	142	143	
			, {1208, 5, 4, 25}, {1208, 5, 3, 25}, {1208, 5, 2, 25}// 144	145	146	
			, {1208, 5, 1, 25}, {1208, 5, 0, 25}, {1208, 5, -1, 25}// 147	148	149	
			, {1208, 5, -2, 25}, {1208, 5, -3, 25}, {1208, 5, -4, 25}// 150	151	152	
			, {1208, 5, -5, 25}, {1208, 4, 5, 25}, {1208, 4, 4, 25}// 153	154	155	
			, {1208, 4, 3, 25}, {1208, 4, 2, 25}, {1208, 4, 1, 25}// 156	157	158	
			, {1208, 4, 0, 25}, {1208, 4, -1, 25}, {1208, 4, -2, 25}// 159	160	161	
			, {1208, 4, -3, 25}, {1208, 4, -4, 25}, {1208, 4, -5, 25}// 162	163	164	
			, {1208, 3, 5, 25}, {1208, 3, 4, 25}, {1208, 3, 3, 25}// 165	166	167	
			, {1208, 3, 2, 25}, {1208, 3, 1, 25}, {1208, 3, 0, 25}// 168	169	170	
			, {1208, 3, -1, 25}, {1208, 3, -2, 25}, {1208, 3, -3, 25}// 171	172	173	
			, {1208, 3, -4, 25}, {1208, 3, -5, 25}, {1208, 2, 5, 25}// 174	175	176	
			, {1208, 2, 4, 25}, {1208, 2, 3, 25}, {1208, 2, 2, 25}// 177	178	179	
			, {1208, 2, 1, 25}, {1208, 2, 0, 25}, {1208, 2, -1, 25}// 180	181	182	
			, {1208, 2, -2, 25}, {1208, 2, -3, 25}, {1208, 2, -4, 25}// 183	184	185	
			, {1208, 2, -5, 25}, {1208, 1, 5, 25}, {1208, 1, 4, 25}// 186	187	188	
			, {1208, 1, 3, 25}, {1208, 1, 2, 25}, {1208, 1, 1, 25}// 189	190	191	
			, {1208, 1, 0, 25}, {1208, 1, -1, 25}, {1208, 1, -2, 25}// 192	193	194	
			, {1208, 1, -3, 25}, {1208, 1, -4, 25}, {1208, 1, -5, 25}// 195	196	197	
			, {1208, 0, 5, 25}, {1208, 0, 4, 25}, {1208, 0, 3, 25}// 198	199	200	
			, {1208, 0, 2, 25}, {1208, 0, 1, 25}, {1208, 0, 0, 25}// 201	202	203	
			, {1208, 0, -1, 25}, {1208, 0, -2, 25}, {1208, 0, -3, 25}// 204	205	206	
			, {1208, 0, -4, 25}, {1208, 0, -5, 25}, {298, 6, 7, 5}// 207	208	209	
			, {298, 2, 7, 5}, {12, 2, 5, 5}, {10, 5, 5, 5}// 210	211	214	
			, {1848, 6, 1, 0}, {1205, 6, -1, 5}, {1205, 5, -2, 5}// 215	216	217	
			, {1205, 4, -3, 5}, {1205, 3, -4, 5}, {1205, 2, -5, 5}// 218	219	220	
			, {1205, 0, -3, 5}, {1205, 1, -2, 5}, {1205, 2, -1, 5}// 221	222	223	
			, {1205, 3, 0, 5}, {1205, 4, 1, 5}, {1205, 5, 2, 5}// 224	225	226	
			, {1205, 6, 3, 5}, {1205, 4, 5, 5}, {1205, 3, 4, 5}// 227	228	229	
			, {1205, 2, 3, 5}, {1205, 1, 2, 5}, {1205, 0, 1, 5}// 230	231	232	
			, {1205, 0, 5, 5}, {1206, 6, -5, 5}, {1206, 6, -2, 5}// 233	234	235	
			, {1206, 5, -3, 5}, {1206, 4, -4, 5}, {1206, 3, -5, 5}// 236	237	238	
			, {1206, 6, 2, 5}, {1206, 5, 1, 5}, {1206, 4, 0, 5}// 239	240	241	
			, {1206, 3, -1, 5}, {1206, 2, -2, 5}, {1206, 1, -3, 5}// 242	243	244	
			, {1206, 0, -4, 5}, {1206, 5, 5, 5}, {1206, 4, 4, 5}// 245	246	247	
			, {1206, 3, 3, 5}, {1206, 2, 2, 5}, {1206, 1, 1, 5}// 248	249	250	
			, {1206, 0, 0, 5}, {1206, 1, 5, 5}, {1206, 0, 4, 5}// 251	252	253	
			, {1207, 6, -3, 5}, {1207, 5, -4, 5}, {1207, 4, -5, 5}// 254	255	256	
			, {1207, 6, 1, 5}, {1207, 5, 0, 5}, {1207, 4, -1, 5}// 257	258	259	
			, {1207, 3, -2, 5}, {1207, 2, -3, 5}, {1207, 1, -4, 5}// 260	261	262	
			, {1207, 0, -5, 5}, {1207, 6, 5, 5}, {1207, 5, 4, 5}// 263	264	265	
			, {1207, 4, 3, 5}, {1207, 3, 2, 5}, {1207, 2, 1, 5}// 266	267	268	
			, {1207, 1, 0, 5}, {1207, 0, -1, 5}, {1207, 2, 5, 5}// 269	270	271	
			, {1207, 1, 4, 5}, {1207, 0, 3, 5}, {1208, 6, -4, 5}// 272	273	274	
			, {1208, 5, -5, 5}, {1208, 6, 0, 5}, {1208, 5, -1, 5}// 275	276	277	
			, {1208, 4, -2, 5}, {1208, 3, -3, 5}, {1208, 2, -4, 5}// 278	279	280	
			, {1208, 1, -5, 5}, {1208, 6, 4, 5}, {1208, 5, 3, 5}// 281	282	283	
			, {1208, 4, 2, 5}, {1208, 3, 1, 5}, {1208, 2, 0, 5}// 284	285	286	
			, {1208, 1, -1, 5}, {1208, 0, -2, 5}, {1208, 3, 5, 5}// 287	288	289	
			, {1208, 2, 4, 5}, {1208, 1, 3, 5}, {1208, 0, 2, 5}// 290	291	292	
			, {8, 6, -5, 25}, {8, 6, 0, 25}, {8, 6, 0, 5}// 293	294	295	
			, {6, 6, 5, 25}, {6, 6, 5, 5}, {11, 6, 4, 25}// 296	297	298	
			, {11, 6, 4, 5}, {11, 6, -1, 25}, {11, 6, -1, 5}// 299	300	301	
			, {13, 6, 1, 25}, {13, 6, 1, 5}, {13, 6, -4, 25}// 310	311	312	
			, {13, 6, -4, 5}, {8, 6, -5, 5}, {1848, 6, 7, 0}// 313	314	315	
			, {1848, 5, 7, 0}, {1848, 4, 7, 0}, {1848, 3, 7, 0}// 316	317	318	
			, {1848, 2, 7, 0}, {1848, 1, 7, 0}, {1848, 0, 7, 0}// 319	320	321	
			, {1848, 6, 6, 0}, {1848, 6, 5, 0}, {1848, 6, 4, 0}// 322	323	324	
			, {1848, 6, 3, 0}, {1848, 6, 2, 0}, {1848, 5, 1, 0}// 325	326	327	
			, {1848, 6, 1, 0}, {1848, 6, -1, 0}, {1848, 6, -2, 0}// 328	329	330	
			, {1848, 6, -3, 0}, {1848, 6, -4, 0}, {1848, 6, -4, 0}// 331	332	333	
			, {1848, 5, 6, 0}, {1848, 5, 5, 0}, {1848, 5, 4, 0}// 334	335	336	
			, {1848, 5, 3, 0}, {1848, 5, 2, 0}, {1848, 5, 1, 0}// 337	338	339	
			, {1848, 5, 0, 0}, {1848, 5, -1, 0}, {1848, 5, -2, 0}// 340	341	342	
			, {1848, 5, -3, 0}, {1848, 5, -4, 0}, {1848, 5, -5, 0}// 343	344	345	
			, {1848, 4, 6, 0}, {1848, 4, 5, 0}, {1848, 4, 4, 0}// 346	347	348	
			, {1848, 4, 3, 0}, {1848, 4, 2, 0}, {1848, 4, 1, 0}// 349	350	351	
			, {1848, 4, 0, 0}, {1848, 4, -1, 0}, {1848, 4, -2, 0}// 352	353	354	
			, {1848, 4, -3, 0}, {1848, 4, -4, 0}, {1848, 4, -5, 0}// 355	356	357	
			, {1848, 3, 6, 0}, {1848, 2, 6, 0}, {1848, 1, 6, 0}// 358	359	360	
			, {1848, 0, 6, 0}, {1848, 3, 5, 0}, {1848, 2, 5, 0}// 361	362	363	
			, {1848, 1, 5, 0}, {1848, 0, 5, 0}, {1848, 3, 4, 0}// 364	365	366	
			, {1848, 3, 3, 0}, {1848, 3, 2, 0}, {1848, 3, 1, 0}// 367	368	369	
			, {1848, 3, 0, 0}, {1848, 3, -1, 0}, {1848, 3, -2, 0}// 370	371	372	
			, {1848, 3, -3, 0}, {1848, 3, -4, 0}, {1848, 3, -5, 0}// 373	374	375	
			, {1848, 2, 4, 0}, {1848, 2, 3, 0}, {1848, 2, 2, 0}// 376	377	378	
			, {1848, 2, 1, 0}, {1848, 2, 0, 0}, {1848, 2, -1, 0}// 379	380	381	
			, {1848, 2, -2, 0}, {1848, 2, -3, 0}, {1848, 2, -4, 0}// 382	383	384	
			, {1848, 2, -5, 0}, {1848, 1, 4, 0}, {1848, 1, 3, 0}// 385	386	387	
			, {1848, 1, 2, 0}, {1848, 1, 1, 0}, {1848, 1, 0, 0}// 388	389	390	
			, {1848, 1, -1, 0}, {1848, 1, -2, 0}, {1848, 1, -3, 0}// 391	392	393	
			, {1848, 1, -4, 0}, {1848, 1, -5, 0}, {1848, 0, 4, 0}// 394	395	396	
			, {1848, 0, 3, 0}, {1848, 0, 2, 0}, {1848, 0, 1, 0}// 397	398	399	
			, {1848, 0, 0, 0}, {1848, 0, -1, 0}, {1848, 0, -2, 0}// 400	401	402	
			, {1848, 0, -3, 0}, {1848, 0, -4, 0}, {1848, 0, -5, 0}// 403	404	405	
			, {22, 6, -6, 45}, {22, 5, -6, 45}, {22, 4, -6, 45}// 406	407	408	
			, {22, 3, -6, 45}, {22, 2, -6, 45}, {22, 1, -6, 45}// 409	410	411	
			, {22, 0, -6, 45}, {12, 6, -6, 25}, {7, 5, -6, 25}// 412	413	414	
			, {7, 4, -6, 25}, {7, 3, -6, 25}, {7, 2, -6, 25}// 415	416	417	
			, {7, 1, -6, 25}, {7, 0, -6, 25}, {12, 6, -6, 5}// 418	419	420	
			, {7, 0, -6, 5}, {7, 1, -6, 5}, {7, 2, -6, 5}// 421	422	423	
			, {7, 3, -6, 5}, {7, 4, -6, 5}, {7, 5, -6, 5}// 424	425	426	
			, {4086, -4, 0, 11}, {2517, -2, -1, 13}, {2495, -2, -1, 13}// 427	428	429	
			, {2478, -2, -1, 12}, {2459, -2, -3, 16}, {2458, -2, -3, 12}// 430	431	432	
			, {2466, -3, -5, 11}, {2462, -4, -5, 11}, {3703, -2, 0, 5}// 433	434	439	
			, {6467, -3, -5, 17}, {6466, -4, -5, 17}, {6462, -2, 2, 11}// 440	441	442	
			, {6464, -4, -1, 11}, {3703, -2, -1, 5}, {2348, -4, -3, 5}// 443	454	456	
			, {3703, -2, -2, 5}, {3703, -2, -3, 5}, {3703, -2, -4, 5}// 460	461	462	
			, {3703, -2, -5, 5}, {1206, -1, 7, 5}, {1206, -2, 7, 5}// 463	464	465	
			, {1206, -3, 6, 5}, {1207, -2, 6, 5}, {1207, -4, 7, 5}// 466	467	468	
			, {1208, -1, 6, 5}, {1208, -3, 7, 5}, {1208, -4, 6, 5}// 469	470	471	
			, {7, -1, 5, 45}, {21, -5, 5, 45}, {21, -5, 4, 45}// 480	481	482	
			, {21, -5, 3, 45}, {21, -5, 2, 45}, {21, -5, 1, 45}// 483	484	485	
			, {21, -5, 0, 45}, {21, -5, -1, 45}, {21, -5, -2, 45}// 486	487	488	
			, {21, -5, -3, 45}, {21, -5, -4, 45}, {21, -5, -5, 45}// 489	490	491	
			, {18, -2, 5, 45}, {18, -3, 5, 45}, {18, -4, 5, 45}// 492	493	494	
			, {12, -1, 5, 25}, {12, -4, 5, 25}, {12, -4, 5, 5}// 539	542	543	
			, {8, -5, 1, 25}, {8, -5, -1, 25}, {8, -5, -5, 25}// 544	545	546	
			, {8, -5, -4, 25}, {8, -5, -3, 25}, {8, -5, -2, 25}// 547	548	549	
			, {8, -5, 0, 25}, {8, -5, 0, 25}, {8, -5, 2, 25}// 550	551	552	
			, {8, -5, 2, 25}, {8, -5, 3, 25}, {8, -5, 4, 25}// 553	554	555	
			, {13, -5, 5, 5}, {13, -5, 5, 25}, {1208, -1, 5, 25}// 556	557	558	
			, {1208, -1, 4, 25}, {1208, -1, 3, 25}, {1208, -1, 2, 25}// 559	560	561	
			, {1208, -1, 1, 25}, {1208, -1, 0, 25}, {1208, -1, -1, 25}// 562	563	564	
			, {1208, -1, -2, 25}, {1208, -1, -3, 25}, {1208, -1, -4, 25}// 565	566	567	
			, {1208, -1, -5, 25}, {1208, -2, 5, 25}, {1208, -2, 4, 25}// 568	569	570	
			, {1208, -2, 3, 25}, {1208, -2, 2, 25}, {1208, -2, 1, 25}// 571	572	573	
			, {1208, -2, 0, 25}, {1208, -2, -1, 25}, {1208, -2, -2, 25}// 574	575	576	
			, {1208, -2, -3, 25}, {1208, -2, -4, 25}, {1208, -2, -5, 25}// 577	578	579	
			, {1208, -3, 5, 25}, {1208, -3, 4, 25}, {1208, -3, 3, 25}// 580	581	582	
			, {1208, -3, 2, 25}, {1208, -3, 1, 25}, {1208, -3, 0, 25}// 583	584	585	
			, {1208, -3, -1, 25}, {1208, -3, -2, 25}, {1208, -3, -3, 25}// 586	587	588	
			, {1208, -3, -4, 25}, {1208, -3, -5, 25}, {1208, -4, 5, 25}// 589	590	591	
			, {1208, -4, 4, 25}, {1208, -4, 3, 25}, {1208, -4, 2, 25}// 592	593	594	
			, {1208, -4, 1, 25}, {1208, -4, 0, 25}, {1208, -4, -1, 25}// 595	596	597	
			, {1208, -4, -2, 25}, {1208, -4, -3, 25}, {1208, -4, -4, 25}// 598	599	600	
			, {1208, -4, -5, 25}, {298, -1, 7, 5}, {298, -5, 7, 5}// 601	602	603	
			, {8, -5, -5, 5}, {8, -5, -4, 5}, {8, -5, -3, 5}// 604	605	606	
			, {8, -5, -2, 5}, {8, -5, -1, 5}, {8, -5, 0, 5}// 607	608	609	
			, {8, -5, 1, 5}, {8, -5, 2, 5}, {8, -5, 3, 5}// 610	611	612	
			, {8, -5, 4, 5}, {10, -1, 5, 5}, {1205, -2, -5, 5}// 613	616	617	
			, {1205, -1, -4, 5}, {1205, -1, 0, 5}, {1205, -2, -1, 5}// 618	619	620	
			, {1205, -3, -2, 5}, {1205, -4, -3, 5}, {1205, -1, 4, 5}// 621	622	623	
			, {1205, -2, 3, 5}, {1205, -3, 2, 5}, {1205, -4, 1, 5}// 624	625	626	
			, {1205, -4, 5, 5}, {1206, -1, -5, 5}, {1206, -1, -1, 5}// 627	628	629	
			, {1206, -2, -2, 5}, {1206, -3, -3, 5}, {1206, -4, -4, 5}// 630	631	632	
			, {1206, -1, 3, 5}, {1206, -2, 2, 5}, {1206, -3, 1, 5}// 633	634	635	
			, {1206, -4, 0, 5}, {1206, -3, 5, 5}, {1206, -4, 4, 5}// 636	637	638	
			, {1207, -1, -2, 5}, {1207, -2, -3, 5}, {1207, -3, -4, 5}// 639	640	641	
			, {1207, -4, -5, 5}, {1207, -1, 2, 5}, {1207, -2, 1, 5}// 642	643	644	
			, {1207, -3, 0, 5}, {1207, -4, -1, 5}, {1207, -2, 5, 5}// 645	646	647	
			, {1207, -3, 4, 5}, {1207, -4, 3, 5}, {1208, -1, 5, 5}// 648	649	650	
			, {1208, -2, 4, 5}, {1208, -3, 3, 5}, {1208, -4, 2, 5}// 651	652	653	
			, {1208, -1, -3, 5}, {1208, -2, -4, 5}, {1208, -3, -5, 5}// 654	655	656	
			, {1208, -1, 1, 5}, {1208, -2, 0, 5}, {1208, -3, -1, 5}// 657	658	659	
			, {1208, -4, -2, 5}, {1848, -1, 7, 0}, {1848, -2, 7, 0}// 660	661	662	
			, {1848, -3, 7, 0}, {1848, -4, 7, 0}, {1848, -1, 6, 0}// 663	664	665	
			, {1848, -2, 6, 0}, {1848, -3, 6, 0}, {1848, -4, 6, 0}// 666	667	668	
			, {1848, -1, 5, 0}, {1848, -2, 5, 0}, {1848, -3, 5, 0}// 669	670	671	
			, {1848, -4, 5, 0}, {1848, -1, 4, 0}, {1848, -1, 3, 0}// 672	673	674	
			, {1848, -1, 2, 0}, {1848, -1, 1, 0}, {1848, -1, 0, 0}// 675	676	677	
			, {1848, -1, -1, 0}, {1848, -1, -2, 0}, {1848, -1, -3, 0}// 678	679	680	
			, {1848, -1, -4, 0}, {1848, -1, -5, 0}, {1848, -2, 4, 0}// 681	682	683	
			, {1848, -2, 3, 0}, {1848, -2, 2, 0}, {1848, -2, 1, 0}// 684	685	686	
			, {1848, -2, 0, 0}, {1848, -2, -1, 0}, {1848, -2, -2, 0}// 687	688	689	
			, {1848, -2, -3, 0}, {1848, -2, -4, 0}, {1848, -2, -5, 0}// 690	691	692	
			, {1848, -3, 4, 0}, {1848, -3, 3, 0}, {1848, -3, 2, 0}// 693	694	695	
			, {1848, -3, 1, 0}, {1848, -3, 0, 0}, {1848, -3, -1, 0}// 696	697	698	
			, {1848, -3, -2, 0}, {1848, -3, -3, 0}, {1848, -3, -4, 0}// 699	700	701	
			, {1848, -3, -5, 0}, {1848, -4, 4, 0}, {1848, -4, 3, 0}// 702	703	704	
			, {1848, -4, 2, 0}, {1848, -4, 1, 0}, {1848, -4, 0, 0}// 705	706	707	
			, {1848, -4, -1, 0}, {1848, -4, -2, 0}, {1848, -4, -3, 0}// 708	709	710	
			, {1848, -4, -4, 0}, {1848, -4, -5, 0}, {22, -1, -6, 45}// 711	712	713	
			, {22, -2, -6, 45}, {22, -3, -6, 45}, {22, -4, -6, 45}// 714	715	716	
			, {23, -5, -6, 45}, {7, -1, -6, 25}, {7, -2, -6, 25}// 717	718	719	
			, {7, -3, -6, 25}, {7, -4, -6, 25}, {7, -4, -6, 5}// 720	721	722	
			, {7, -2, -6, 5}, {7, -3, -6, 5}, {7, -1, -6, 5}// 723	724	725	
			, {298, -5, -6, 5}// 726	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new OldWestCasino1_AddonDeed();
			}
		}

		[ Constructable ]
		public OldWestCasino1_Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 11343, 6, 7, 21, 1900, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 11343, 5, 7, 21, 1900, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 11343, 4, 7, 21, 1900, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 11343, 3, 7, 21, 1900, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 11343, 2, 7, 21, 1900, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 11343, 1, 7, 21, 1900, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 11343, 0, 7, 21, 1900, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 11343, 6, 6, 23, 1900, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 11343, 5, 6, 23, 1900, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 11343, 4, 6, 23, 1900, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 11343, 3, 6, 23, 1900, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 11343, 2, 6, 23, 1900, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 11343, 1, 6, 23, 1900, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 11343, 0, 6, 23, 1900, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1173, 6, 5, 45, 1109, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 1173, 6, 4, 45, 1109, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 1173, 6, 3, 45, 1109, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 1173, 6, 2, 45, 1109, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 1173, 6, 1, 45, 1109, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 1173, 6, 0, 45, 1109, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 1173, 6, -1, 45, 1109, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 1173, 6, -2, 45, 1109, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 1173, 6, -3, 45, 1109, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 1173, 6, -4, 45, 1109, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1173, 6, -5, 45, 1109, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1173, 5, 5, 45, 1109, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 1173, 5, 4, 45, 1109, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 1173, 5, 3, 45, 1109, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1173, 5, 2, 45, 1109, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1173, 5, 1, 45, 1109, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 1173, 5, 0, 45, 1109, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 1173, 5, -1, 45, 1109, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1173, 5, -2, 45, 1109, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 1173, 5, -3, 45, 1109, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 1173, 5, -4, 45, 1109, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 1173, 5, -5, 45, 1109, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 1173, 4, 5, 45, 1109, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 1173, 4, 4, 45, 1109, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 1173, 4, 3, 45, 1109, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 1173, 4, 2, 45, 1109, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 1173, 4, 1, 45, 1109, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 1173, 4, 0, 45, 1109, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 1173, 4, -1, 45, 1109, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 1173, 4, -2, 45, 1109, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 1173, 4, -3, 45, 1109, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 1173, 4, -4, 45, 1109, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 1173, 4, -5, 45, 1109, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 1173, 3, 5, 45, 1109, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 1173, 3, 4, 45, 1109, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 1173, 3, 3, 45, 1109, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 1173, 3, 2, 45, 1109, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 1173, 3, 1, 45, 1109, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 1173, 3, 0, 45, 1109, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 1173, 3, -1, 45, 1109, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 1173, 3, -2, 45, 1109, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 1173, 3, -3, 45, 1109, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 1173, 3, -4, 45, 1109, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 1173, 3, -5, 45, 1109, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 1173, 2, 5, 45, 1109, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 1173, 2, 4, 45, 1109, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 1173, 2, 3, 45, 1109, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 1173, 2, 2, 45, 1109, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 1173, 2, 1, 45, 1109, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 1173, 2, 0, 45, 1109, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 1173, 2, -1, 45, 1109, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 1173, 2, -2, 45, 1109, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 1173, 2, -3, 45, 1109, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 1173, 2, -4, 45, 1109, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 1173, 2, -5, 45, 1109, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 1173, 1, 5, 45, 1109, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 1173, 1, 4, 45, 1109, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 1173, 1, 3, 45, 1109, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 1173, 1, 2, 45, 1109, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 1173, 1, 1, 45, 1109, -1, "", 1);// 106
			AddComplexComponent( (BaseAddon) this, 1173, 1, 0, 45, 1109, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 1173, 1, -1, 45, 1109, -1, "", 1);// 108
			AddComplexComponent( (BaseAddon) this, 1173, 1, -2, 45, 1109, -1, "", 1);// 109
			AddComplexComponent( (BaseAddon) this, 1173, 1, -3, 45, 1109, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 1173, 1, -4, 45, 1109, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 1173, 1, -5, 45, 1109, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 1173, 0, 5, 45, 1109, -1, "", 1);// 113
			AddComplexComponent( (BaseAddon) this, 1173, 0, 4, 45, 1109, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 1173, 0, 3, 45, 1109, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 1173, 0, 2, 45, 1109, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 1173, 0, 1, 45, 1109, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 1173, 0, 0, 45, 1109, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 1173, 0, -1, 45, 1109, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 1173, 0, -2, 45, 1109, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 1173, 0, -3, 45, 1109, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 1173, 0, -4, 45, 1109, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 1173, 0, -5, 45, 1109, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 14, 1, 5, 25, 0, 42, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 14, 0, 5, 25, 0, 42, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 14, 4, 5, 25, 0, 42, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 14, 3, 5, 25, 0, 42, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 14, 3, 5, 5, 0, 42, "", 1);// 212
			AddComplexComponent( (BaseAddon) this, 14, 4, 5, 5, 0, 42, "", 1);// 213
			AddComplexComponent( (BaseAddon) this, 15, 6, 2, 25, 0, 40, "", 1);// 302
			AddComplexComponent( (BaseAddon) this, 15, 6, 3, 5, 0, 40, "", 1);// 303
			AddComplexComponent( (BaseAddon) this, 15, 6, 3, 25, 0, 40, "", 1);// 304
			AddComplexComponent( (BaseAddon) this, 15, 6, 2, 5, 0, 40, "", 1);// 305
			AddComplexComponent( (BaseAddon) this, 15, 6, -2, 25, 0, 40, "", 1);// 306
			AddComplexComponent( (BaseAddon) this, 15, 6, -2, 5, 0, 40, "", 1);// 307
			AddComplexComponent( (BaseAddon) this, 15, 6, -3, 25, 0, 40, "", 1);// 308
			AddComplexComponent( (BaseAddon) this, 15, 6, -3, 5, 0, 40, "", 1);// 309
			AddComplexComponent( (BaseAddon) this, 2879, -4, 0, 5, 1022, -1, "", 1);// 435
			AddComplexComponent( (BaseAddon) this, 2602, -1, 0, 5, 1157, -1, "", 1);// 436
			AddComplexComponent( (BaseAddon) this, 1999, -2, 0, 11, 1022, -1, "", 1);// 437
			AddComplexComponent( (BaseAddon) this, 2879, -3, -5, 5, 1022, -1, "", 1);// 438
			AddComplexComponent( (BaseAddon) this, 2602, -1, -1, 5, 1157, -1, "", 1);// 444
			AddComplexComponent( (BaseAddon) this, 2602, -1, -2, 5, 1157, -1, "", 1);// 445
			AddComplexComponent( (BaseAddon) this, 2602, -1, -3, 5, 1157, -1, "", 1);// 446
			AddComplexComponent( (BaseAddon) this, 2602, -1, -4, 5, 1157, -1, "", 1);// 447
			AddComplexComponent( (BaseAddon) this, 2602, -1, -5, 5, 1157, -1, "", 1);// 448
			AddComplexComponent( (BaseAddon) this, 1997, -2, -4, 11, 1022, -1, "", 1);// 449
			AddComplexComponent( (BaseAddon) this, 1997, -2, -2, 11, 1022, -1, "", 1);// 450
			AddComplexComponent( (BaseAddon) this, 1999, -2, -1, 11, 1022, -1, "", 1);// 451
			AddComplexComponent( (BaseAddon) this, 1999, -2, -3, 11, 1022, -1, "", 1);// 452
			AddComplexComponent( (BaseAddon) this, 1999, -2, -5, 11, 1022, -1, "", 1);// 453
			AddComplexComponent( (BaseAddon) this, 2347, -4, -2, 5, 0, 14, "", 1);// 455
			AddComplexComponent( (BaseAddon) this, 2879, -4, -5, 5, 1022, -1, "", 1);// 457
			AddComplexComponent( (BaseAddon) this, 2879, -4, -4, 5, 1022, -1, "", 1);// 458
			AddComplexComponent( (BaseAddon) this, 2879, -4, -1, 5, 1022, -1, "", 1);// 459
			AddComplexComponent( (BaseAddon) this, 11343, -1, 7, 21, 1900, -1, "", 1);// 472
			AddComplexComponent( (BaseAddon) this, 11343, -2, 7, 21, 1900, -1, "", 1);// 473
			AddComplexComponent( (BaseAddon) this, 11343, -3, 7, 21, 1900, -1, "", 1);// 474
			AddComplexComponent( (BaseAddon) this, 11343, -4, 7, 21, 1900, -1, "", 1);// 475
			AddComplexComponent( (BaseAddon) this, 11343, -1, 6, 23, 1900, -1, "", 1);// 476
			AddComplexComponent( (BaseAddon) this, 11343, -2, 6, 23, 1900, -1, "", 1);// 477
			AddComplexComponent( (BaseAddon) this, 11343, -3, 6, 23, 1900, -1, "", 1);// 478
			AddComplexComponent( (BaseAddon) this, 11343, -4, 6, 23, 1900, -1, "", 1);// 479
			AddComplexComponent( (BaseAddon) this, 1173, -1, 5, 45, 1109, -1, "", 1);// 495
			AddComplexComponent( (BaseAddon) this, 1173, -1, 4, 45, 1109, -1, "", 1);// 496
			AddComplexComponent( (BaseAddon) this, 1173, -1, 3, 45, 1109, -1, "", 1);// 497
			AddComplexComponent( (BaseAddon) this, 1173, -1, 2, 45, 1109, -1, "", 1);// 498
			AddComplexComponent( (BaseAddon) this, 1173, -1, 1, 45, 1109, -1, "", 1);// 499
			AddComplexComponent( (BaseAddon) this, 1173, -1, 0, 45, 1109, -1, "", 1);// 500
			AddComplexComponent( (BaseAddon) this, 1173, -1, -1, 45, 1109, -1, "", 1);// 501
			AddComplexComponent( (BaseAddon) this, 1173, -1, -2, 45, 1109, -1, "", 1);// 502
			AddComplexComponent( (BaseAddon) this, 1173, -1, -3, 45, 1109, -1, "", 1);// 503
			AddComplexComponent( (BaseAddon) this, 1173, -1, -4, 45, 1109, -1, "", 1);// 504
			AddComplexComponent( (BaseAddon) this, 1173, -1, -5, 45, 1109, -1, "", 1);// 505
			AddComplexComponent( (BaseAddon) this, 1173, -2, 5, 45, 1109, -1, "", 1);// 506
			AddComplexComponent( (BaseAddon) this, 1173, -2, 4, 45, 1109, -1, "", 1);// 507
			AddComplexComponent( (BaseAddon) this, 1173, -2, 3, 45, 1109, -1, "", 1);// 508
			AddComplexComponent( (BaseAddon) this, 1173, -2, 2, 45, 1109, -1, "", 1);// 509
			AddComplexComponent( (BaseAddon) this, 1173, -2, 1, 45, 1109, -1, "", 1);// 510
			AddComplexComponent( (BaseAddon) this, 1173, -2, 0, 45, 1109, -1, "", 1);// 511
			AddComplexComponent( (BaseAddon) this, 1173, -2, -1, 45, 1109, -1, "", 1);// 512
			AddComplexComponent( (BaseAddon) this, 1173, -2, -2, 45, 1109, -1, "", 1);// 513
			AddComplexComponent( (BaseAddon) this, 1173, -2, -3, 45, 1109, -1, "", 1);// 514
			AddComplexComponent( (BaseAddon) this, 1173, -2, -4, 45, 1109, -1, "", 1);// 515
			AddComplexComponent( (BaseAddon) this, 1173, -2, -5, 45, 1109, -1, "", 1);// 516
			AddComplexComponent( (BaseAddon) this, 1173, -3, 5, 45, 1109, -1, "", 1);// 517
			AddComplexComponent( (BaseAddon) this, 1173, -3, 4, 45, 1109, -1, "", 1);// 518
			AddComplexComponent( (BaseAddon) this, 1173, -3, 3, 45, 1109, -1, "", 1);// 519
			AddComplexComponent( (BaseAddon) this, 1173, -3, 2, 45, 1109, -1, "", 1);// 520
			AddComplexComponent( (BaseAddon) this, 1173, -3, 1, 45, 1109, -1, "", 1);// 521
			AddComplexComponent( (BaseAddon) this, 1173, -3, 0, 45, 1109, -1, "", 1);// 522
			AddComplexComponent( (BaseAddon) this, 1173, -3, -1, 45, 1109, -1, "", 1);// 523
			AddComplexComponent( (BaseAddon) this, 1173, -3, -2, 45, 1109, -1, "", 1);// 524
			AddComplexComponent( (BaseAddon) this, 1173, -3, -3, 45, 1109, -1, "", 1);// 525
			AddComplexComponent( (BaseAddon) this, 1173, -3, -4, 45, 1109, -1, "", 1);// 526
			AddComplexComponent( (BaseAddon) this, 1173, -3, -5, 45, 1109, -1, "", 1);// 527
			AddComplexComponent( (BaseAddon) this, 1173, -4, 5, 45, 1109, -1, "", 1);// 528
			AddComplexComponent( (BaseAddon) this, 1173, -4, 4, 45, 1109, -1, "", 1);// 529
			AddComplexComponent( (BaseAddon) this, 1173, -4, 3, 45, 1109, -1, "", 1);// 530
			AddComplexComponent( (BaseAddon) this, 1173, -4, 2, 45, 1109, -1, "", 1);// 531
			AddComplexComponent( (BaseAddon) this, 1173, -4, 1, 45, 1109, -1, "", 1);// 532
			AddComplexComponent( (BaseAddon) this, 1173, -4, 0, 45, 1109, -1, "", 1);// 533
			AddComplexComponent( (BaseAddon) this, 1173, -4, -1, 45, 1109, -1, "", 1);// 534
			AddComplexComponent( (BaseAddon) this, 1173, -4, -2, 45, 1109, -1, "", 1);// 535
			AddComplexComponent( (BaseAddon) this, 1173, -4, -3, 45, 1109, -1, "", 1);// 536
			AddComplexComponent( (BaseAddon) this, 1173, -4, -4, 45, 1109, -1, "", 1);// 537
			AddComplexComponent( (BaseAddon) this, 1173, -4, -5, 45, 1109, -1, "", 1);// 538
			AddComplexComponent( (BaseAddon) this, 14, -2, 5, 25, 0, 42, "", 1);// 540
			AddComplexComponent( (BaseAddon) this, 14, -3, 5, 25, 0, 42, "", 1);// 541
			AddComplexComponent( (BaseAddon) this, 14, -3, 5, 5, 0, 42, "", 1);// 614
			AddComplexComponent( (BaseAddon) this, 14, -2, 5, 5, 0, 42, "", 1);// 615

		}

		public OldWestCasino1_Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class OldWestCasino1_AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new OldWestCasino1_Addon();
			}
		}

		[Constructable]
		public OldWestCasino1_AddonDeed()
		{
			Name = "OldWestCasino1_";
		}

		public OldWestCasino1_AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}