
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LunaTrainingCenter9_Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3353, 6, 7, 0}, {3144, -5, 10, 0}, {3147, -5, 18, 0}// 31	34	35	
			, {3150, -5, 13, 0}, {3145, 6, 6, 0}, {3146, 1, 8, 0}// 36	37	38	
			, {3214, -5, 14, 0}, {3209, -5, 18, 0}, {3204, 6, 10, 0}// 51	54	59	
			, {3264, 6, 9, 0}, {3352, -5, 12, 0}, {3207, -5, 9, 0}// 77	93	108	
			, {3209, -4, 19, 0}, {3210, -2, 8, 0}, {3211, 0, 9, 0}// 110	111	113	
			, {2973, 5, -11, 13}, {3834, -2, -2, 6}, {3834, 2, -4, 6}// 169	184	185	
			, {3834, 0, -4, 6}, {3146, 5, -8, 0}, {3141, 2, -9, 0}// 282	284	285	
			, {3348, 3, -9, 0}, {3344, -3, -8, 0}, {7621, 0, -4, 0}// 286	287	289	
			, {3148, -3, -9, 0}, {3263, 5, -8, 0}, {3263, -5, -7, 0}// 290	291	292	
			, {3263, 2, -9, 0}, {3149, -1, -7, 0}, {3149, 2, -7, 0}// 293	294	295	
			, {7622, 1, -4, 0}, {7619, -2, -1, 0}, {7618, -2, -2, 0}// 297	299	300	
			, {3150, 6, -9, 0}, {5758, 3, -11, 1}, {5758, 2, -11, 1}// 301	326	327	
			, {5758, -1, -11, 1}, {5758, -2, -11, 1}, {1996, 4, -11, 8}// 328	329	332	
			, {1993, 3, -11, 8}, {569, 4, -11, 1}, {563, -4, -11, 17}// 333	335	336	
			, {563, 4, -11, 16}, {2102, 3, -11, 9}, {2102, 1, -11, 9}// 337	338	339	
			, {2102, 2, -11, 9}, {2103, -4, -11, 9}, {1996, 1, -11, 8}// 340	341	342	
			, {1993, 2, -11, 8}, {1993, -2, -11, 8}, {2102, -2, -11, 9}// 343	344	345	
			, {2102, -1, -11, 9}, {2102, -3, -11, 9}, {2103, 4, -11, 9}// 346	347	348	
			, {1996, -1, -11, 8}, {2102, 0, -11, 9}, {2102, 4, -11, 9}// 364	365	367	
			, {7620, 2, -4, 0}, {1993, -3, -11, 8}, {7617, -2, 0, 0}// 371	374	376	
			, {1993, 0, -11, 8}, {3128, -5, -19, 0}, {3143, 1, -18, 0}// 379	388	389	
			, {3150, -3, -18, 0}, {3212, 1, -18, 0}, {3212, -3, -18, 0}// 390	391	392	
			, {2879, 2, -14, 8}, {3144, 4, -18, 0}, {2879, 0, -14, 8}// 393	394	395	
			, {2879, -2, -14, 8}, {3263, 4, -17, 0}, {2202, 5, -13, 1}// 396	397	419	
			, {2202, 5, -12, 1}, {1993, 4, -12, 8}, {1993, 4, -13, 8}// 420	421	422	
			, {1995, 4, -14, 8}, {1993, 3, -14, 8}, {1995, 3, -13, 8}// 423	439	440	
			, {1996, 3, -12, 8}, {563, 4, -15, 16}, {2102, -2, -15, 9}// 441	442	443	
			, {2102, -1, -15, 9}, {2102, -3, -15, 9}, {2103, -4, -13, 9}// 444	445	446	
			, {1994, 2, -14, 8}, {1995, -1, -14, 8}, {1993, -2, -14, 8}// 447	448	449	
			, {1993, -2, -12, 8}, {1993, -1, -12, 8}, {2102, 2, -15, 9}// 450	451	452	
			, {2102, 0, -15, 9}, {563, -3, -14, 25}, {2102, 3, -15, 9}// 453	456	457	
			, {2102, 4, -15, 9}, {2103, 4, -14, 9}, {1993, 2, -13, 8}// 458	459	461	
			, {2103, -4, -14, 9}, {1993, -1, -13, 8}, {1995, -3, -14, 8}// 462	463	466	
			, {1994, -3, -12, 8}, {2103, -4, -12, 9}, {1996, 1, -12, 8}// 467	468	470	
			, {1993, -3, -13, 8}, {10644, 5, -20, 0}, {1993, 1, -14, 8}// 472	473	474	
			, {1993, 1, -13, 8}, {1996, 0, -13, 8}, {1993, 2, -12, 8}// 476	477	478	
			, {1993, -2, -13, 8}, {1993, 0, -12, 8}, {1993, 0, -14, 8}// 480	481	484	
			, {2102, 1, -15, 9}, {10644, -6, 18, 0}, {10644, -6, 6, 0}// 486	488	489	
			, {10644, -6, 3, 0}, {10644, -6, -20, 0}// 490	491	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LunaTrainingCenter9_AddonDeed();
			}
		}

		[ Constructable ]
		public LunaTrainingCenter9_Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2765, -2, 13, 0, 16, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2760, 0, 13, 0, 16, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2765, -2, 16, 0, 16, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1535, 0, 19, 45, 1917, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2765, -2, 14, 0, 16, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2764, 4, 12, 0, 16, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2766, 0, 12, 0, 16, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1536, 2, 14, 45, 1917, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2760, -1, 17, 0, 16, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1536, -1, 12, 23, 1917, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1542, 1, 15, 48, 1917, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2768, 3, 18, 0, 16, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2762, -2, 12, 0, 16, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1537, 4, 19, 51, 1917, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2765, -2, 15, 0, 16, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2760, 1, 16, 0, 16, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2767, 4, 16, 0, 16, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1538, 6, 17, 48, 1917, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 2760, 2, 13, 0, 16, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1540, 6, 20, 48, 1917, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2760, -1, 14, 0, 16, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2768, -1, 18, 0, 16, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2760, 3, 17, 0, 16, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 1541, 5, 16, 51, 1917, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2765, -2, 17, 0, 16, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2760, -1, 15, 0, 16, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 9010, -5, 18, 0, 1195, 29, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 9010, -5, 17, 0, 1195, 29, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 9010, -5, 16, 0, 1195, 29, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 2766, -1, 12, 0, 16, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 2766, 2, 12, 0, 16, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 2768, 1, 18, 0, 16, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 2766, 1, 12, 0, 16, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 2768, 2, 18, 0, 16, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1537, 4, 20, 48, 1917, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 2768, 0, 18, 0, 16, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1537, 5, 20, 48, 1917, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 2760, 1, 17, 0, 16, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 2763, -2, 18, 0, 16, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 2760, 0, 17, 0, 16, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 2760, 3, 15, 0, 16, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 2767, 4, 17, 0, 16, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 1537, 3, 20, 48, 1917, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 2760, 0, 16, 0, 16, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 2760, 1, 15, 0, 16, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 1535, 2, 18, 51, 1917, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 1535, 0, 15, 45, 1917, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 2760, 3, 16, 0, 16, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1536, 5, 15, 48, 1917, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1535, 0, 18, 45, 1917, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 1543, 2, 19, 51, 1917, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1541, 6, 15, 48, 1917, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1535, 1, 19, 48, 1917, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 1536, 3, 14, 45, 1917, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 1543, 1, 20, 48, 1917, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1536, 4, 15, 48, 1917, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 1536, 3, 16, 51, 1917, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 2761, 4, 18, 0, 16, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 888, -1, 6, 20, 2721, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 888, 0, 6, 20, 2721, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 888, 1, 6, 20, 2721, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 1538, 6, 18, 48, 1917, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 1538, 5, 18, 51, 1917, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 1543, 3, 18, 54, 1917, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 9010, -5, 14, 0, 1195, 29, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 9010, -5, 13, 0, 1195, 29, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 2767, 4, 14, 0, 16, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 2760, -1, 16, 0, 16, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 2767, 4, 13, 0, 16, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 888, 2, 6, 20, 2721, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 888, 3, 6, 20, 2721, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 888, 4, 6, 20, 2721, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 888, 5, 6, 20, 2721, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 888, 6, 6, 20, 2721, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 1536, 4, 14, 45, 1917, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 1537, 6, 5, 45, 1914, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 1537, 5, 5, 45, 1914, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 1537, 4, 5, 45, 1914, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 1537, 3, 5, 45, 1914, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 1537, 2, 5, 45, 1914, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 1537, 1, 5, 45, 1914, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 1543, 0, 5, 45, 1914, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 1538, 6, 19, 48, 1917, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 1536, 4, 16, 51, 1917, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 2760, 3, 13, 0, 16, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 1537, 2, 20, 48, 1917, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 1535, 2, 17, 51, 1917, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 2760, 2, 15, 0, 16, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 2760, 2, 17, 0, 16, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 1542, 2, 16, 51, 1917, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 1538, 6, 16, 48, 1917, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 2760, 2, 16, 0, 16, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 1536, 6, 14, 45, 1917, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 2760, -1, 13, 0, 16, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 1540, 4, 18, 54, 1917, -1, "", 1);// 106
			AddComplexComponent( (BaseAddon) this, 1535, 1, 17, 48, 1917, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 9010, -5, 15, 0, 1195, 29, "", 1);// 109
			AddComplexComponent( (BaseAddon) this, 1536, 5, 14, 45, 1917, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 1541, 4, 17, 54, 1917, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 1538, 5, 17, 51, 1917, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 1535, 0, 17, 45, 1917, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 500, -3, 19, 0, 1917, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 503, -3, 17, 0, 1917, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 503, -3, 18, 0, 1917, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 503, -3, 15, 0, 1917, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 503, -3, 16, 0, 1917, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 503, -3, 13, 0, 1917, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 503, -3, 14, 0, 1917, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 502, -2, 11, 0, 1917, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 502, -1, 11, 0, 1917, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 502, 1, 11, 0, 1917, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 502, 2, 11, 0, 1917, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 502, 3, 11, 0, 1917, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 502, 0, 11, 0, 1917, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 497, -2, 19, 0, 1917, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 497, -1, 19, 0, 1917, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 497, 3, 19, 0, 1917, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 503, -3, 12, 0, 1917, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 502, 4, 11, 0, 1917, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 496, 5, 19, 0, 1917, -1, "", 1);// 135
			AddComplexComponent( (BaseAddon) this, 498, 5, 12, 0, 1917, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 498, 5, 13, 0, 1917, -1, "", 1);// 137
			AddComplexComponent( (BaseAddon) this, 498, 5, 18, 0, 1917, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 498, 5, 17, 0, 1917, -1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 1542, 3, 17, 54, 1917, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 2760, 1, 14, 0, 16, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 1535, 0, 20, 45, 1917, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 498, 5, 16, 0, 1917, -1, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 498, 5, 15, 0, 1917, -1, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 498, 5, 14, 0, 1917, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 739, 5, 11, 0, 1917, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 1535, -2, 14, 23, 1917, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 2760, 3, 14, 0, 16, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 9010, -5, 12, 0, 1195, 29, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 9010, -5, 7, 0, 1195, 29, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 2760, 2, 14, 0, 16, -1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 1542, -2, 12, 23, 1917, -1, "", 1);// 152
			AddComplexComponent( (BaseAddon) this, 9010, -5, 8, 0, 1195, 29, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 9010, -5, 9, 0, 1195, 29, "", 1);// 154
			AddComplexComponent( (BaseAddon) this, 1537, 3, 19, 51, 1917, -1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 1535, 1, 18, 48, 1917, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 497, 4, 19, 0, 1917, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 2760, 0, 15, 0, 16, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 9010, -5, 10, 0, 1195, 29, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 2760, 0, 14, 0, 16, -1, "", 1);// 160
			AddComplexComponent( (BaseAddon) this, 1540, 5, 19, 51, 1917, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 2760, 1, 13, 0, 16, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 9010, -5, 11, 0, 1195, 29, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 1536, 2, 15, 48, 1917, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 1535, 1, 16, 48, 1917, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 1536, 3, 15, 48, 1917, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 2766, 3, 12, 0, 16, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 2767, 4, 15, 0, 16, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 9010, -5, 3, 0, 1195, 29, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 9010, -5, 2, 0, 1195, 29, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 9010, -5, 1, 0, 1195, 29, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 9010, -5, 0, 0, 1195, 29, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 9010, -5, -1, 0, 1195, 29, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 9010, -5, -2, 0, 1195, 29, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 9010, -5, -3, 0, 1195, 29, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 9010, -5, -4, 0, 1195, 29, "", 1);// 177
			AddComplexComponent( (BaseAddon) this, 9010, -5, -6, 0, 1195, 29, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 9010, -5, -7, 0, 1195, 29, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 9010, -5, -9, 0, 1195, 29, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 9010, -5, -10, 0, 1195, 29, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 9010, -5, -11, 0, 1195, 29, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 9010, -5, -5, 0, 1195, 29, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 1542, -2, -4, 23, 1914, -1, "", 1);// 186
			AddComplexComponent( (BaseAddon) this, 1536, -1, -4, 23, 1914, -1, "", 1);// 187
			AddComplexComponent( (BaseAddon) this, 1536, 2, -2, 45, 1914, -1, "", 1);// 188
			AddComplexComponent( (BaseAddon) this, 1536, 3, -2, 45, 1914, -1, "", 1);// 189
			AddComplexComponent( (BaseAddon) this, 1536, 4, -2, 45, 1914, -1, "", 1);// 190
			AddComplexComponent( (BaseAddon) this, 1536, 5, -2, 45, 1914, -1, "", 1);// 191
			AddComplexComponent( (BaseAddon) this, 1536, 6, -2, 45, 1914, -1, "", 1);// 192
			AddComplexComponent( (BaseAddon) this, 1535, 0, -1, 45, 1914, -1, "", 1);// 193
			AddComplexComponent( (BaseAddon) this, 1542, 1, -1, 48, 1914, -1, "", 1);// 194
			AddComplexComponent( (BaseAddon) this, 1536, 2, -1, 48, 1914, -1, "", 1);// 195
			AddComplexComponent( (BaseAddon) this, 1536, 3, -1, 48, 1914, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 1536, 4, -1, 48, 1914, -1, "", 1);// 197
			AddComplexComponent( (BaseAddon) this, 1536, 5, -1, 48, 1914, -1, "", 1);// 198
			AddComplexComponent( (BaseAddon) this, 1541, 6, -1, 48, 1914, -1, "", 1);// 199
			AddComplexComponent( (BaseAddon) this, 1535, -2, -2, 23, 1914, -1, "", 1);// 200
			AddComplexComponent( (BaseAddon) this, 1535, 1, 0, 48, 1914, -1, "", 1);// 201
			AddComplexComponent( (BaseAddon) this, 1542, 2, 0, 51, 1914, -1, "", 1);// 202
			AddComplexComponent( (BaseAddon) this, 1536, 3, 0, 51, 1914, -1, "", 1);// 203
			AddComplexComponent( (BaseAddon) this, 1536, 4, 0, 51, 1914, -1, "", 1);// 204
			AddComplexComponent( (BaseAddon) this, 1541, 5, 0, 51, 1914, -1, "", 1);// 205
			AddComplexComponent( (BaseAddon) this, 1538, 6, 0, 48, 1914, -1, "", 1);// 206
			AddComplexComponent( (BaseAddon) this, 1535, 0, 1, 45, 1914, -1, "", 1);// 207
			AddComplexComponent( (BaseAddon) this, 1535, 1, 1, 48, 1914, -1, "", 1);// 208
			AddComplexComponent( (BaseAddon) this, 1535, 2, 1, 51, 1914, -1, "", 1);// 209
			AddComplexComponent( (BaseAddon) this, 1542, 3, 1, 54, 1914, -1, "", 1);// 210
			AddComplexComponent( (BaseAddon) this, 1541, 4, 1, 54, 1914, -1, "", 1);// 211
			AddComplexComponent( (BaseAddon) this, 1538, 5, 1, 51, 1914, -1, "", 1);// 212
			AddComplexComponent( (BaseAddon) this, 1538, 6, 1, 48, 1914, -1, "", 1);// 213
			AddComplexComponent( (BaseAddon) this, 1535, 0, 2, 45, 1914, -1, "", 1);// 214
			AddComplexComponent( (BaseAddon) this, 1535, 1, 2, 48, 1914, -1, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 1535, 2, 2, 51, 1914, -1, "", 1);// 216
			AddComplexComponent( (BaseAddon) this, 1540, 4, 2, 54, 1914, -1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 1543, 3, 2, 54, 1914, -1, "", 1);// 218
			AddComplexComponent( (BaseAddon) this, 1538, 5, 2, 51, 1914, -1, "", 1);// 219
			AddComplexComponent( (BaseAddon) this, 1538, 6, 2, 48, 1914, -1, "", 1);// 220
			AddComplexComponent( (BaseAddon) this, 1538, 6, 3, 48, 1914, -1, "", 1);// 221
			AddComplexComponent( (BaseAddon) this, 1540, 5, 3, 51, 1914, -1, "", 1);// 222
			AddComplexComponent( (BaseAddon) this, 1537, 4, 3, 51, 1914, -1, "", 1);// 223
			AddComplexComponent( (BaseAddon) this, 1537, 3, 3, 51, 1914, -1, "", 1);// 224
			AddComplexComponent( (BaseAddon) this, 1543, 2, 3, 51, 1914, -1, "", 1);// 225
			AddComplexComponent( (BaseAddon) this, 1535, 1, 3, 48, 1914, -1, "", 1);// 226
			AddComplexComponent( (BaseAddon) this, 1535, 0, 3, 45, 1914, -1, "", 1);// 227
			AddComplexComponent( (BaseAddon) this, 1535, 0, 4, 45, 1914, -1, "", 1);// 228
			AddComplexComponent( (BaseAddon) this, 1537, 2, 4, 48, 1914, -1, "", 1);// 229
			AddComplexComponent( (BaseAddon) this, 1543, 1, 4, 48, 1914, -1, "", 1);// 230
			AddComplexComponent( (BaseAddon) this, 1537, 3, 4, 48, 1914, -1, "", 1);// 231
			AddComplexComponent( (BaseAddon) this, 2768, 3, 2, 0, 2721, -1, "", 1);// 232
			AddComplexComponent( (BaseAddon) this, 2768, 2, 2, 0, 2721, -1, "", 1);// 233
			AddComplexComponent( (BaseAddon) this, 2768, 1, 2, 0, 2721, -1, "", 1);// 234
			AddComplexComponent( (BaseAddon) this, 2768, 0, 2, 0, 2721, -1, "", 1);// 235
			AddComplexComponent( (BaseAddon) this, 2768, -1, 2, 0, 2721, -1, "", 1);// 236
			AddComplexComponent( (BaseAddon) this, 2767, 4, 1, 0, 2721, -1, "", 1);// 237
			AddComplexComponent( (BaseAddon) this, 2767, 4, 0, 0, 2721, -1, "", 1);// 238
			AddComplexComponent( (BaseAddon) this, 2765, -2, 1, 0, 2721, -1, "", 1);// 239
			AddComplexComponent( (BaseAddon) this, 2765, -2, 0, 0, 2721, -1, "", 1);// 240
			AddComplexComponent( (BaseAddon) this, 2763, -2, 2, 0, 2721, -1, "", 1);// 241
			AddComplexComponent( (BaseAddon) this, 2760, -1, 1, 0, 2721, -1, "", 1);// 242
			AddComplexComponent( (BaseAddon) this, 2760, 0, 1, 0, 2721, -1, "", 1);// 243
			AddComplexComponent( (BaseAddon) this, 2760, 1, 1, 0, 2721, -1, "", 1);// 244
			AddComplexComponent( (BaseAddon) this, 2760, 2, 1, 0, 2721, -1, "", 1);// 245
			AddComplexComponent( (BaseAddon) this, 2760, 3, 1, 0, 2721, -1, "", 1);// 246
			AddComplexComponent( (BaseAddon) this, 2760, 3, 0, 0, 2721, -1, "", 1);// 247
			AddComplexComponent( (BaseAddon) this, 2760, 2, 0, 0, 2721, -1, "", 1);// 248
			AddComplexComponent( (BaseAddon) this, 2760, 1, 0, 0, 2721, -1, "", 1);// 249
			AddComplexComponent( (BaseAddon) this, 2760, 0, 0, 0, 2721, -1, "", 1);// 250
			AddComplexComponent( (BaseAddon) this, 2760, -1, 0, 0, 2721, -1, "", 1);// 251
			AddComplexComponent( (BaseAddon) this, 2761, 4, 2, 0, 2721, -1, "", 1);// 252
			AddComplexComponent( (BaseAddon) this, 2767, 4, -1, 0, 2721, -1, "", 1);// 253
			AddComplexComponent( (BaseAddon) this, 2767, 4, -2, 0, 2721, -1, "", 1);// 254
			AddComplexComponent( (BaseAddon) this, 2767, 4, -3, 0, 2721, -1, "", 1);// 255
			AddComplexComponent( (BaseAddon) this, 2766, 3, -4, 0, 2721, -1, "", 1);// 256
			AddComplexComponent( (BaseAddon) this, 2766, 2, -4, 0, 2721, -1, "", 1);// 257
			AddComplexComponent( (BaseAddon) this, 2766, 1, -4, 0, 2721, -1, "", 1);// 258
			AddComplexComponent( (BaseAddon) this, 2766, 0, -4, 0, 2721, -1, "", 1);// 259
			AddComplexComponent( (BaseAddon) this, 2766, -1, -4, 0, 2721, -1, "", 1);// 260
			AddComplexComponent( (BaseAddon) this, 2765, -2, -1, 0, 2721, -1, "", 1);// 261
			AddComplexComponent( (BaseAddon) this, 2765, -2, -2, 0, 2721, -1, "", 1);// 262
			AddComplexComponent( (BaseAddon) this, 2765, -2, -3, 0, 2721, -1, "", 1);// 263
			AddComplexComponent( (BaseAddon) this, 2764, 4, -4, 0, 2721, -1, "", 1);// 264
			AddComplexComponent( (BaseAddon) this, 2762, -2, -4, 0, 2721, -1, "", 1);// 265
			AddComplexComponent( (BaseAddon) this, 2760, 3, -1, 0, 2721, -1, "", 1);// 266
			AddComplexComponent( (BaseAddon) this, 2760, 3, -2, 0, 2721, -1, "", 1);// 267
			AddComplexComponent( (BaseAddon) this, 2760, 3, -3, 0, 2721, -1, "", 1);// 268
			AddComplexComponent( (BaseAddon) this, 2760, 2, -1, 0, 2721, -1, "", 1);// 269
			AddComplexComponent( (BaseAddon) this, 2760, 2, -2, 0, 2721, -1, "", 1);// 270
			AddComplexComponent( (BaseAddon) this, 2760, 2, -3, 0, 2721, -1, "", 1);// 271
			AddComplexComponent( (BaseAddon) this, 2760, 1, -1, 0, 2721, -1, "", 1);// 272
			AddComplexComponent( (BaseAddon) this, 2760, 1, -2, 0, 2721, -1, "", 1);// 273
			AddComplexComponent( (BaseAddon) this, 2760, 1, -3, 0, 2721, -1, "", 1);// 274
			AddComplexComponent( (BaseAddon) this, 2760, 0, -1, 0, 2721, -1, "", 1);// 275
			AddComplexComponent( (BaseAddon) this, 2760, 0, -2, 0, 2721, -1, "", 1);// 276
			AddComplexComponent( (BaseAddon) this, 2760, 0, -3, 0, 2721, -1, "", 1);// 277
			AddComplexComponent( (BaseAddon) this, 2760, -1, -1, 0, 2721, -1, "", 1);// 278
			AddComplexComponent( (BaseAddon) this, 2760, -1, -2, 0, 2721, -1, "", 1);// 279
			AddComplexComponent( (BaseAddon) this, 2760, -1, -3, 0, 2721, -1, "", 1);// 280
			AddComplexComponent( (BaseAddon) this, 6570, 4, -4, 0, 0, 29, "", 1);// 281
			AddComplexComponent( (BaseAddon) this, 3834, -2, 0, 6, 2125, -1, "", 1);// 283
			AddComplexComponent( (BaseAddon) this, 6571, 4, -4, 17, 0, 1, "", 1);// 288
			AddComplexComponent( (BaseAddon) this, 1540, 6, 4, 48, 1914, -1, "", 1);// 296
			AddComplexComponent( (BaseAddon) this, 1537, 5, 4, 48, 1914, -1, "", 1);// 298
			AddComplexComponent( (BaseAddon) this, 1537, 4, 4, 48, 1914, -1, "", 1);// 302
			AddComplexComponent( (BaseAddon) this, 2594, 5, -11, 25, 0, 2, "", 1);// 303
			AddComplexComponent( (BaseAddon) this, 6571, -2, -4, 17, 0, 1, "", 1);// 304
			AddComplexComponent( (BaseAddon) this, 500, -3, 3, 0, 1914, -1, "", 1);// 305
			AddComplexComponent( (BaseAddon) this, 503, -3, 1, 0, 1914, -1, "", 1);// 306
			AddComplexComponent( (BaseAddon) this, 503, -3, 0, 0, 1914, -1, "", 1);// 307
			AddComplexComponent( (BaseAddon) this, 6570, -2, -4, 0, 0, 29, "", 1);// 308
			AddComplexComponent( (BaseAddon) this, 498, 5, -1, 0, 1914, -1, "", 1);// 309
			AddComplexComponent( (BaseAddon) this, 1561, 2, -11, 29, 52, -1, "", 1);// 310
			AddComplexComponent( (BaseAddon) this, 1561, 1, -11, 29, 52, -1, "", 1);// 311
			AddComplexComponent( (BaseAddon) this, 1561, 0, -11, 29, 52, -1, "", 1);// 312
			AddComplexComponent( (BaseAddon) this, 568, -4, -11, 16, 37, -1, "", 1);// 313
			AddComplexComponent( (BaseAddon) this, 569, -3, -11, 16, 37, -1, "", 1);// 314
			AddComplexComponent( (BaseAddon) this, 569, -2, -11, 16, 37, -1, "", 1);// 315
			AddComplexComponent( (BaseAddon) this, 569, -1, -11, 16, 37, -1, "", 1);// 316
			AddComplexComponent( (BaseAddon) this, 569, 1, -11, 16, 37, -1, "", 1);// 317
			AddComplexComponent( (BaseAddon) this, 569, 0, -11, 16, 37, -1, "", 1);// 318
			AddComplexComponent( (BaseAddon) this, 569, 2, -11, 16, 37, -1, "", 1);// 319
			AddComplexComponent( (BaseAddon) this, 569, 3, -11, 16, 37, -1, "", 1);// 320
			AddComplexComponent( (BaseAddon) this, 569, 4, -11, 16, 37, -1, "", 1);// 321
			AddComplexComponent( (BaseAddon) this, 568, 4, -11, 16, 37, -1, "", 1);// 322
			AddComplexComponent( (BaseAddon) this, 1561, -2, -11, 29, 52, -1, "", 1);// 323
			AddComplexComponent( (BaseAddon) this, 1561, -1, -11, 29, 52, -1, "", 1);// 324
			AddComplexComponent( (BaseAddon) this, 1561, 3, -11, 29, 52, -1, "", 1);// 325
			AddComplexComponent( (BaseAddon) this, 1635, 4, -11, 29, 52, -1, "", 1);// 330
			AddComplexComponent( (BaseAddon) this, 1638, -3, -11, 29, 52, -1, "", 1);// 331
			AddComplexComponent( (BaseAddon) this, 498, 5, -2, 0, 1914, -1, "", 1);// 334
			AddComplexComponent( (BaseAddon) this, 739, 5, -5, 0, 1914, -1, "", 1);// 349
			AddComplexComponent( (BaseAddon) this, 497, 4, 3, 0, 1914, -1, "", 1);// 350
			AddComplexComponent( (BaseAddon) this, 498, 5, 1, 0, 1914, -1, "", 1);// 351
			AddComplexComponent( (BaseAddon) this, 498, 5, 2, 0, 1914, -1, "", 1);// 352
			AddComplexComponent( (BaseAddon) this, 498, 5, -3, 0, 1914, -1, "", 1);// 353
			AddComplexComponent( (BaseAddon) this, 498, 5, -4, 0, 1914, -1, "", 1);// 354
			AddComplexComponent( (BaseAddon) this, 496, 5, 3, 0, 1914, -1, "", 1);// 355
			AddComplexComponent( (BaseAddon) this, 502, 4, -5, 0, 1914, -1, "", 1);// 356
			AddComplexComponent( (BaseAddon) this, 503, -3, -4, 0, 1914, -1, "", 1);// 357
			AddComplexComponent( (BaseAddon) this, 497, 3, 3, 0, 1914, -1, "", 1);// 358
			AddComplexComponent( (BaseAddon) this, 497, -1, 3, 0, 1914, -1, "", 1);// 359
			AddComplexComponent( (BaseAddon) this, 497, -2, 3, 0, 1914, -1, "", 1);// 360
			AddComplexComponent( (BaseAddon) this, 502, 0, -5, 0, 1914, -1, "", 1);// 361
			AddComplexComponent( (BaseAddon) this, 502, 3, -5, 0, 1914, -1, "", 1);// 362
			AddComplexComponent( (BaseAddon) this, 502, 2, -5, 0, 1914, -1, "", 1);// 363
			AddComplexComponent( (BaseAddon) this, 502, 1, -5, 0, 1914, -1, "", 1);// 366
			AddComplexComponent( (BaseAddon) this, 502, -1, -5, 0, 1914, -1, "", 1);// 368
			AddComplexComponent( (BaseAddon) this, 502, -2, -5, 0, 1914, -1, "", 1);// 369
			AddComplexComponent( (BaseAddon) this, 498, 5, 0, 0, 1914, -1, "", 1);// 370
			AddComplexComponent( (BaseAddon) this, 503, -3, -2, 0, 1914, -1, "", 1);// 372
			AddComplexComponent( (BaseAddon) this, 503, -3, 2, 0, 1914, -1, "", 1);// 373
			AddComplexComponent( (BaseAddon) this, 503, -3, -3, 0, 1914, -1, "", 1);// 375
			AddComplexComponent( (BaseAddon) this, 503, -3, -1, 0, 1914, -1, "", 1);// 377
			AddComplexComponent( (BaseAddon) this, 9010, -5, -8, 0, 1195, 29, "", 1);// 378
			AddComplexComponent( (BaseAddon) this, 9010, -5, -12, 0, 1195, 29, "", 1);// 380
			AddComplexComponent( (BaseAddon) this, 9010, -5, -13, 0, 1195, 29, "", 1);// 381
			AddComplexComponent( (BaseAddon) this, 9010, -5, -14, 0, 1195, 29, "", 1);// 382
			AddComplexComponent( (BaseAddon) this, 9010, -5, -16, 0, 1195, 29, "", 1);// 383
			AddComplexComponent( (BaseAddon) this, 9010, -5, -15, 0, 1195, 29, "", 1);// 384
			AddComplexComponent( (BaseAddon) this, 9010, -5, -17, 0, 1195, 29, "", 1);// 385
			AddComplexComponent( (BaseAddon) this, 9010, -5, -18, 0, 1195, 29, "", 1);// 386
			AddComplexComponent( (BaseAddon) this, 9010, -5, -19, 0, 1195, 29, "", 1);// 387
			AddComplexComponent( (BaseAddon) this, 1650, 0, -13, 32, 52, -1, "", 1);// 398
			AddComplexComponent( (BaseAddon) this, 1649, 0, -12, 32, 52, -1, "", 1);// 399
			AddComplexComponent( (BaseAddon) this, 1649, -1, -12, 32, 52, -1, "", 1);// 400
			AddComplexComponent( (BaseAddon) this, 1649, 1, -12, 32, 52, -1, "", 1);// 401
			AddComplexComponent( (BaseAddon) this, 1649, 2, -12, 32, 52, -1, "", 1);// 402
			AddComplexComponent( (BaseAddon) this, 1650, 1, -13, 32, 52, -1, "", 1);// 403
			AddComplexComponent( (BaseAddon) this, 569, -3, -15, 16, 37, -1, "", 1);// 404
			AddComplexComponent( (BaseAddon) this, 568, -4, -14, 16, 37, -1, "", 1);// 405
			AddComplexComponent( (BaseAddon) this, 568, -4, -13, 16, 37, -1, "", 1);// 406
			AddComplexComponent( (BaseAddon) this, 568, -4, -12, 16, 37, -1, "", 1);// 407
			AddComplexComponent( (BaseAddon) this, 1650, 2, -13, 32, 52, -1, "", 1);// 408
			AddComplexComponent( (BaseAddon) this, 569, -2, -15, 16, 37, -1, "", 1);// 409
			AddComplexComponent( (BaseAddon) this, 569, -1, -15, 16, 37, -1, "", 1);// 410
			AddComplexComponent( (BaseAddon) this, 569, 1, -15, 16, 37, -1, "", 1);// 411
			AddComplexComponent( (BaseAddon) this, 569, 0, -15, 16, 37, -1, "", 1);// 412
			AddComplexComponent( (BaseAddon) this, 569, 2, -15, 16, 37, -1, "", 1);// 413
			AddComplexComponent( (BaseAddon) this, 569, 3, -15, 16, 37, -1, "", 1);// 414
			AddComplexComponent( (BaseAddon) this, 569, 4, -15, 16, 37, -1, "", 1);// 415
			AddComplexComponent( (BaseAddon) this, 1559, -3, -13, 29, 52, -1, "", 1);// 416
			AddComplexComponent( (BaseAddon) this, 568, 4, -14, 16, 37, -1, "", 1);// 417
			AddComplexComponent( (BaseAddon) this, 1559, -3, -12, 29, 52, -1, "", 1);// 418
			AddComplexComponent( (BaseAddon) this, 1635, 3, -12, 32, 52, -1, "", 1);// 424
			AddComplexComponent( (BaseAddon) this, 1636, 4, -14, 29, 52, -1, "", 1);// 425
			AddComplexComponent( (BaseAddon) this, 1636, 3, -13, 32, 52, -1, "", 1);// 426
			AddComplexComponent( (BaseAddon) this, 1638, -2, -12, 32, 52, -1, "", 1);// 427
			AddComplexComponent( (BaseAddon) this, 1637, -2, -13, 32, 52, -1, "", 1);// 428
			AddComplexComponent( (BaseAddon) this, 1637, -3, -14, 29, 52, -1, "", 1);// 429
			AddComplexComponent( (BaseAddon) this, 1562, 4, -12, 29, 52, -1, "", 1);// 430
			AddComplexComponent( (BaseAddon) this, 1562, 4, -13, 29, 52, -1, "", 1);// 431
			AddComplexComponent( (BaseAddon) this, 1560, -2, -14, 29, 52, -1, "", 1);// 432
			AddComplexComponent( (BaseAddon) this, 1560, -1, -14, 29, 52, -1, "", 1);// 433
			AddComplexComponent( (BaseAddon) this, 1560, 0, -14, 29, 52, -1, "", 1);// 434
			AddComplexComponent( (BaseAddon) this, 1560, 1, -14, 29, 52, -1, "", 1);// 435
			AddComplexComponent( (BaseAddon) this, 1560, 2, -14, 29, 52, -1, "", 1);// 436
			AddComplexComponent( (BaseAddon) this, 1560, 3, -14, 29, 52, -1, "", 1);// 437
			AddComplexComponent( (BaseAddon) this, 1650, -1, -13, 32, 52, -1, "", 1);// 438
			AddComplexComponent( (BaseAddon) this, 4830, 5, -12, 15, 37, -1, "", 1);// 454
			AddComplexComponent( (BaseAddon) this, 9014, -4, -19, 0, 1195, 29, "", 1);// 455
			AddComplexComponent( (BaseAddon) this, 9014, 1, -19, 0, 1195, 29, "", 1);// 460
			AddComplexComponent( (BaseAddon) this, 9014, 5, -19, 0, 1195, 29, "", 1);// 464
			AddComplexComponent( (BaseAddon) this, 9014, -5, -19, 0, 1195, 29, "", 1);// 465
			AddComplexComponent( (BaseAddon) this, 9014, 4, -19, 0, 1195, 29, "", 1);// 469
			AddComplexComponent( (BaseAddon) this, 9014, -3, -19, 0, 1195, 29, "", 1);// 471
			AddComplexComponent( (BaseAddon) this, 9014, -1, -19, 0, 1195, 29, "", 1);// 475
			AddComplexComponent( (BaseAddon) this, 9014, 3, -19, 0, 1195, 29, "", 1);// 479
			AddComplexComponent( (BaseAddon) this, 6093, 4, -17, 0, 0, -1, "tiny flowers", 1);// 482
			AddComplexComponent( (BaseAddon) this, 9014, 2, -19, 0, 1195, 29, "", 1);// 483
			AddComplexComponent( (BaseAddon) this, 9014, 0, -19, 0, 1195, 29, "", 1);// 485
			AddComplexComponent( (BaseAddon) this, 9014, -2, -19, 0, 1195, 29, "", 1);// 487

		}

		public LunaTrainingCenter9_Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LunaTrainingCenter9_AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LunaTrainingCenter9_Addon();
			}
		}

		[Constructable]
		public LunaTrainingCenter9_AddonDeed()
		{
			Name = "LunaTrainingCenter9_";
		}

		public LunaTrainingCenter9_AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}