
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BKitchenSinkEast_Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6812, 1, -1, 9}, {2519, 0, 2, 11}, {2519, 0, 2, 9}// 6	9	11	
			, {2519, 0, 2, 7}, {2519, 0, -1, 11}, {2519, 0, -1, 9}// 13	14	15	
			, {2519, 0, -1, 7}, {4100, 1, 0, 14}, {4100, 1, 1, 14}// 16	22	23	
			, {13477, 1, 0, 6}, {13477, 1, 1, 6}// 24	25	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BKitchenSinkEast_AddonDeed();
			}
		}

		[ Constructable ]
		public BKitchenSinkEast_Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 5534, 0, 1, 0, 53, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 5534, 0, 0, 0, 53, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 41246, 0, 1, 10, 25, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 5991, 0, -1, 15, 88, -1, "towel", 1);// 4
			AddComplexComponent( (BaseAddon) this, 7192, 0, 0, 9, 2969, -1, "Palmolive", 1);// 5
			AddComplexComponent( (BaseAddon) this, 4101, 0, 1, 9, 0, -1, "comet", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1114, 0, 2, 12, 1153, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1114, 0, 2, 10, 1153, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1114, 0, 2, 8, 1153, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1114, 0, 2, 6, 1153, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1114, 0, -1, 12, 1153, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1114, 0, -1, 10, 1153, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1114, 0, -1, 8, 1153, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1114, 0, -1, 6, 1153, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 698, 1, 0, 6, 1153, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 699, 1, 1, 6, 1153, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 699, 1, 0, 6, 1153, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 699, 0, 0, 6, 1153, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 699, 0, 1, 6, 1153, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 698, 1, -1, 6, 1153, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 698, 1, 1, 6, 1153, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1300, 1, 2, 6, 1153, -1, "tile counter", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1300, 0, 2, 6, 1153, -1, "tile counter", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1300, 0, 1, 6, 1153, -1, "tile counter", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1300, 1, -1, 6, 1153, -1, "tile counter", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1300, 0, 0, 6, 1153, -1, "tile counter", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1300, 0, -1, 6, 1153, -1, "tile counter", 1);// 38
			AddComplexComponent( (BaseAddon) this, 19207, 1, 2, 0, 1310, -1, "counter", 1);// 39
			AddComplexComponent( (BaseAddon) this, 19207, 0, 2, 0, 1310, -1, "counter", 1);// 40
			AddComplexComponent( (BaseAddon) this, 19207, 1, 1, 0, 1310, -1, "counter", 1);// 41
			AddComplexComponent( (BaseAddon) this, 19207, 0, 1, 0, 1310, -1, "counter", 1);// 42
			AddComplexComponent( (BaseAddon) this, 19207, 0, 0, 0, 1310, -1, "counter", 1);// 43
			AddComplexComponent( (BaseAddon) this, 19207, 0, -1, 0, 1310, -1, "counter", 1);// 44
			AddComplexComponent( (BaseAddon) this, 19207, 1, 0, 0, 1310, -1, "counter", 1);// 45
			AddComplexComponent( (BaseAddon) this, 19207, 1, -1, 0, 1310, -1, "counter", 1);// 46

		}

		public BKitchenSinkEast_Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BKitchenSinkEast_AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BKitchenSinkEast_Addon();
			}
		}

		[Constructable]
		public BKitchenSinkEast_AddonDeed()
		{
			Name = "BKitchenSinkEast_";
		}

		public BKitchenSinkEast_AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}