
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LunaTrainingCenter5_Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3650, 33, 1, 4}, {3650, 33, 1, 0}, {3703, 33, 2, 0}// 1	2	3	
			, {3703, 33, 2, 6}, {3703, 33, 3, 0}, {10644, 28, 7, 0}// 4	5	6	
			, {10644, 17, 7, 0}, {3211, 27, 6, 0}, {3263, 21, 6, 0}// 7	11	12	
			, {3210, 23, 6, 0}, {3210, 23, 5, 0}, {10644, 31, 7, 0}// 13	14	15	
			, {2102, 29, 2, 8}, {2103, 28, 1, 8}, {2103, 28, 2, 8}// 19	20	21	
			, {2103, 28, 0, 8}, {737, 32, 2, 16}, {1999, 31, 1, 7}// 22	25	26	
			, {2103, 32, 2, 8}, {1997, 32, 0, 7}, {1997, 30, 2, 7}// 28	82	84	
			, {1997, 30, 1, 7}, {1997, 31, 0, 7}, {1998, 31, 2, 7}// 85	86	88	
			, {737, 28, 2, 15}, {3703, 32, 3, 0}, {2103, 32, 1, 8}// 90	91	94	
			, {1997, 32, 1, 7}, {2103, 32, 0, 8}, {2204, 30, 3, 0}// 99	106	108	
			, {2204, 31, 3, 0}, {1997, 32, 2, 7}, {1998, 29, 1, 7}// 109	110	111	
			, {1998, 30, 0, 7}, {1997, 29, 2, 7}, {1997, 29, 0, 7}// 112	113	114	
			, {2102, 32, 2, 8}, {3265, 24, -6, 0}, {3262, 25, -4, 0}// 124	129	130	
			, {3262, 23, -2, 0}, {3211, 17, -7, 0}, {5373, 29, -2, 14}// 131	132	134	
			, {3589, 29, -3, 14}, {1998, 31, -1, 7}, {2103, 32, -4, 8}// 135	137	138	
			, {2103, 32, -5, 8}, {2102, 31, -6, 8}, {2102, 32, -6, 8}// 139	140	141	
			, {2102, 29, -6, 8}, {2102, 30, -6, 8}, {2103, 28, -1, 8}// 142	143	144	
			, {2103, 28, -3, 8}, {2103, 28, -2, 8}, {2103, 28, -5, 8}// 145	146	147	
			, {2103, 28, -4, 8}, {2879, 29, -5, 8}, {2879, 29, -3, 8}// 148	149	150	
			, {2879, 29, -4, 8}, {2879, 31, -5, 8}, {2879, 30, -5, 8}// 151	152	153	
			, {2879, 29, -2, 8}, {2103, 32, -2, 8}, {1997, 31, -3, 7}// 154	167	171	
			, {3589, 30, -5, 17}, {1997, 31, -2, 7}, {1997, 30, -1, 7}// 187	194	198	
			, {6996, 29, -4, 14}, {6996, 31, -5, 14}, {1998, 30, -2, 7}// 200	201	202	
			, {2103, 32, -3, 8}, {1997, 32, -2, 7}, {1997, 32, -3, 7}// 204	208	214	
			, {1999, 32, -1, 7}, {1997, 31, -5, 7}, {1997, 31, -4, 7}// 216	218	222	
			, {737, 28, -6, 15}, {2103, 32, -1, 8}, {737, 32, -6, 15}// 226	228	229	
			, {1997, 30, -3, 7}, {1999, 29, -3, 7}, {1999, 30, -4, 7}// 234	235	236	
			, {1998, 29, -5, 7}, {1997, 29, -2, 7}, {1997, 29, -1, 7}// 237	238	239	
			, {1997, 29, -4, 7}, {1997, 30, -5, 7}, {1997, 32, -5, 7}// 240	241	250	
			, {1998, 32, -4, 7}, {10644, 14, 7, 0}, {10644, 2, 7, 0}// 252	254	255	
			, {3264, 12, 6, 0}, {3208, 11, 6, 0}, {3203, 10, 7, 0}// 262	263	264	
			, {3207, 8, 1, 0}, {3208, 4, 6, 0}, {3265, 7, 2, 0}// 265	266	267	
			, {2768, 3, 3, 0}, {2768, 2, 3, 0}, {2768, 1, 3, 0}// 353	354	355	
			, {2767, 4, 2, 0}, {2767, 4, 1, 0}, {2760, 1, 2, 0}// 356	357	358	
			, {2760, 2, 2, 0}, {2760, 3, 2, 0}, {2760, 3, 1, 0}// 359	360	361	
			, {2760, 2, 1, 0}, {2760, 1, 1, 0}, {2761, 4, 3, 0}// 362	363	364	
			, {2767, 4, 0, 0}, {2760, 3, 0, 0}, {2760, 2, 0, 0}// 365	366	367	
			, {2760, 1, 0, 0}, {3299, 11, 6, 0}, {3263, 15, -7, 0}// 368	373	399	
			, {3213, 10, -3, 0}, {3214, 11, -7, 0}, {3207, 10, -1, 0}// 400	401	402	
			, {3264, 10, -7, 0}, {3214, 10, -6, 0}, {3205, 8, -6, 0}// 403	404	405	
			, {3262, 2, -7, 0}, {3203, 8, -3, 0}, {3206, 8, -1, 0}// 406	407	408	
			, {3211, 9, -3, 0}, {3203, 1, -7, 0}, {2767, 4, -1, 0}// 409	410	428	
			, {2767, 4, -2, 0}, {2766, 3, -3, 0}, {2766, 2, -3, 0}// 429	430	431	
			, {2766, 1, -3, 0}, {2764, 4, -3, 0}, {2760, 3, -1, 0}// 432	433	434	
			, {2760, 3, -2, 0}, {2760, 2, -1, 0}, {2760, 2, -2, 0}// 435	436	437	
			, {2760, 1, -2, 0}, {2760, 1, -1, 0}, {10644, -1, 7, 0}// 448	449	469	
			, {10644, -11, 7, 0}, {3204, -3, 6, 0}, {3210, -8, 6, 0}// 474	475	476	
			, {3203, -7, 6, 0}, {3206, -6, 3, 0}, {3205, -6, 0, 0}// 477	478	479	
			, {3209, -4, 3, 0}, {3205, -8, 7, 0}, {10644, -14, 7, 0}// 480	481	482	
			, {2768, 0, 3, 0}, {2768, -1, 3, 0}, {2765, -2, 2, 0}// 489	490	491	
			, {2765, -2, 1, 0}, {2763, -2, 3, 0}, {2760, -1, 2, 0}// 492	493	494	
			, {2760, 0, 2, 0}, {2760, 0, 1, 0}, {2760, -1, 1, 0}// 495	496	497	
			, {2765, -2, 0, 0}, {2760, -1, 0, 0}, {2760, 0, 0, 0}// 498	603	605	
			, {3208, -6, -3, 0}, {3208, -8, -5, 0}, {3263, -13, -7, 0}// 626	627	628	
			, {2766, 0, -3, 0}, {2766, -1, -3, 0}, {2765, -2, -1, 0}// 632	633	634	
			, {2765, -2, -2, 0}, {2762, -2, -3, 0}, {2760, -1, -2, 0}// 635	636	648	
			, {2760, -1, -1, 0}, {2760, 0, -2, 0}, {3213, -14, -7, 0}// 649	650	651	
			, {2760, 0, -1, 0}, {10644, -24, 7, 0}, {10644, -27, 7, 0}// 652	675	676	
			, {3144, -17, 7, 0}, {3347, -21, 7, 0}, {3147, -17, 4, 0}// 677	753	754	
			, {3127, -19, 4, 0}, {3127, -29, 7, 0}, {3128, -31, 6, 0}// 755	756	757	
			, {3143, -19, 6, 0}, {3143, -31, 4, 0}, {3143, -31, 3, 0}// 758	759	760	
			, {3212, -30, 7, 0}, {3208, -19, 5, 0}, {3264, -31, 4, 0}// 761	762	763	
			, {3147, -31, 5, 0}, {3345, -31, -3, 0}, {3149, -19, -6, 0}// 764	832	833	
			, {3127, -31, -1, 0}, {3205, -19, -4, 0}, {3210, -19, -3, 0}// 834	835	836	
			, {3210, -19, -2, 0}, {3205, -19, -1, 0}, {3208, -31, -1, 0}// 837	838	839	
			, {10644, -32, 7, 0}, {10644, -32, -6, 0}// 884	885	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LunaTrainingCenter5_AddonDeed();
			}
		}

		[ Constructable ]
		public LunaTrainingCenter5_Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 6093, 27, 6, 0, 0, -1, "tiny flowers", 1);// 8
			AddComplexComponent( (BaseAddon) this, 6093, 28, 5, 0, 0, -1, "tiny flowers", 1);// 9
			AddComplexComponent( (BaseAddon) this, 6093, 21, 6, 0, 0, -1, "tiny flowers", 1);// 10
			AddComplexComponent( (BaseAddon) this, 6093, 23, 6, 0, 0, -1, "tiny flowers", 1);// 16
			AddComplexComponent( (BaseAddon) this, 4837, 31, 3, 12, 1174, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 742, 32, 1, 14, 1171, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1652, 30, 0, 31, 16, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 1651, 31, 0, 31, 16, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 5717, 32, 0, 0, 0, -1, "wheel", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1542, 17, 0, 51, 37, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 1536, 18, 0, 51, 37, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1536, 19, 0, 51, 37, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 1541, 20, 0, 51, 37, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1538, 21, 0, 48, 37, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1538, 22, 0, 45, 37, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1535, 17, 1, 51, 37, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1542, 18, 1, 54, 37, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1541, 19, 1, 54, 37, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1538, 20, 1, 51, 37, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 1538, 21, 1, 48, 37, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 1538, 22, 1, 45, 37, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1535, 17, 2, 51, 37, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1540, 19, 2, 54, 37, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1543, 18, 2, 54, 37, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 1538, 20, 2, 51, 37, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 1538, 21, 2, 48, 37, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 1538, 22, 2, 45, 37, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 1538, 22, 3, 45, 37, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 1538, 21, 3, 48, 37, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 1540, 20, 3, 51, 37, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 1537, 19, 3, 51, 37, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 1537, 18, 3, 51, 37, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 1543, 17, 3, 51, 37, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 1537, 17, 4, 48, 37, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 1537, 18, 4, 48, 37, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 1537, 19, 4, 48, 37, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 1537, 20, 4, 48, 37, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1540, 21, 4, 48, 37, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1538, 22, 4, 45, 37, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 1537, 17, 5, 45, 37, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 1537, 18, 5, 45, 37, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1537, 19, 5, 45, 37, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1537, 20, 5, 45, 37, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 889, 23, 3, 20, 1106, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 889, 23, 2, 20, 1106, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 889, 23, 1, 20, 1106, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 889, 23, 0, 20, 1106, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 888, 21, 6, 20, 1106, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 888, 20, 6, 20, 1106, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 888, 19, 6, 20, 1106, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 888, 18, 6, 20, 1106, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 888, 17, 6, 20, 1106, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 889, 23, 4, 20, 1106, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 2794, 18, 2, 0, 1106, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 2794, 17, 2, 0, 1106, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 2793, 19, 1, 0, 1106, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 2793, 19, 0, 0, 1106, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 2787, 19, 2, 0, 1106, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 2795, 18, 1, 0, 1106, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 2795, 18, 0, 0, 1106, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 2795, 17, 1, 0, 1106, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 2795, 17, 0, 0, 1106, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 5717, 32, 1, 0, 0, -1, "wheel", 1);// 83
			AddComplexComponent( (BaseAddon) this, 1638, 29, 2, 28, 16, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 743, 29, 2, 14, 1171, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 1638, 30, 1, 31, 16, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 1633, 32, 1, 28, 16, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 1633, 32, 0, 28, 16, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 742, 32, 0, 14, 1171, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 1635, 31, 1, 31, 16, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 1635, 32, 2, 28, 16, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 1630, 29, 1, 28, 16, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 742, 28, 1, 14, 1171, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 742, 28, 2, 14, 1171, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 1630, 29, 0, 28, 16, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 1632, 30, 2, 28, 16, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 1537, 21, 5, 45, 37, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 1540, 22, 5, 45, 37, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 497, 18, 3, 0, 1109, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 496, 20, 3, 0, 1109, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 498, 20, 2, 0, 1109, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 498, 20, 1, 0, 1109, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 497, 19, 3, 0, 1109, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 498, 20, 0, 0, 1109, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 1632, 31, 2, 28, 16, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 742, 32, 2, 14, 1171, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 742, 28, 0, 14, 1171, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 743, 32, 2, 14, 1171, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 6093, 24, -2, 0, 0, -1, "tiny flowers", 1);// 126
			AddComplexComponent( (BaseAddon) this, 6093, 25, -4, 0, 0, -1, "tiny flowers", 1);// 127
			AddComplexComponent( (BaseAddon) this, 6093, 25, -5, 0, 0, -1, "tiny flowers", 1);// 128
			AddComplexComponent( (BaseAddon) this, 6093, 24, -6, 0, 0, -1, "tiny flowers", 1);// 133
			AddComplexComponent( (BaseAddon) this, 743, 31, -6, 14, 1171, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 1652, 30, -1, 31, 16, -1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 1652, 30, -3, 31, 16, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 1652, 30, -2, 31, 16, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 1651, 31, -2, 31, 16, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 1651, 31, -3, 31, 16, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 1651, 31, -1, 31, 16, -1, "", 1);// 160
			AddComplexComponent( (BaseAddon) this, 742, 32, -2, 14, 1171, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 742, 28, -1, 14, 1171, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 742, 28, -3, 14, 1171, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 742, 28, -2, 14, 1171, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 1637, 29, -5, 28, 16, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 1636, 31, -4, 31, 16, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 1637, 30, -4, 31, 16, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 742, 32, -5, 13, 1171, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 742, 32, -4, 14, 1171, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 1536, 17, -2, 45, 37, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 1536, 18, -2, 45, 37, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 1536, 19, -2, 45, 37, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 1536, 20, -2, 45, 37, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 1536, 21, -2, 45, 37, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 1541, 22, -2, 45, 37, -1, "", 1);// 177
			AddComplexComponent( (BaseAddon) this, 1536, 17, -1, 48, 37, -1, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 1536, 18, -1, 48, 37, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 1536, 19, -1, 48, 37, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 1536, 20, -1, 48, 37, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 1541, 21, -1, 48, 37, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 1538, 22, -1, 45, 37, -1, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 889, 23, -3, 20, 1106, -1, "", 1);// 184
			AddComplexComponent( (BaseAddon) this, 889, 23, -2, 20, 1106, -1, "", 1);// 185
			AddComplexComponent( (BaseAddon) this, 889, 23, -1, 20, 1106, -1, "", 1);// 186
			AddComplexComponent( (BaseAddon) this, 2793, 19, -1, 0, 1106, -1, "", 1);// 188
			AddComplexComponent( (BaseAddon) this, 2793, 19, -2, 0, 1106, -1, "", 1);// 189
			AddComplexComponent( (BaseAddon) this, 2793, 19, -3, 0, 1106, -1, "", 1);// 190
			AddComplexComponent( (BaseAddon) this, 2792, 18, -4, 0, 1106, -1, "", 1);// 191
			AddComplexComponent( (BaseAddon) this, 2792, 17, -4, 0, 1106, -1, "", 1);// 192
			AddComplexComponent( (BaseAddon) this, 742, 28, -5, 14, 1171, -1, "", 1);// 193
			AddComplexComponent( (BaseAddon) this, 742, 32, -1, 14, 1171, -1, "", 1);// 195
			AddComplexComponent( (BaseAddon) this, 742, 28, -4, 14, 1171, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 743, 29, -6, 14, 1171, -1, "", 1);// 197
			AddComplexComponent( (BaseAddon) this, 1636, 32, -5, 28, 16, -1, "", 1);// 199
			AddComplexComponent( (BaseAddon) this, 1633, 32, -2, 28, 16, -1, "", 1);// 203
			AddComplexComponent( (BaseAddon) this, 1633, 32, -1, 28, 16, -1, "", 1);// 205
			AddComplexComponent( (BaseAddon) this, 743, 32, -6, 14, 1171, -1, "", 1);// 206
			AddComplexComponent( (BaseAddon) this, 1633, 32, -4, 28, 16, -1, "", 1);// 207
			AddComplexComponent( (BaseAddon) this, 2795, 17, -3, 0, 1106, -1, "", 1);// 209
			AddComplexComponent( (BaseAddon) this, 2795, 18, -2, 0, 1106, -1, "", 1);// 210
			AddComplexComponent( (BaseAddon) this, 2790, 19, -4, 0, 1106, -1, "", 1);// 211
			AddComplexComponent( (BaseAddon) this, 2795, 18, -1, 0, 1106, -1, "", 1);// 212
			AddComplexComponent( (BaseAddon) this, 2795, 17, -1, 0, 1106, -1, "", 1);// 213
			AddComplexComponent( (BaseAddon) this, 2795, 18, -3, 0, 1106, -1, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 1633, 32, -3, 28, 16, -1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 1630, 29, -3, 28, 16, -1, "", 1);// 219
			AddComplexComponent( (BaseAddon) this, 2795, 17, -2, 0, 1106, -1, "", 1);// 220
			AddComplexComponent( (BaseAddon) this, 743, 30, -6, 14, 1171, -1, "", 1);// 221
			AddComplexComponent( (BaseAddon) this, 1630, 29, -4, 28, 16, -1, "", 1);// 223
			AddComplexComponent( (BaseAddon) this, 1630, 29, -1, 28, 16, -1, "", 1);// 224
			AddComplexComponent( (BaseAddon) this, 1630, 29, -2, 28, 16, -1, "", 1);// 225
			AddComplexComponent( (BaseAddon) this, 1631, 31, -5, 28, 16, -1, "", 1);// 227
			AddComplexComponent( (BaseAddon) this, 742, 32, -3, 14, 1171, -1, "", 1);// 230
			AddComplexComponent( (BaseAddon) this, 5717, 32, -3, 0, 0, -1, "wheel", 1);// 231
			AddComplexComponent( (BaseAddon) this, 1631, 30, -5, 28, 16, -1, "", 1);// 232
			AddComplexComponent( (BaseAddon) this, 6093, 23, -2, 0, 0, -1, "tiny flowers", 1);// 233
			AddComplexComponent( (BaseAddon) this, 502, 17, -5, 0, 1109, -1, "", 1);// 242
			AddComplexComponent( (BaseAddon) this, 502, 18, -5, 0, 1109, -1, "", 1);// 243
			AddComplexComponent( (BaseAddon) this, 502, 19, -5, 0, 1109, -1, "", 1);// 244
			AddComplexComponent( (BaseAddon) this, 498, 20, -4, 0, 1109, -1, "", 1);// 245
			AddComplexComponent( (BaseAddon) this, 498, 20, -3, 0, 1109, -1, "", 1);// 246
			AddComplexComponent( (BaseAddon) this, 739, 20, -5, 0, 1109, -1, "", 1);// 247
			AddComplexComponent( (BaseAddon) this, 498, 20, -2, 0, 1109, -1, "", 1);// 248
			AddComplexComponent( (BaseAddon) this, 498, 20, -1, 0, 1109, -1, "", 1);// 249
			AddComplexComponent( (BaseAddon) this, 6093, 23, -1, 0, 0, -1, "tiny flowers", 1);// 251
			AddComplexComponent( (BaseAddon) this, 5717, 32, -4, 0, 0, -1, "wheel", 1);// 253
			AddComplexComponent( (BaseAddon) this, 6093, 4, 6, 0, 0, -1, "tiny flowers", 1);// 256
			AddComplexComponent( (BaseAddon) this, 6093, 10, 7, 0, 0, -1, "tiny flowers", 1);// 257
			AddComplexComponent( (BaseAddon) this, 6093, 10, 7, 10, 0, -1, "tiny flowers", 1);// 258
			AddComplexComponent( (BaseAddon) this, 6093, 9, 5, 22, 0, -1, "tiny flowers", 1);// 259
			AddComplexComponent( (BaseAddon) this, 6093, 8, 1, 0, 0, -1, "tiny flowers", 1);// 260
			AddComplexComponent( (BaseAddon) this, 6093, 12, 6, 0, 0, -1, "tiny flowers", 1);// 261
			AddComplexComponent( (BaseAddon) this, 41188, 11, 7, 34, 1153, -1, "", 1);// 268
			AddComplexComponent( (BaseAddon) this, 1535, 16, 0, 48, 37, -1, "", 1);// 269
			AddComplexComponent( (BaseAddon) this, 1535, 15, 1, 45, 37, -1, "", 1);// 270
			AddComplexComponent( (BaseAddon) this, 1535, 16, 1, 48, 37, -1, "", 1);// 271
			AddComplexComponent( (BaseAddon) this, 1535, 15, 2, 45, 37, -1, "", 1);// 272
			AddComplexComponent( (BaseAddon) this, 1535, 16, 2, 48, 37, -1, "", 1);// 273
			AddComplexComponent( (BaseAddon) this, 1535, 16, 3, 48, 37, -1, "", 1);// 274
			AddComplexComponent( (BaseAddon) this, 1535, 15, 3, 45, 37, -1, "", 1);// 275
			AddComplexComponent( (BaseAddon) this, 1535, 15, 4, 45, 37, -1, "", 1);// 276
			AddComplexComponent( (BaseAddon) this, 1543, 16, 4, 48, 37, -1, "", 1);// 277
			AddComplexComponent( (BaseAddon) this, 1543, 15, 5, 45, 37, -1, "", 1);// 278
			AddComplexComponent( (BaseAddon) this, 1537, 16, 5, 45, 37, -1, "", 1);// 279
			AddComplexComponent( (BaseAddon) this, 888, 16, 6, 20, 1106, -1, "", 1);// 280
			AddComplexComponent( (BaseAddon) this, 41188, 12, 6, 33, 1153, -1, "", 1);// 281
			AddComplexComponent( (BaseAddon) this, 2794, 16, 2, 0, 1106, -1, "", 1);// 282
			AddComplexComponent( (BaseAddon) this, 2794, 15, 2, 0, 1106, -1, "", 1);// 283
			AddComplexComponent( (BaseAddon) this, 2794, 14, 2, 0, 1106, -1, "", 1);// 284
			AddComplexComponent( (BaseAddon) this, 2791, 13, 1, 0, 1106, -1, "", 1);// 285
			AddComplexComponent( (BaseAddon) this, 2791, 13, 0, 0, 1106, -1, "", 1);// 286
			AddComplexComponent( (BaseAddon) this, 2789, 13, 2, 0, 1106, -1, "", 1);// 287
			AddComplexComponent( (BaseAddon) this, 2795, 16, 1, 0, 1106, -1, "", 1);// 288
			AddComplexComponent( (BaseAddon) this, 2795, 16, 0, 0, 1106, -1, "", 1);// 289
			AddComplexComponent( (BaseAddon) this, 2795, 15, 1, 0, 1106, -1, "", 1);// 290
			AddComplexComponent( (BaseAddon) this, 2795, 15, 0, 0, 1106, -1, "", 1);// 291
			AddComplexComponent( (BaseAddon) this, 2795, 14, 1, 0, 1106, -1, "", 1);// 292
			AddComplexComponent( (BaseAddon) this, 2795, 14, 0, 0, 1106, -1, "", 1);// 293
			AddComplexComponent( (BaseAddon) this, 1542, 1, 0, 47, 1320, -1, "", 1);// 294
			AddComplexComponent( (BaseAddon) this, 1536, 2, 0, 47, 1320, -1, "", 1);// 295
			AddComplexComponent( (BaseAddon) this, 1536, 3, 0, 47, 1320, -1, "", 1);// 296
			AddComplexComponent( (BaseAddon) this, 1536, 4, 0, 47, 1320, -1, "", 1);// 297
			AddComplexComponent( (BaseAddon) this, 1536, 5, 0, 47, 1320, -1, "", 1);// 298
			AddComplexComponent( (BaseAddon) this, 1541, 6, 0, 47, 1320, -1, "", 1);// 299
			AddComplexComponent( (BaseAddon) this, 1538, 7, 0, 44, 1320, -1, "", 1);// 300
			AddComplexComponent( (BaseAddon) this, 1535, 1, 1, 47, 1320, -1, "", 1);// 301
			AddComplexComponent( (BaseAddon) this, 1542, 2, 1, 50, 1320, -1, "", 1);// 302
			AddComplexComponent( (BaseAddon) this, 1536, 3, 1, 50, 1320, -1, "", 1);// 303
			AddComplexComponent( (BaseAddon) this, 1536, 4, 1, 50, 1320, -1, "", 1);// 304
			AddComplexComponent( (BaseAddon) this, 1541, 5, 1, 50, 1320, -1, "", 1);// 305
			AddComplexComponent( (BaseAddon) this, 1538, 6, 1, 47, 1320, -1, "", 1);// 306
			AddComplexComponent( (BaseAddon) this, 1538, 7, 1, 44, 1320, -1, "", 1);// 307
			AddComplexComponent( (BaseAddon) this, 1535, 1, 2, 47, 1320, -1, "", 1);// 308
			AddComplexComponent( (BaseAddon) this, 1535, 2, 2, 50, 1320, -1, "", 1);// 309
			AddComplexComponent( (BaseAddon) this, 1542, 3, 2, 53, 1320, -1, "", 1);// 310
			AddComplexComponent( (BaseAddon) this, 1541, 4, 2, 53, 1320, -1, "", 1);// 311
			AddComplexComponent( (BaseAddon) this, 1538, 5, 2, 50, 1320, -1, "", 1);// 312
			AddComplexComponent( (BaseAddon) this, 1538, 6, 2, 47, 1320, -1, "", 1);// 313
			AddComplexComponent( (BaseAddon) this, 1538, 7, 2, 44, 1320, -1, "", 1);// 314
			AddComplexComponent( (BaseAddon) this, 1535, 1, 3, 47, 1320, -1, "", 1);// 315
			AddComplexComponent( (BaseAddon) this, 1535, 2, 3, 50, 1320, -1, "", 1);// 316
			AddComplexComponent( (BaseAddon) this, 1540, 4, 3, 53, 1320, -1, "", 1);// 317
			AddComplexComponent( (BaseAddon) this, 1543, 3, 3, 53, 1320, -1, "", 1);// 318
			AddComplexComponent( (BaseAddon) this, 1538, 5, 3, 50, 1320, -1, "", 1);// 319
			AddComplexComponent( (BaseAddon) this, 1538, 6, 3, 47, 1320, -1, "", 1);// 320
			AddComplexComponent( (BaseAddon) this, 1538, 7, 3, 44, 1320, -1, "", 1);// 321
			AddComplexComponent( (BaseAddon) this, 1538, 7, 4, 44, 1320, -1, "", 1);// 322
			AddComplexComponent( (BaseAddon) this, 1538, 6, 4, 47, 1320, -1, "", 1);// 323
			AddComplexComponent( (BaseAddon) this, 1540, 5, 4, 50, 1320, -1, "", 1);// 324
			AddComplexComponent( (BaseAddon) this, 1537, 4, 4, 50, 1320, -1, "", 1);// 325
			AddComplexComponent( (BaseAddon) this, 1537, 3, 4, 50, 1320, -1, "", 1);// 326
			AddComplexComponent( (BaseAddon) this, 1543, 2, 4, 50, 1320, -1, "", 1);// 327
			AddComplexComponent( (BaseAddon) this, 1535, 1, 4, 47, 1320, -1, "", 1);// 328
			AddComplexComponent( (BaseAddon) this, 1537, 2, 5, 47, 1320, -1, "", 1);// 329
			AddComplexComponent( (BaseAddon) this, 1543, 1, 5, 47, 1320, -1, "", 1);// 330
			AddComplexComponent( (BaseAddon) this, 1537, 3, 5, 47, 1320, -1, "", 1);// 331
			AddComplexComponent( (BaseAddon) this, 1537, 4, 5, 47, 1320, -1, "", 1);// 332
			AddComplexComponent( (BaseAddon) this, 1537, 5, 5, 47, 1320, -1, "", 1);// 333
			AddComplexComponent( (BaseAddon) this, 1540, 6, 5, 47, 1320, -1, "", 1);// 334
			AddComplexComponent( (BaseAddon) this, 1538, 7, 5, 44, 1320, -1, "", 1);// 335
			AddComplexComponent( (BaseAddon) this, 1537, 1, 6, 44, 1320, -1, "", 1);// 336
			AddComplexComponent( (BaseAddon) this, 1537, 2, 6, 44, 1320, -1, "", 1);// 337
			AddComplexComponent( (BaseAddon) this, 1537, 3, 6, 44, 1320, -1, "", 1);// 338
			AddComplexComponent( (BaseAddon) this, 1537, 4, 6, 44, 1320, -1, "", 1);// 339
			AddComplexComponent( (BaseAddon) this, 1537, 5, 6, 44, 1320, -1, "", 1);// 340
			AddComplexComponent( (BaseAddon) this, 1537, 6, 6, 44, 1320, -1, "", 1);// 341
			AddComplexComponent( (BaseAddon) this, 889, 8, 4, 20, 1320, -1, "", 1);// 342
			AddComplexComponent( (BaseAddon) this, 889, 8, 3, 20, 1320, -1, "", 1);// 343
			AddComplexComponent( (BaseAddon) this, 889, 8, 2, 20, 1320, -1, "", 1);// 344
			AddComplexComponent( (BaseAddon) this, 889, 8, 1, 20, 1320, -1, "", 1);// 345
			AddComplexComponent( (BaseAddon) this, 888, 6, 7, 20, 1320, -1, "", 1);// 346
			AddComplexComponent( (BaseAddon) this, 888, 5, 7, 20, 1320, -1, "", 1);// 347
			AddComplexComponent( (BaseAddon) this, 888, 4, 7, 20, 1320, -1, "", 1);// 348
			AddComplexComponent( (BaseAddon) this, 888, 3, 7, 20, 1320, -1, "", 1);// 349
			AddComplexComponent( (BaseAddon) this, 888, 2, 7, 20, 1320, -1, "", 1);// 350
			AddComplexComponent( (BaseAddon) this, 889, 8, 5, 20, 1320, -1, "", 1);// 351
			AddComplexComponent( (BaseAddon) this, 889, 8, 0, 20, 1320, -1, "", 1);// 352
			AddComplexComponent( (BaseAddon) this, 888, 14, 6, 20, 1106, -1, "", 1);// 369
			AddComplexComponent( (BaseAddon) this, 888, 1, 7, 20, 1320, -1, "", 1);// 370
			AddComplexComponent( (BaseAddon) this, 1540, 7, 6, 44, 1320, -1, "", 1);// 371
			AddComplexComponent( (BaseAddon) this, 41188, 10, 7, 10, 1153, -1, "", 1);// 372
			AddComplexComponent( (BaseAddon) this, 41188, 12, 6, 16, 1153, -1, "", 1);// 374
			AddComplexComponent( (BaseAddon) this, 41188, 11, 7, 27, 1153, -1, "", 1);// 375
			AddComplexComponent( (BaseAddon) this, 41188, 12, 5, 22, 1153, -1, "", 1);// 376
			AddComplexComponent( (BaseAddon) this, 41188, 12, 7, 30, 1153, -1, "", 1);// 377
			AddComplexComponent( (BaseAddon) this, 888, 15, 6, 20, 1106, -1, "", 1);// 378
			AddComplexComponent( (BaseAddon) this, 500, 12, 3, 0, 1109, -1, "", 1);// 379
			AddComplexComponent( (BaseAddon) this, 503, 12, 1, 0, 1109, -1, "", 1);// 380
			AddComplexComponent( (BaseAddon) this, 503, 12, 2, 0, 1109, -1, "", 1);// 381
			AddComplexComponent( (BaseAddon) this, 503, 12, 0, 0, 1109, -1, "", 1);// 382
			AddComplexComponent( (BaseAddon) this, 497, 13, 3, 0, 1109, -1, "", 1);// 383
			AddComplexComponent( (BaseAddon) this, 497, 14, 3, 0, 1109, -1, "", 1);// 384
			AddComplexComponent( (BaseAddon) this, 497, 3, 4, 0, 1320, -1, "", 1);// 385
			AddComplexComponent( (BaseAddon) this, 496, 5, 4, 0, 1320, -1, "", 1);// 386
			AddComplexComponent( (BaseAddon) this, 498, 5, 3, 0, 1320, -1, "", 1);// 387
			AddComplexComponent( (BaseAddon) this, 498, 5, 2, 0, 1320, -1, "", 1);// 388
			AddComplexComponent( (BaseAddon) this, 497, 4, 4, 0, 1320, -1, "", 1);// 389
			AddComplexComponent( (BaseAddon) this, 498, 5, 0, 0, 1320, -1, "", 1);// 390
			AddComplexComponent( (BaseAddon) this, 498, 5, 1, 0, 1320, -1, "", 1);// 391
			AddComplexComponent( (BaseAddon) this, 6093, 10, -3, 0, 0, -1, "tiny flowers", 1);// 392
			AddComplexComponent( (BaseAddon) this, 6093, 10, -1, 0, 0, -1, "tiny flowers", 1);// 393
			AddComplexComponent( (BaseAddon) this, 6093, 8, -1, 0, 0, -1, "tiny flowers", 1);// 394
			AddComplexComponent( (BaseAddon) this, 6093, 11, -7, 0, 0, -1, "tiny flowers", 1);// 395
			AddComplexComponent( (BaseAddon) this, 6093, 2, -7, 0, 0, -1, "tiny flowers", 1);// 396
			AddComplexComponent( (BaseAddon) this, 6093, 9, -3, 0, 0, -1, "tiny flowers", 1);// 397
			AddComplexComponent( (BaseAddon) this, 6093, 10, -6, 0, 0, -1, "tiny flowers", 1);// 398
			AddComplexComponent( (BaseAddon) this, 1542, 13, -4, 23, 37, -1, "", 1);// 411
			AddComplexComponent( (BaseAddon) this, 1536, 14, -4, 23, 37, -1, "", 1);// 412
			AddComplexComponent( (BaseAddon) this, 1535, 15, -1, 45, 37, -1, "", 1);// 413
			AddComplexComponent( (BaseAddon) this, 1542, 16, -1, 48, 37, -1, "", 1);// 414
			AddComplexComponent( (BaseAddon) this, 1535, 13, -2, 23, 37, -1, "", 1);// 415
			AddComplexComponent( (BaseAddon) this, 2792, 15, -4, 0, 1106, -1, "", 1);// 416
			AddComplexComponent( (BaseAddon) this, 2792, 16, -4, 0, 1106, -1, "", 1);// 417
			AddComplexComponent( (BaseAddon) this, 2795, 14, -3, 0, 1106, -1, "", 1);// 418
			AddComplexComponent( (BaseAddon) this, 2795, 14, -2, 0, 1106, -1, "", 1);// 419
			AddComplexComponent( (BaseAddon) this, 2792, 14, -4, 0, 1106, -1, "", 1);// 420
			AddComplexComponent( (BaseAddon) this, 1536, 2, -1, 44, 1320, -1, "", 1);// 421
			AddComplexComponent( (BaseAddon) this, 1536, 3, -1, 44, 1320, -1, "", 1);// 422
			AddComplexComponent( (BaseAddon) this, 1536, 4, -1, 44, 1320, -1, "", 1);// 423
			AddComplexComponent( (BaseAddon) this, 1536, 5, -1, 44, 1320, -1, "", 1);// 424
			AddComplexComponent( (BaseAddon) this, 1536, 6, -1, 44, 1320, -1, "", 1);// 425
			AddComplexComponent( (BaseAddon) this, 1541, 7, -1, 44, 1320, -1, "", 1);// 426
			AddComplexComponent( (BaseAddon) this, 889, 8, -2, 20, 1320, -1, "", 1);// 427
			AddComplexComponent( (BaseAddon) this, 2795, 16, -2, 0, 1106, -1, "", 1);// 438
			AddComplexComponent( (BaseAddon) this, 2795, 16, -1, 0, 1106, -1, "", 1);// 439
			AddComplexComponent( (BaseAddon) this, 2788, 13, -4, 0, 1106, -1, "", 1);// 440
			AddComplexComponent( (BaseAddon) this, 2791, 13, -1, 0, 1106, -1, "", 1);// 441
			AddComplexComponent( (BaseAddon) this, 2791, 13, -3, 0, 1106, -1, "", 1);// 442
			AddComplexComponent( (BaseAddon) this, 2791, 13, -2, 0, 1106, -1, "", 1);// 443
			AddComplexComponent( (BaseAddon) this, 2795, 15, -2, 0, 1106, -1, "", 1);// 444
			AddComplexComponent( (BaseAddon) this, 2795, 15, -3, 0, 1106, -1, "", 1);// 445
			AddComplexComponent( (BaseAddon) this, 2795, 15, -1, 0, 1106, -1, "", 1);// 446
			AddComplexComponent( (BaseAddon) this, 889, 8, -1, 20, 1320, -1, "", 1);// 447
			AddComplexComponent( (BaseAddon) this, 2795, 14, -1, 0, 1106, -1, "", 1);// 450
			AddComplexComponent( (BaseAddon) this, 2795, 16, -3, 0, 1106, -1, "", 1);// 451
			AddComplexComponent( (BaseAddon) this, 6093, 15, -7, 0, 0, -1, "tiny flowers", 1);// 452
			AddComplexComponent( (BaseAddon) this, 503, 12, -1, 0, 1109, -1, "", 1);// 453
			AddComplexComponent( (BaseAddon) this, 503, 12, -3, 0, 1109, -1, "", 1);// 454
			AddComplexComponent( (BaseAddon) this, 503, 12, -2, 0, 1109, -1, "", 1);// 455
			AddComplexComponent( (BaseAddon) this, 502, 13, -5, 0, 1109, -1, "", 1);// 456
			AddComplexComponent( (BaseAddon) this, 502, 14, -5, 0, 1109, -1, "", 1);// 457
			AddComplexComponent( (BaseAddon) this, 502, 16, -5, 0, 1109, -1, "", 1);// 458
			AddComplexComponent( (BaseAddon) this, 502, 15, -5, 0, 1109, -1, "", 1);// 459
			AddComplexComponent( (BaseAddon) this, 503, 12, -4, 0, 1109, -1, "", 1);// 460
			AddComplexComponent( (BaseAddon) this, 502, 1, -4, 0, 1320, -1, "", 1);// 461
			AddComplexComponent( (BaseAddon) this, 502, 2, -4, 0, 1320, -1, "", 1);// 462
			AddComplexComponent( (BaseAddon) this, 502, 3, -4, 0, 1320, -1, "", 1);// 463
			AddComplexComponent( (BaseAddon) this, 502, 4, -4, 0, 1320, -1, "", 1);// 464
			AddComplexComponent( (BaseAddon) this, 498, 5, -3, 0, 1320, -1, "", 1);// 465
			AddComplexComponent( (BaseAddon) this, 498, 5, -2, 0, 1320, -1, "", 1);// 466
			AddComplexComponent( (BaseAddon) this, 739, 5, -4, 0, 1320, -1, "", 1);// 467
			AddComplexComponent( (BaseAddon) this, 498, 5, -1, 0, 1320, -1, "", 1);// 468
			AddComplexComponent( (BaseAddon) this, 6093, -3, 6, 0, 0, -1, "tiny flowers", 1);// 470
			AddComplexComponent( (BaseAddon) this, 6093, -7, 6, 0, 0, -1, "tiny flowers", 1);// 471
			AddComplexComponent( (BaseAddon) this, 6093, -6, 6, 0, 0, -1, "tiny flowers", 1);// 472
			AddComplexComponent( (BaseAddon) this, 6093, -6, 2, 0, 0, -1, "tiny flowers", 1);// 473
			AddComplexComponent( (BaseAddon) this, 1535, 0, 0, 44, 1320, -1, "", 1);// 483
			AddComplexComponent( (BaseAddon) this, 1535, 0, 2, 44, 1320, -1, "", 1);// 484
			AddComplexComponent( (BaseAddon) this, 1535, 0, 3, 44, 1320, -1, "", 1);// 485
			AddComplexComponent( (BaseAddon) this, 1535, 0, 4, 44, 1320, -1, "", 1);// 486
			AddComplexComponent( (BaseAddon) this, 1535, 0, 5, 44, 1320, -1, "", 1);// 487
			AddComplexComponent( (BaseAddon) this, 1543, 0, 6, 44, 1320, -1, "", 1);// 488
			AddComplexComponent( (BaseAddon) this, 888, 0, 7, 20, 1320, -1, "", 1);// 499
			AddComplexComponent( (BaseAddon) this, 1536, -11, 0, 45, 1931, -1, "", 1);// 500
			AddComplexComponent( (BaseAddon) this, 1536, -10, 0, 45, 1931, -1, "", 1);// 501
			AddComplexComponent( (BaseAddon) this, 1536, -9, 0, 45, 1931, -1, "", 1);// 502
			AddComplexComponent( (BaseAddon) this, 1536, -8, 0, 45, 1931, -1, "", 1);// 503
			AddComplexComponent( (BaseAddon) this, 1536, -7, 0, 45, 1931, -1, "", 1);// 504
			AddComplexComponent( (BaseAddon) this, 1541, -6, 0, 45, 1931, -1, "", 1);// 505
			AddComplexComponent( (BaseAddon) this, 1535, -13, 1, 45, 1931, -1, "", 1);// 506
			AddComplexComponent( (BaseAddon) this, 1542, -12, 1, 48, 1931, -1, "", 1);// 507
			AddComplexComponent( (BaseAddon) this, 1536, -11, 1, 48, 1931, -1, "", 1);// 508
			AddComplexComponent( (BaseAddon) this, 1536, -10, 1, 48, 1931, -1, "", 1);// 509
			AddComplexComponent( (BaseAddon) this, 1536, -9, 1, 48, 1931, -1, "", 1);// 510
			AddComplexComponent( (BaseAddon) this, 1536, -8, 1, 48, 1931, -1, "", 1);// 511
			AddComplexComponent( (BaseAddon) this, 1541, -7, 1, 48, 1931, -1, "", 1);// 512
			AddComplexComponent( (BaseAddon) this, 1538, -6, 1, 45, 1931, -1, "", 1);// 513
			AddComplexComponent( (BaseAddon) this, 1535, -15, 0, 23, 1931, -1, "", 1);// 514
			AddComplexComponent( (BaseAddon) this, 1535, -12, 2, 48, 1931, -1, "", 1);// 515
			AddComplexComponent( (BaseAddon) this, 1542, -11, 2, 51, 1931, -1, "", 1);// 516
			AddComplexComponent( (BaseAddon) this, 1536, -10, 2, 51, 1931, -1, "", 1);// 517
			AddComplexComponent( (BaseAddon) this, 1536, -9, 2, 51, 1931, -1, "", 1);// 518
			AddComplexComponent( (BaseAddon) this, 1541, -8, 2, 51, 1931, -1, "", 1);// 519
			AddComplexComponent( (BaseAddon) this, 1538, -7, 2, 48, 1931, -1, "", 1);// 520
			AddComplexComponent( (BaseAddon) this, 1538, -6, 2, 45, 1931, -1, "", 1);// 521
			AddComplexComponent( (BaseAddon) this, 1535, -13, 3, 45, 1931, -1, "", 1);// 522
			AddComplexComponent( (BaseAddon) this, 1535, -12, 3, 48, 1931, -1, "", 1);// 523
			AddComplexComponent( (BaseAddon) this, 1535, -11, 3, 51, 1931, -1, "", 1);// 524
			AddComplexComponent( (BaseAddon) this, 1542, -10, 3, 54, 1931, -1, "", 1);// 525
			AddComplexComponent( (BaseAddon) this, 1541, -9, 3, 54, 1931, -1, "", 1);// 526
			AddComplexComponent( (BaseAddon) this, 1538, -8, 3, 51, 1931, -1, "", 1);// 527
			AddComplexComponent( (BaseAddon) this, 1538, -7, 3, 48, 1931, -1, "", 1);// 528
			AddComplexComponent( (BaseAddon) this, 1538, -6, 3, 45, 1931, -1, "", 1);// 529
			AddComplexComponent( (BaseAddon) this, 1535, -13, 4, 45, 1931, -1, "", 1);// 530
			AddComplexComponent( (BaseAddon) this, 1535, -12, 4, 48, 1931, -1, "", 1);// 531
			AddComplexComponent( (BaseAddon) this, 1535, -11, 4, 51, 1931, -1, "", 1);// 532
			AddComplexComponent( (BaseAddon) this, 1540, -9, 4, 54, 1931, -1, "", 1);// 533
			AddComplexComponent( (BaseAddon) this, 1543, -10, 4, 54, 1931, -1, "", 1);// 534
			AddComplexComponent( (BaseAddon) this, 1538, -8, 4, 51, 1931, -1, "", 1);// 535
			AddComplexComponent( (BaseAddon) this, 1538, -7, 4, 48, 1931, -1, "", 1);// 536
			AddComplexComponent( (BaseAddon) this, 1538, -6, 4, 45, 1931, -1, "", 1);// 537
			AddComplexComponent( (BaseAddon) this, 1538, -6, 5, 45, 1931, -1, "", 1);// 538
			AddComplexComponent( (BaseAddon) this, 1538, -7, 5, 48, 1931, -1, "", 1);// 539
			AddComplexComponent( (BaseAddon) this, 1540, -8, 5, 51, 1931, -1, "", 1);// 540
			AddComplexComponent( (BaseAddon) this, 1537, -9, 5, 51, 1931, -1, "", 1);// 541
			AddComplexComponent( (BaseAddon) this, 1537, -10, 5, 51, 1931, -1, "", 1);// 542
			AddComplexComponent( (BaseAddon) this, 1543, -11, 5, 51, 1931, -1, "", 1);// 543
			AddComplexComponent( (BaseAddon) this, 1535, -12, 5, 48, 1931, -1, "", 1);// 544
			AddComplexComponent( (BaseAddon) this, 1535, -13, 5, 45, 1931, -1, "", 1);// 545
			AddComplexComponent( (BaseAddon) this, 1535, -13, 6, 45, 1931, -1, "", 1);// 546
			AddComplexComponent( (BaseAddon) this, 1537, -11, 6, 48, 1931, -1, "", 1);// 547
			AddComplexComponent( (BaseAddon) this, 1543, -12, 6, 48, 1931, -1, "", 1);// 548
			AddComplexComponent( (BaseAddon) this, 1537, -10, 6, 48, 1931, -1, "", 1);// 549
			AddComplexComponent( (BaseAddon) this, 1537, -9, 6, 48, 1931, -1, "", 1);// 550
			AddComplexComponent( (BaseAddon) this, 1537, -8, 6, 48, 1931, -1, "", 1);// 551
			AddComplexComponent( (BaseAddon) this, 1540, -7, 6, 48, 1931, -1, "", 1);// 552
			AddComplexComponent( (BaseAddon) this, 1538, -6, 6, 45, 1931, -1, "", 1);// 553
			AddComplexComponent( (BaseAddon) this, 1543, -13, 7, 45, 1931, -1, "", 1);// 554
			AddComplexComponent( (BaseAddon) this, 1537, -12, 7, 45, 1931, -1, "", 1);// 555
			AddComplexComponent( (BaseAddon) this, 1537, -11, 7, 45, 1931, -1, "", 1);// 556
			AddComplexComponent( (BaseAddon) this, 1537, -10, 7, 45, 1931, -1, "", 1);// 557
			AddComplexComponent( (BaseAddon) this, 1537, -9, 7, 45, 1931, -1, "", 1);// 558
			AddComplexComponent( (BaseAddon) this, 1537, -8, 7, 45, 1931, -1, "", 1);// 559
			AddComplexComponent( (BaseAddon) this, 1537, -7, 7, 45, 1931, -1, "", 1);// 560
			AddComplexComponent( (BaseAddon) this, 1540, -6, 7, 45, 1931, -1, "", 1);// 561
			AddComplexComponent( (BaseAddon) this, 889, -5, 5, 20, 2721, -1, "", 1);// 562
			AddComplexComponent( (BaseAddon) this, 889, -5, 4, 20, 2721, -1, "", 1);// 563
			AddComplexComponent( (BaseAddon) this, 889, -5, 3, 20, 2721, -1, "", 1);// 564
			AddComplexComponent( (BaseAddon) this, 889, -5, 2, 20, 2721, -1, "", 1);// 565
			AddComplexComponent( (BaseAddon) this, 889, -5, 6, 20, 2721, -1, "", 1);// 566
			AddComplexComponent( (BaseAddon) this, 889, -5, 0, 20, 2721, -1, "", 1);// 567
			AddComplexComponent( (BaseAddon) this, 889, -5, 1, 20, 2721, -1, "", 1);// 568
			AddComplexComponent( (BaseAddon) this, 2810, -10, 3, 0, 2721, -1, "", 1);// 569
			AddComplexComponent( (BaseAddon) this, 2810, -13, 3, 0, 2721, -1, "", 1);// 570
			AddComplexComponent( (BaseAddon) this, 2756, -15, 4, 0, 2721, -1, "", 1);// 571
			AddComplexComponent( (BaseAddon) this, 2810, -12, 3, 0, 2721, -1, "", 1);// 572
			AddComplexComponent( (BaseAddon) this, 2809, -10, 4, 0, 2721, -1, "", 1);// 573
			AddComplexComponent( (BaseAddon) this, 2809, -11, 4, 0, 2721, -1, "", 1);// 574
			AddComplexComponent( (BaseAddon) this, 2806, -15, 3, 0, 2721, -1, "", 1);// 575
			AddComplexComponent( (BaseAddon) this, 2809, -12, 4, 0, 2721, -1, "", 1);// 576
			AddComplexComponent( (BaseAddon) this, 2809, -14, 4, 0, 2721, -1, "", 1);// 577
			AddComplexComponent( (BaseAddon) this, 2809, -13, 4, 0, 2721, -1, "", 1);// 578
			AddComplexComponent( (BaseAddon) this, 2810, -11, 3, 0, 2721, -1, "", 1);// 579
			AddComplexComponent( (BaseAddon) this, 2810, -14, 3, 0, 2721, -1, "", 1);// 580
			AddComplexComponent( (BaseAddon) this, 2754, -9, 4, 0, 2721, -1, "", 1);// 581
			AddComplexComponent( (BaseAddon) this, 2808, -9, 3, 0, 2721, -1, "", 1);// 582
			AddComplexComponent( (BaseAddon) this, 2810, -10, 0, 0, 2721, -1, "", 1);// 583
			AddComplexComponent( (BaseAddon) this, 2810, -12, 1, 0, 2721, -1, "", 1);// 584
			AddComplexComponent( (BaseAddon) this, 2810, -11, 2, 0, 2721, -1, "", 1);// 585
			AddComplexComponent( (BaseAddon) this, 2806, -15, 0, 0, 2721, -1, "", 1);// 586
			AddComplexComponent( (BaseAddon) this, 2810, -12, 2, 0, 2721, -1, "", 1);// 587
			AddComplexComponent( (BaseAddon) this, 2810, -11, 0, 0, 2721, -1, "", 1);// 588
			AddComplexComponent( (BaseAddon) this, 2810, -13, 1, 0, 2721, -1, "", 1);// 589
			AddComplexComponent( (BaseAddon) this, 2810, -11, 1, 0, 2721, -1, "", 1);// 590
			AddComplexComponent( (BaseAddon) this, 2810, -14, 2, 0, 2721, -1, "", 1);// 591
			AddComplexComponent( (BaseAddon) this, 2806, -15, 1, 0, 2721, -1, "", 1);// 592
			AddComplexComponent( (BaseAddon) this, 2810, -13, 2, 0, 2721, -1, "", 1);// 593
			AddComplexComponent( (BaseAddon) this, 2810, -10, 2, 0, 2721, -1, "", 1);// 594
			AddComplexComponent( (BaseAddon) this, 2808, -9, 1, 0, 2721, -1, "", 1);// 595
			AddComplexComponent( (BaseAddon) this, 2810, -14, 0, 0, 2721, -1, "", 1);// 596
			AddComplexComponent( (BaseAddon) this, 2810, -10, 1, 0, 2721, -1, "", 1);// 597
			AddComplexComponent( (BaseAddon) this, 2808, -9, 0, 0, 2721, -1, "", 1);// 598
			AddComplexComponent( (BaseAddon) this, 2810, -12, 0, 0, 2721, -1, "", 1);// 599
			AddComplexComponent( (BaseAddon) this, 2810, -14, 1, 0, 2721, -1, "", 1);// 600
			AddComplexComponent( (BaseAddon) this, 2810, -13, 0, 0, 2721, -1, "", 1);// 601
			AddComplexComponent( (BaseAddon) this, 2806, -15, 2, 0, 2721, -1, "", 1);// 602
			AddComplexComponent( (BaseAddon) this, 888, -1, 7, 20, 1320, -1, "", 1);// 604
			AddComplexComponent( (BaseAddon) this, 500, -3, 4, 0, 1320, -1, "", 1);// 606
			AddComplexComponent( (BaseAddon) this, 503, -3, 2, 0, 1320, -1, "", 1);// 607
			AddComplexComponent( (BaseAddon) this, 503, -3, 3, 0, 1320, -1, "", 1);// 608
			AddComplexComponent( (BaseAddon) this, 503, -3, 0, 0, 1320, -1, "", 1);// 609
			AddComplexComponent( (BaseAddon) this, 503, -3, 1, 0, 1320, -1, "", 1);// 610
			AddComplexComponent( (BaseAddon) this, 497, -2, 4, 0, 1320, -1, "", 1);// 611
			AddComplexComponent( (BaseAddon) this, 497, -1, 4, 0, 1320, -1, "", 1);// 612
			AddComplexComponent( (BaseAddon) this, 2808, -9, 2, 0, 2721, -1, "", 1);// 613
			AddComplexComponent( (BaseAddon) this, 497, -10, 5, 0, 1931, -1, "", 1);// 614
			AddComplexComponent( (BaseAddon) this, 496, -8, 5, 0, 1931, -1, "", 1);// 615
			AddComplexComponent( (BaseAddon) this, 498, -8, 3, 0, 1931, -1, "", 1);// 616
			AddComplexComponent( (BaseAddon) this, 497, -9, 5, 0, 1931, -1, "", 1);// 617
			AddComplexComponent( (BaseAddon) this, 498, -8, 1, 0, 1931, -1, "", 1);// 618
			AddComplexComponent( (BaseAddon) this, 498, -8, 2, 0, 1931, -1, "", 1);// 619
			AddComplexComponent( (BaseAddon) this, 498, -8, 0, 0, 1931, -1, "", 1);// 620
			AddComplexComponent( (BaseAddon) this, 497, -14, 5, 0, 1931, -1, "", 1);// 621
			AddComplexComponent( (BaseAddon) this, 497, -15, 5, 0, 1931, -1, "", 1);// 622
			AddComplexComponent( (BaseAddon) this, 498, -8, 4, 0, 1931, -1, "", 1);// 623
			AddComplexComponent( (BaseAddon) this, 6093, -6, -2, 0, 0, -1, "tiny flowers", 1);// 624
			AddComplexComponent( (BaseAddon) this, 6093, -4, -7, 0, 0, -1, "tiny flowers", 1);// 625
			AddComplexComponent( (BaseAddon) this, 1542, -2, -3, 22, 1320, -1, "", 1);// 629
			AddComplexComponent( (BaseAddon) this, 1536, -1, -3, 22, 1320, -1, "", 1);// 630
			AddComplexComponent( (BaseAddon) this, 1535, -2, -1, 22, 1320, -1, "", 1);// 631
			AddComplexComponent( (BaseAddon) this, 1542, -15, -2, 23, 1931, -1, "", 1);// 637
			AddComplexComponent( (BaseAddon) this, 1536, -14, -2, 23, 1931, -1, "", 1);// 638
			AddComplexComponent( (BaseAddon) this, 889, -5, -1, 20, 2721, -1, "", 1);// 639
			AddComplexComponent( (BaseAddon) this, 2810, -14, -1, 0, 2721, -1, "", 1);// 640
			AddComplexComponent( (BaseAddon) this, 2807, -13, -2, 0, 2721, -1, "", 1);// 641
			AddComplexComponent( (BaseAddon) this, 2807, -11, -2, 0, 2721, -1, "", 1);// 642
			AddComplexComponent( (BaseAddon) this, 2755, -15, -2, 0, 2721, -1, "", 1);// 643
			AddComplexComponent( (BaseAddon) this, 2807, -14, -2, 0, 2721, -1, "", 1);// 644
			AddComplexComponent( (BaseAddon) this, 2807, -12, -2, 0, 2721, -1, "", 1);// 645
			AddComplexComponent( (BaseAddon) this, 2806, -15, -1, 0, 2721, -1, "", 1);// 646
			AddComplexComponent( (BaseAddon) this, 2807, -10, -2, 0, 2721, -1, "", 1);// 647
			AddComplexComponent( (BaseAddon) this, 503, -3, -2, 0, 1320, -1, "", 1);// 653
			AddComplexComponent( (BaseAddon) this, 503, -3, -1, 0, 1320, -1, "", 1);// 654
			AddComplexComponent( (BaseAddon) this, 502, -2, -4, 0, 1320, -1, "", 1);// 655
			AddComplexComponent( (BaseAddon) this, 502, -1, -4, 0, 1320, -1, "", 1);// 656
			AddComplexComponent( (BaseAddon) this, 502, 0, -4, 0, 1320, -1, "", 1);// 657
			AddComplexComponent( (BaseAddon) this, 503, -3, -3, 0, 1320, -1, "", 1);// 658
			AddComplexComponent( (BaseAddon) this, 2810, -10, -1, 0, 2721, -1, "", 1);// 659
			AddComplexComponent( (BaseAddon) this, 2810, -13, -1, 0, 2721, -1, "", 1);// 660
			AddComplexComponent( (BaseAddon) this, 2810, -11, -1, 0, 2721, -1, "", 1);// 661
			AddComplexComponent( (BaseAddon) this, 2757, -9, -2, 0, 2721, -1, "", 1);// 662
			AddComplexComponent( (BaseAddon) this, 2808, -9, -1, 0, 2721, -1, "", 1);// 663
			AddComplexComponent( (BaseAddon) this, 2810, -12, -1, 0, 2721, -1, "", 1);// 664
			AddComplexComponent( (BaseAddon) this, 502, -9, -3, 0, 1931, -1, "", 1);// 665
			AddComplexComponent( (BaseAddon) this, 498, -8, -1, 0, 1931, -1, "", 1);// 666
			AddComplexComponent( (BaseAddon) this, 739, -8, -3, 0, 1931, -1, "", 1);// 667
			AddComplexComponent( (BaseAddon) this, 502, -13, -3, 0, 1931, -1, "", 1);// 668
			AddComplexComponent( (BaseAddon) this, 502, -10, -3, 0, 1931, -1, "", 1);// 669
			AddComplexComponent( (BaseAddon) this, 502, -11, -3, 0, 1931, -1, "", 1);// 670
			AddComplexComponent( (BaseAddon) this, 502, -12, -3, 0, 1931, -1, "", 1);// 671
			AddComplexComponent( (BaseAddon) this, 502, -14, -3, 0, 1931, -1, "", 1);// 672
			AddComplexComponent( (BaseAddon) this, 498, -8, -2, 0, 1931, -1, "", 1);// 673
			AddComplexComponent( (BaseAddon) this, 502, -15, -3, 0, 1931, -1, "", 1);// 674
			AddComplexComponent( (BaseAddon) this, 1536, -24, 0, 45, 1931, -1, "", 1);// 678
			AddComplexComponent( (BaseAddon) this, 1536, -23, 0, 45, 1931, -1, "", 1);// 679
			AddComplexComponent( (BaseAddon) this, 1536, -22, 0, 45, 1931, -1, "", 1);// 680
			AddComplexComponent( (BaseAddon) this, 1536, -21, 0, 45, 1931, -1, "", 1);// 681
			AddComplexComponent( (BaseAddon) this, 1536, -20, 0, 45, 1931, -1, "", 1);// 682
			AddComplexComponent( (BaseAddon) this, 1541, -19, 0, 45, 1931, -1, "", 1);// 683
			AddComplexComponent( (BaseAddon) this, 1535, -26, 1, 45, 1931, -1, "", 1);// 684
			AddComplexComponent( (BaseAddon) this, 1542, -25, 1, 48, 1931, -1, "", 1);// 685
			AddComplexComponent( (BaseAddon) this, 1536, -24, 1, 48, 1931, -1, "", 1);// 686
			AddComplexComponent( (BaseAddon) this, 1536, -23, 1, 48, 1931, -1, "", 1);// 687
			AddComplexComponent( (BaseAddon) this, 1536, -22, 1, 48, 1931, -1, "", 1);// 688
			AddComplexComponent( (BaseAddon) this, 1536, -21, 1, 48, 1931, -1, "", 1);// 689
			AddComplexComponent( (BaseAddon) this, 1541, -20, 1, 48, 1931, -1, "", 1);// 690
			AddComplexComponent( (BaseAddon) this, 1538, -19, 1, 45, 1931, -1, "", 1);// 691
			AddComplexComponent( (BaseAddon) this, 1535, -28, 0, 23, 1931, -1, "", 1);// 692
			AddComplexComponent( (BaseAddon) this, 1535, -25, 2, 48, 1931, -1, "", 1);// 693
			AddComplexComponent( (BaseAddon) this, 1542, -24, 2, 51, 1931, -1, "", 1);// 694
			AddComplexComponent( (BaseAddon) this, 1536, -23, 2, 51, 1931, -1, "", 1);// 695
			AddComplexComponent( (BaseAddon) this, 1536, -22, 2, 51, 1931, -1, "", 1);// 696
			AddComplexComponent( (BaseAddon) this, 1541, -21, 2, 51, 1931, -1, "", 1);// 697
			AddComplexComponent( (BaseAddon) this, 1538, -20, 2, 48, 1931, -1, "", 1);// 698
			AddComplexComponent( (BaseAddon) this, 1538, -19, 2, 45, 1931, -1, "", 1);// 699
			AddComplexComponent( (BaseAddon) this, 1535, -26, 3, 45, 1931, -1, "", 1);// 700
			AddComplexComponent( (BaseAddon) this, 1535, -25, 3, 48, 1931, -1, "", 1);// 701
			AddComplexComponent( (BaseAddon) this, 1535, -24, 3, 51, 1931, -1, "", 1);// 702
			AddComplexComponent( (BaseAddon) this, 1542, -23, 3, 54, 1931, -1, "", 1);// 703
			AddComplexComponent( (BaseAddon) this, 1541, -22, 3, 54, 1931, -1, "", 1);// 704
			AddComplexComponent( (BaseAddon) this, 1538, -21, 3, 51, 1931, -1, "", 1);// 705
			AddComplexComponent( (BaseAddon) this, 1538, -20, 3, 48, 1931, -1, "", 1);// 706
			AddComplexComponent( (BaseAddon) this, 1538, -19, 3, 45, 1931, -1, "", 1);// 707
			AddComplexComponent( (BaseAddon) this, 1535, -26, 4, 45, 1931, -1, "", 1);// 708
			AddComplexComponent( (BaseAddon) this, 1535, -25, 4, 48, 1931, -1, "", 1);// 709
			AddComplexComponent( (BaseAddon) this, 1535, -24, 4, 51, 1931, -1, "", 1);// 710
			AddComplexComponent( (BaseAddon) this, 1540, -22, 4, 54, 1931, -1, "", 1);// 711
			AddComplexComponent( (BaseAddon) this, 1543, -23, 4, 54, 1931, -1, "", 1);// 712
			AddComplexComponent( (BaseAddon) this, 1538, -21, 4, 51, 1931, -1, "", 1);// 713
			AddComplexComponent( (BaseAddon) this, 1538, -20, 4, 48, 1931, -1, "", 1);// 714
			AddComplexComponent( (BaseAddon) this, 1538, -19, 4, 45, 1931, -1, "", 1);// 715
			AddComplexComponent( (BaseAddon) this, 1538, -19, 5, 45, 1931, -1, "", 1);// 716
			AddComplexComponent( (BaseAddon) this, 1538, -20, 5, 48, 1931, -1, "", 1);// 717
			AddComplexComponent( (BaseAddon) this, 1540, -21, 5, 51, 1931, -1, "", 1);// 718
			AddComplexComponent( (BaseAddon) this, 1537, -22, 5, 51, 1931, -1, "", 1);// 719
			AddComplexComponent( (BaseAddon) this, 1537, -23, 5, 51, 1931, -1, "", 1);// 720
			AddComplexComponent( (BaseAddon) this, 1543, -24, 5, 51, 1931, -1, "", 1);// 721
			AddComplexComponent( (BaseAddon) this, 1540, -19, 7, 45, 1931, -1, "", 1);// 722
			AddComplexComponent( (BaseAddon) this, 1537, -20, 7, 45, 1931, -1, "", 1);// 723
			AddComplexComponent( (BaseAddon) this, 1537, -21, 7, 45, 1931, -1, "", 1);// 724
			AddComplexComponent( (BaseAddon) this, 1537, -22, 7, 45, 1931, -1, "", 1);// 725
			AddComplexComponent( (BaseAddon) this, 1537, -23, 7, 45, 1931, -1, "", 1);// 726
			AddComplexComponent( (BaseAddon) this, 1537, -24, 7, 45, 1931, -1, "", 1);// 727
			AddComplexComponent( (BaseAddon) this, 1537, -25, 7, 45, 1931, -1, "", 1);// 728
			AddComplexComponent( (BaseAddon) this, 1543, -26, 7, 45, 1931, -1, "", 1);// 729
			AddComplexComponent( (BaseAddon) this, 1538, -19, 6, 45, 1931, -1, "", 1);// 730
			AddComplexComponent( (BaseAddon) this, 1540, -20, 6, 48, 1931, -1, "", 1);// 731
			AddComplexComponent( (BaseAddon) this, 1537, -21, 6, 48, 1931, -1, "", 1);// 732
			AddComplexComponent( (BaseAddon) this, 1537, -22, 6, 48, 1931, -1, "", 1);// 733
			AddComplexComponent( (BaseAddon) this, 1537, -23, 6, 48, 1931, -1, "", 1);// 734
			AddComplexComponent( (BaseAddon) this, 1535, -26, 6, 45, 1931, -1, "", 1);// 735
			AddComplexComponent( (BaseAddon) this, 1543, -25, 6, 48, 1931, -1, "", 1);// 736
			AddComplexComponent( (BaseAddon) this, 1537, -24, 6, 48, 1931, -1, "", 1);// 737
			AddComplexComponent( (BaseAddon) this, 889, -18, 5, 20, 2721, -1, "", 1);// 738
			AddComplexComponent( (BaseAddon) this, 889, -18, 4, 20, 2721, -1, "", 1);// 739
			AddComplexComponent( (BaseAddon) this, 889, -18, 3, 20, 2721, -1, "", 1);// 740
			AddComplexComponent( (BaseAddon) this, 889, -18, 2, 20, 2721, -1, "", 1);// 741
			AddComplexComponent( (BaseAddon) this, 889, -18, 6, 20, 2721, -1, "", 1);// 742
			AddComplexComponent( (BaseAddon) this, 889, -18, 0, 20, 2721, -1, "", 1);// 743
			AddComplexComponent( (BaseAddon) this, 889, -18, 1, 20, 2721, -1, "", 1);// 744
			AddComplexComponent( (BaseAddon) this, 9010, -31, 7, 0, 1195, 29, "", 1);// 745
			AddComplexComponent( (BaseAddon) this, 9010, -31, 6, 0, 1195, 29, "", 1);// 746
			AddComplexComponent( (BaseAddon) this, 9010, -31, 5, 0, 1195, 29, "", 1);// 747
			AddComplexComponent( (BaseAddon) this, 9010, -31, 4, 0, 1195, 29, "", 1);// 748
			AddComplexComponent( (BaseAddon) this, 9010, -31, 3, 0, 1195, 29, "", 1);// 749
			AddComplexComponent( (BaseAddon) this, 9010, -31, 1, 0, 1195, 29, "", 1);// 750
			AddComplexComponent( (BaseAddon) this, 9010, -31, 2, 0, 1195, 29, "", 1);// 751
			AddComplexComponent( (BaseAddon) this, 9010, -31, 0, 0, 1195, 29, "", 1);// 752
			AddComplexComponent( (BaseAddon) this, 2810, -24, 1, 0, 2721, -1, "", 1);// 765
			AddComplexComponent( (BaseAddon) this, 2808, -22, 2, 0, 2721, -1, "", 1);// 766
			AddComplexComponent( (BaseAddon) this, 2810, -26, 0, 0, 2721, -1, "", 1);// 767
			AddComplexComponent( (BaseAddon) this, 2810, -27, 1, 0, 2721, -1, "", 1);// 768
			AddComplexComponent( (BaseAddon) this, 2810, -23, 2, 0, 2721, -1, "", 1);// 769
			AddComplexComponent( (BaseAddon) this, 2810, -24, 0, 0, 2721, -1, "", 1);// 770
			AddComplexComponent( (BaseAddon) this, 2810, -26, 1, 0, 2721, -1, "", 1);// 771
			AddComplexComponent( (BaseAddon) this, 2806, -28, 2, 0, 2721, -1, "", 1);// 772
			AddComplexComponent( (BaseAddon) this, 2808, -22, 3, 0, 2721, -1, "", 1);// 773
			AddComplexComponent( (BaseAddon) this, 2754, -22, 4, 0, 2721, -1, "", 1);// 774
			AddComplexComponent( (BaseAddon) this, 2810, -25, 0, 0, 2721, -1, "", 1);// 775
			AddComplexComponent( (BaseAddon) this, 2810, -27, 3, 0, 2721, -1, "", 1);// 776
			AddComplexComponent( (BaseAddon) this, 2810, -24, 3, 0, 2721, -1, "", 1);// 777
			AddComplexComponent( (BaseAddon) this, 1535, -26, 5, 45, 1931, -1, "", 1);// 778
			AddComplexComponent( (BaseAddon) this, 1535, -25, 5, 48, 1931, -1, "", 1);// 779
			AddComplexComponent( (BaseAddon) this, 2809, -26, 4, 0, 2721, -1, "", 1);// 780
			AddComplexComponent( (BaseAddon) this, 2809, -27, 4, 0, 2721, -1, "", 1);// 781
			AddComplexComponent( (BaseAddon) this, 2810, -25, 2, 0, 2721, -1, "", 1);// 782
			AddComplexComponent( (BaseAddon) this, 2809, -25, 4, 0, 2721, -1, "", 1);// 783
			AddComplexComponent( (BaseAddon) this, 2810, -23, 0, 0, 2721, -1, "", 1);// 784
			AddComplexComponent( (BaseAddon) this, 2810, -24, 2, 0, 2721, -1, "", 1);// 785
			AddComplexComponent( (BaseAddon) this, 2806, -28, 3, 0, 2721, -1, "", 1);// 786
			AddComplexComponent( (BaseAddon) this, 2809, -24, 4, 0, 2721, -1, "", 1);// 787
			AddComplexComponent( (BaseAddon) this, 500, -29, 5, 0, 1931, -1, "", 1);// 788
			AddComplexComponent( (BaseAddon) this, 503, -29, 3, 0, 1931, -1, "", 1);// 789
			AddComplexComponent( (BaseAddon) this, 503, -29, 4, 0, 1931, -1, "", 1);// 790
			AddComplexComponent( (BaseAddon) this, 503, -29, 1, 0, 1931, -1, "", 1);// 791
			AddComplexComponent( (BaseAddon) this, 503, -29, 2, 0, 1931, -1, "", 1);// 792
			AddComplexComponent( (BaseAddon) this, 503, -29, 0, 0, 1931, -1, "", 1);// 793
			AddComplexComponent( (BaseAddon) this, 2809, -23, 4, 0, 2721, -1, "", 1);// 794
			AddComplexComponent( (BaseAddon) this, 2810, -25, 3, 0, 2721, -1, "", 1);// 795
			AddComplexComponent( (BaseAddon) this, 2756, -28, 4, 0, 2721, -1, "", 1);// 796
			AddComplexComponent( (BaseAddon) this, 2810, -26, 3, 0, 2721, -1, "", 1);// 797
			AddComplexComponent( (BaseAddon) this, 2810, -23, 3, 0, 2721, -1, "", 1);// 798
			AddComplexComponent( (BaseAddon) this, 2810, -27, 0, 0, 2721, -1, "", 1);// 799
			AddComplexComponent( (BaseAddon) this, 498, -21, 3, 0, 1931, -1, "", 1);// 800
			AddComplexComponent( (BaseAddon) this, 497, -22, 5, 0, 1931, -1, "", 1);// 801
			AddComplexComponent( (BaseAddon) this, 498, -21, 0, 0, 1931, -1, "", 1);// 802
			AddComplexComponent( (BaseAddon) this, 498, -21, 1, 0, 1931, -1, "", 1);// 803
			AddComplexComponent( (BaseAddon) this, 498, -21, 2, 0, 1931, -1, "", 1);// 804
			AddComplexComponent( (BaseAddon) this, 497, -23, 5, 0, 1931, -1, "", 1);// 805
			AddComplexComponent( (BaseAddon) this, 496, -21, 5, 0, 1931, -1, "", 1);// 806
			AddComplexComponent( (BaseAddon) this, 498, -21, 4, 0, 1931, -1, "", 1);// 807
			AddComplexComponent( (BaseAddon) this, 497, -27, 5, 0, 1931, -1, "", 1);// 808
			AddComplexComponent( (BaseAddon) this, 497, -28, 5, 0, 1931, -1, "", 1);// 809
			AddComplexComponent( (BaseAddon) this, 2810, -23, 1, 0, 2721, -1, "", 1);// 810
			AddComplexComponent( (BaseAddon) this, 2808, -22, 1, 0, 2721, -1, "", 1);// 811
			AddComplexComponent( (BaseAddon) this, 503, -16, 0, 0, 1931, -1, "", 1);// 812
			AddComplexComponent( (BaseAddon) this, 503, -16, 2, 0, 1931, -1, "", 1);// 813
			AddComplexComponent( (BaseAddon) this, 503, -16, 1, 0, 1931, -1, "", 1);// 814
			AddComplexComponent( (BaseAddon) this, 2810, -27, 2, 0, 2721, -1, "", 1);// 815
			AddComplexComponent( (BaseAddon) this, 503, -16, 4, 0, 1931, -1, "", 1);// 816
			AddComplexComponent( (BaseAddon) this, 503, -16, 3, 0, 1931, -1, "", 1);// 817
			AddComplexComponent( (BaseAddon) this, 500, -16, 5, 0, 1931, -1, "", 1);// 818
			AddComplexComponent( (BaseAddon) this, 2810, -25, 1, 0, 2721, -1, "", 1);// 819
			AddComplexComponent( (BaseAddon) this, 2808, -22, 0, 0, 2721, -1, "", 1);// 820
			AddComplexComponent( (BaseAddon) this, 2806, -28, 1, 0, 2721, -1, "", 1);// 821
			AddComplexComponent( (BaseAddon) this, 2810, -26, 2, 0, 2721, -1, "", 1);// 822
			AddComplexComponent( (BaseAddon) this, 2806, -28, 0, 0, 2721, -1, "", 1);// 823
			AddComplexComponent( (BaseAddon) this, 1542, -28, -2, 23, 1931, -1, "", 1);// 824
			AddComplexComponent( (BaseAddon) this, 1536, -27, -2, 23, 1931, -1, "", 1);// 825
			AddComplexComponent( (BaseAddon) this, 889, -18, -1, 20, 2721, -1, "", 1);// 826
			AddComplexComponent( (BaseAddon) this, 9010, -31, -2, 0, 1195, 29, "", 1);// 827
			AddComplexComponent( (BaseAddon) this, 9010, -31, -1, 0, 1195, 29, "", 1);// 828
			AddComplexComponent( (BaseAddon) this, 9010, -31, -3, 0, 1195, 29, "", 1);// 829
			AddComplexComponent( (BaseAddon) this, 9010, -31, -4, 0, 1195, 29, "", 1);// 830
			AddComplexComponent( (BaseAddon) this, 9010, -31, -5, 0, 1195, 29, "", 1);// 831
			AddComplexComponent( (BaseAddon) this, 2810, -27, -1, 0, 2721, -1, "", 1);// 840
			AddComplexComponent( (BaseAddon) this, 2757, -22, -2, 0, 2721, -1, "", 1);// 841
			AddComplexComponent( (BaseAddon) this, 2807, -23, -2, 0, 2721, -1, "", 1);// 842
			AddComplexComponent( (BaseAddon) this, 2810, -26, -1, 0, 2721, -1, "", 1);// 843
			AddComplexComponent( (BaseAddon) this, 2810, -24, -1, 0, 2721, -1, "", 1);// 844
			AddComplexComponent( (BaseAddon) this, 2810, -25, -1, 0, 2721, -1, "", 1);// 845
			AddComplexComponent( (BaseAddon) this, 2808, -22, -1, 0, 2721, -1, "", 1);// 846
			AddComplexComponent( (BaseAddon) this, 2807, -24, -2, 0, 2721, -1, "", 1);// 847
			AddComplexComponent( (BaseAddon) this, 2806, -28, -1, 0, 2721, -1, "", 1);// 848
			AddComplexComponent( (BaseAddon) this, 1543, -25, -7, 45, 37, -1, "", 1);// 849
			AddComplexComponent( (BaseAddon) this, 1537, -24, -7, 45, 37, -1, "", 1);// 850
			AddComplexComponent( (BaseAddon) this, 1537, -23, -7, 45, 37, -1, "", 1);// 851
			AddComplexComponent( (BaseAddon) this, 1537, -22, -7, 45, 37, -1, "", 1);// 852
			AddComplexComponent( (BaseAddon) this, 1537, -21, -7, 45, 37, -1, "", 1);// 853
			AddComplexComponent( (BaseAddon) this, 1537, -20, -7, 45, 37, -1, "", 1);// 854
			AddComplexComponent( (BaseAddon) this, 1537, -19, -7, 45, 37, -1, "", 1);// 855
			AddComplexComponent( (BaseAddon) this, 1540, -18, -7, 45, 37, -1, "", 1);// 856
			AddComplexComponent( (BaseAddon) this, 2810, -23, -1, 0, 2721, -1, "", 1);// 857
			AddComplexComponent( (BaseAddon) this, 888, -26, -6, 20, 1, -1, "", 1);// 858
			AddComplexComponent( (BaseAddon) this, 888, -25, -6, 20, 1, -1, "", 1);// 859
			AddComplexComponent( (BaseAddon) this, 888, -24, -6, 20, 1, -1, "", 1);// 860
			AddComplexComponent( (BaseAddon) this, 503, -29, -1, 0, 1931, -1, "", 1);// 861
			AddComplexComponent( (BaseAddon) this, 502, -28, -3, 0, 1931, -1, "", 1);// 862
			AddComplexComponent( (BaseAddon) this, 502, -27, -3, 0, 1931, -1, "", 1);// 863
			AddComplexComponent( (BaseAddon) this, 502, -25, -3, 0, 1931, -1, "", 1);// 864
			AddComplexComponent( (BaseAddon) this, 502, -24, -3, 0, 1931, -1, "", 1);// 865
			AddComplexComponent( (BaseAddon) this, 739, -21, -3, 0, 1931, -1, "", 1);// 866
			AddComplexComponent( (BaseAddon) this, 503, -29, -2, 0, 1931, -1, "", 1);// 867
			AddComplexComponent( (BaseAddon) this, 502, -22, -3, 0, 1931, -1, "", 1);// 868
			AddComplexComponent( (BaseAddon) this, 498, -21, -2, 0, 1931, -1, "", 1);// 869
			AddComplexComponent( (BaseAddon) this, 498, -21, -1, 0, 1931, -1, "", 1);// 870
			AddComplexComponent( (BaseAddon) this, 502, -26, -3, 0, 1931, -1, "", 1);// 871
			AddComplexComponent( (BaseAddon) this, 502, -23, -3, 0, 1931, -1, "", 1);// 872
			AddComplexComponent( (BaseAddon) this, 888, -23, -6, 20, 1, -1, "", 1);// 873
			AddComplexComponent( (BaseAddon) this, 503, -16, -1, 0, 1931, -1, "", 1);// 874
			AddComplexComponent( (BaseAddon) this, 503, -16, -2, 0, 1931, -1, "", 1);// 875
			AddComplexComponent( (BaseAddon) this, 888, -22, -6, 20, 1, -1, "", 1);// 876
			AddComplexComponent( (BaseAddon) this, 2755, -28, -2, 0, 2721, -1, "", 1);// 877
			AddComplexComponent( (BaseAddon) this, 2807, -25, -2, 0, 2721, -1, "", 1);// 878
			AddComplexComponent( (BaseAddon) this, 2807, -26, -2, 0, 2721, -1, "", 1);// 879
			AddComplexComponent( (BaseAddon) this, 888, -21, -6, 20, 1, -1, "", 1);// 880
			AddComplexComponent( (BaseAddon) this, 2807, -27, -2, 0, 2721, -1, "", 1);// 881
			AddComplexComponent( (BaseAddon) this, 888, -20, -6, 20, 1, -1, "", 1);// 882
			AddComplexComponent( (BaseAddon) this, 888, -19, -6, 20, 1, -1, "", 1);// 883

		}

		public LunaTrainingCenter5_Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LunaTrainingCenter5_AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LunaTrainingCenter5_Addon();
			}
		}

		[Constructable]
		public LunaTrainingCenter5_AddonDeed()
		{
			Name = "LunaTrainingCenter5_";
		}

		public LunaTrainingCenter5_AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}