
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Xmas_Gold_TreeAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Xmas_Gold_TreeAddonDeed();
			}
		}

		[ Constructable ]
		public Xmas_Gold_TreeAddon()
		{



			AddComplexComponent( (BaseAddon) this, 2885, 0, 0, 0, 2721, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2512, -1, 0, 11, 38, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2512, 0, -1, 10, 38, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2512, 1, -1, 13, 38, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2512, 0, 0, 7, 38, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2512, 1, 1, 25, 38, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2512, 1, 0, 14, 2721, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2512, 0, -1, 15, 38, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2512, -1, 0, 19, 38, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 2512, 0, 0, 22, 38, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2512, 0, 1, 15, 38, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2512, -1, 1, 13, 38, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 10299, 0, 0, 31, 2721, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 3203, 0, 0, 22, 2721, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 3203, 0, 0, 6, 2721, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 3203, 0, -1, 10, 2721, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 3203, -1, 0, 11, 2721, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 3203, -1, -1, 5, 2721, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 3203, 0, -1, 5, 2721, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 3203, -1, 0, 5, 2721, -1, "", 1);// 20

		}

		public Xmas_Gold_TreeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Xmas_Gold_TreeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Xmas_Gold_TreeAddon();
			}
		}

		[Constructable]
		public Xmas_Gold_TreeAddonDeed()
		{
			Name = "Xmas_Gold_Tree";
		}

		public Xmas_Gold_TreeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}