
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Christmas_Skinny_TreeAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {14201, 1, 1, 8}, {10299, 1, 2, 26}, {10299, 1, 2, 36}// 1	8	9	
			, {10299, 2, 1, 26}, {10299, 1, 1, 10}, {3302, 1, 1, 0}// 10	11	14	
			, {14201, 0, -1, 6}, {10299, 3, 0, 28}, {6093, -1, -2, 0}// 15	17	24	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Christmas_Skinny_TreeAddonDeed();
			}
		}

		[ Constructable ]
		public Christmas_Skinny_TreeAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 9014, 2, 1, 0, 0, 29, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 9014, 1, 2, 0, 0, 29, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 9014, 0, 3, 0, 0, 29, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 9014, 2, 1, 18, 0, 29, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 9014, 1, 2, 14, 0, 29, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 9014, 0, 3, 12, 0, 29, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 6093, -1, 1, 0, 0, -1, "flowers", 1);// 12
			AddComplexComponent( (BaseAddon) this, 6093, 1, 1, 10, 0, -1, "flowers", 1);// 13
			AddComplexComponent( (BaseAddon) this, 9014, 3, 0, 13, 0, 29, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 6093, -2, 0, 0, 0, -1, "flowers", 1);// 18
			AddComplexComponent( (BaseAddon) this, 6093, 1, -2, 6, 0, -1, "flowers", 1);// 19
			AddComplexComponent( (BaseAddon) this, 6093, -2, -1, 0, 0, -1, "flowers", 1);// 20
			AddComplexComponent( (BaseAddon) this, 6093, -2, -2, 0, 0, -1, "flowers", 1);// 21
			AddComplexComponent( (BaseAddon) this, 6093, 1, 0, 0, 0, -1, "flowers", 1);// 22
			AddComplexComponent( (BaseAddon) this, 6093, 1, -2, 0, 0, -1, "flowers", 1);// 23
			AddComplexComponent( (BaseAddon) this, 6093, 0, -1, 0, 0, -1, "flowers", 1);// 25
			AddComplexComponent( (BaseAddon) this, 6093, -1, -1, 0, 0, -1, "flowers", 1);// 26

		}

		public Christmas_Skinny_TreeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Christmas_Skinny_TreeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Christmas_Skinny_TreeAddon();
			}
		}

		[Constructable]
		public Christmas_Skinny_TreeAddonDeed()
		{
			Name = "Christmas_Skinny_Tree";
		}

		public Christmas_Skinny_TreeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}