
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Fall_Floral_Planter_1Addon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Fall_Floral_Planter_1AddonDeed();
			}
		}

		[ Constructable ]
		public Fall_Floral_Planter_1Addon()
		{



			AddComplexComponent( (BaseAddon) this, 9037, 1, 1, 21, 54, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2887, 0, 0, 0, 137, -1, "Fall Flowers Vase", 1);// 2
			AddComplexComponent( (BaseAddon) this, 3265, 0, 0, 14, 40, -1, "Fall Flowers", 1);// 3
			AddComplexComponent( (BaseAddon) this, 3231, 0, 0, 5, 1102, -1, "Fall Flowers", 1);// 4
			AddComplexComponent( (BaseAddon) this, 3224, 0, 0, 4, 1105, -1, "Fall Flowers", 1);// 5

		}

		public Fall_Floral_Planter_1Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Fall_Floral_Planter_1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Fall_Floral_Planter_1Addon();
			}
		}

		[Constructable]
		public Fall_Floral_Planter_1AddonDeed()
		{
			Name = "Fall_Floral_Planter_1";
		}

		public Fall_Floral_Planter_1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}