
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DdWHeartpond4x4Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6039, 1, 0, 0}, {6039, 1, 1, 0}, {6039, 0, 1, 0}// 1	2	3	
			, {6051, -1, 1, 0}, {6047, 1, -1, 0}, {6052, 0, 0, 0}// 4	5	6	
			, {6048, 0, 0, 0}, {6054, 0, -1, 0}, {6054, -1, 0, 0}// 7	8	9	
			, {6045, 2, 0, 0}, {6046, 2, 1, 0}, {6053, 2, -1, 0}// 10	11	12	
			, {6049, 0, 2, 0}, {6050, 1, 2, 0}, {6056, -1, 2, 0}// 13	14	15	
			, {6055, 2, 2, 0}// 16	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DdWHeartpond4x4AddonDeed();
			}
		}

		[ Constructable ]
		public DdWHeartpond4x4Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public DdWHeartpond4x4Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DdWHeartpond4x4AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DdWHeartpond4x4Addon();
			}
		}

		[Constructable]
		public DdWHeartpond4x4AddonDeed()
		{
			Name = "DdWHeartpond4x4";
		}

		public DdWHeartpond4x4AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}