
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DdWWillowTreeBlossom3Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3302, 0, 0, 0}, {3303, 0, 0, 0}, {3207, 0, 1, 28}// 1	2	3	
			, {3207, 1, 0, 28}, {3207, 0, 1, 20}, {3207, 1, 0, 22}// 4	5	6	
			, {3207, 0, 1, 15}, {3207, 1, 0, 15}// 7	8	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DdWWillowTreeBlossom3AddonDeed();
			}
		}

		[ Constructable ]
		public DdWWillowTreeBlossom3Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public DdWWillowTreeBlossom3Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DdWWillowTreeBlossom3AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DdWWillowTreeBlossom3Addon();
			}
		}

		[Constructable]
		public DdWWillowTreeBlossom3AddonDeed()
		{
			Name = "DdWWillowTreeBlossom3";
		}

		public DdWWillowTreeBlossom3AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}