
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GypsyWagonTentWallEast_Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {568, 4, 2, 0}, {568, 4, -1, 0}, {569, 4, 2, 0}// 1	2	3	
			, {569, 3, 2, 0}, {569, 2, 2, 0}, {569, 0, 2, 0}// 4	5	6	
			, {569, 1, 2, 0}, {569, -1, 2, 0}, {569, -2, 2, 0}// 7	8	9	
			, {569, -3, 2, 0}, {569, 4, -2, 0}, {569, 3, -2, 0}// 10	11	12	
			, {569, 2, -2, 0}, {569, 0, -2, 0}, {569, 1, -2, 0}// 13	14	15	
			, {569, -1, -2, 0}, {569, -2, -2, 0}, {568, -4, 2, 0}// 16	17	18	
			, {568, -4, 1, 0}, {568, -4, 0, 0}, {568, -4, -1, 0}// 19	20	21	
			, {569, -3, -2, 0}// 22	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new GypsyWagonTentWallEast_AddonDeed();
			}
		}

		[ Constructable ]
		public GypsyWagonTentWallEast_Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public GypsyWagonTentWallEast_Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GypsyWagonTentWallEast_AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GypsyWagonTentWallEast_Addon();
			}
		}

		[Constructable]
		public GypsyWagonTentWallEast_AddonDeed()
		{
			Name = "GypsyWagonTentWallEast_";
		}

		public GypsyWagonTentWallEast_AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}