
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class RevisedComputerDeskAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4032, 0, 1, 14}, {2454, 0, 0, 13}, {2929, 1, -1, 8}// 2	3	12	
			, {2928, 0, -1, 8}, {2928, -1, -1, 8}, {2948, -1, 0, 10}// 13	14	15	
			, {2948, -1, 1, 10}, {2929, 0, -1, 1}, {2930, -1, -1, 1}// 16	17	18	
			, {2930, -1, 0, 1}, {2929, -1, 1, 1}, {2929, 1, -1, 1}// 19	20	21	
			, {2928, -1, 1, 1}, {4553, 2, -1, 2}// 22	23	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new RevisedComputerDeskAddonDeed();
			}
		}

		[ Constructable ]
		public RevisedComputerDeskAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2854, -1, 2, 2, 0, 1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 7792, -1, 0, 9, 0, -1, "desk drawer", 1);// 4
			AddComplexComponent( (BaseAddon) this, 7792, -1, 1, 9, 0, -1, "desk drawer", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2900, 1, 1, 4, 0, -1, "computer chair", 1);// 6
			AddComplexComponent( (BaseAddon) this, 4175, 1, -1, 15, 0, -1, "clock", 1);// 7
			AddComplexComponent( (BaseAddon) this, 7830, 1, 0, 14, 0, -1, "cord", 1);// 8
			AddComplexComponent( (BaseAddon) this, 5983, 1, 0, 10, 0, -1, "keyboard", 1);// 9
			AddComplexComponent( (BaseAddon) this, 5356, 1, -1, 7, 0, -1, "computer", 1);// 10
			AddComplexComponent( (BaseAddon) this, 7893, 1, 0, 0, 0, -1, "monitor", 1);// 11

		}

		public RevisedComputerDeskAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class RevisedComputerDeskAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new RevisedComputerDeskAddon();
			}
		}

		[Constructable]
		public RevisedComputerDeskAddonDeed()
		{
			Name = "RevisedComputerDesk";
		}

		public RevisedComputerDeskAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}