
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class TabledFlowers1_Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2615, 1, 1, 10}, {2605, 0, 0, 6}, {2613, 0, 0, 6}// 2	3	6	
			, {2879, 0, 0, 0}// 7	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TabledFlowers1_AddonDeed();
			}
		}

		[ Constructable ]
		public TabledFlowers1_Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 3346, 1, 1, 16, 53, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3195, 0, 0, 7, 33, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 3184, 0, 0, 10, 1161, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 3195, 0, 1, 13, 33, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 3184, 0, 0, 13, 33, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 3184, 0, 0, 11, 33, -1, "", 1);// 10

		}

		public TabledFlowers1_Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TabledFlowers1_AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TabledFlowers1_Addon();
			}
		}

		[Constructable]
		public TabledFlowers1_AddonDeed()
		{
			Name = "TabledFlowers1_";
		}

		public TabledFlowers1_AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}