
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CedarSkullTree_Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6880, 0, 1, 11}, {6884, 1, 0, 8}, {6882, 1, 0, 17}// 1	2	3	
			, {6883, 0, 1, 15}, {6881, 0, 0, 17}, {6884, 1, 1, 41}// 4	5	6	
			, {6883, 0, 0, 29}, {6882, 0, 0, 28}, {6881, 0, 0, 24}// 7	8	9	
			, {6880, 0, 1, 21}, {3288, 0, 0, 0}// 10	11	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CedarSkullTree_AddonDeed();
			}
		}

		[ Constructable ]
		public CedarSkullTree_Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public CedarSkullTree_Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CedarSkullTree_AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CedarSkullTree_Addon();
			}
		}

		[Constructable]
		public CedarSkullTree_AddonDeed()
		{
			Name = "CedarSkullTree_";
		}

		public CedarSkullTree_AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}