
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BirchTreeTinyBlueBud_Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3146, 1, 0, 22}, {3146, 1, 0, 24}, {3146, 1, 0, 29}// 1	2	3	
			, {3146, 1, 0, 35}, {3146, 1, 1, 22}, {3146, 1, 1, 27}// 4	5	6	
			, {3146, 1, 1, 31}, {3146, 1, 1, 42}, {3146, 0, 1, 18}// 7	8	9	
			, {3146, 0, 1, 23}, {3146, 0, 1, 28}, {3146, 0, 1, 35}// 10	11	12	
			, {3280, 0, 0, 0}// 13	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BirchTreeTinyBlueBud_AddonDeed();
			}
		}

		[ Constructable ]
		public BirchTreeTinyBlueBud_Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public BirchTreeTinyBlueBud_Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BirchTreeTinyBlueBud_AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BirchTreeTinyBlueBud_Addon();
			}
		}

		[Constructable]
		public BirchTreeTinyBlueBud_AddonDeed()
		{
			Name = "BirchTreeTinyBlueBud_";
		}

		public BirchTreeTinyBlueBud_AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}